/** Biology missions. See physics.js for the shape of an entry. */

const biology = [
  {
    slug: 'cell-membranes',
    chapterId: 'biology.cells-microscopy',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Cell membranes',
    lab: 'osmosis',
    formula: '\\Psi_{in} = \\Psi_{out}',
    scenario: 'a tissue sample being kept alive during transport to a burns unit',
    crisis: 'The cells are swelling and will burst. The fluid around them sits at 0.9% solute, and the saline going into the container adds 0.3% for every gram per litre.',
    insight: 'A membrane lets water cross freely. Water always moves toward the more concentrated side until the two match.',
    resolution: 'At the solved dose the two sides match, nothing moves either way, and the tissue holds its shape.',
    model: {
      kind: 'fluxBalance',
      params: { outside: 0.9, perUnit: 0.3, leftName: 'Internal concentration', rightName: 'External concentration', productUnit: '%' },
      control: { label: 'Saline added', unit: 'g/L', min: 0, max: 8, precision: 2 },
      tolerance: 0.17,
      start: 8,
    },
  },
  {
    slug: 'osmosis',
    chapterId: 'biology.cells-microscopy',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Osmosis',
    lab: 'osmosis',
    formula: '\\Psi = \\Psi_s + \\Psi_p',
    scenario: 'a hydroponic bed where every seedling has wilted overnight',
    crisis: 'Water is being pulled back out of the roots. The root zone sits at 1.4 units of solute, and each scoop of fertiliser raises the feed by 0.35 units.',
    insight: 'Too much fertiliser can dehydrate a plant. Water leaves the roots when the outside is saltier than the inside.',
    resolution: 'At the solved number of scoops the feed matches the roots, water stops leaving, and the seedlings recover.',
    model: {
      kind: 'fluxBalance',
      params: { outside: 1.4, perUnit: 0.35, leftName: 'Feed concentration', rightName: 'Root concentration', productUnit: 'units' },
      control: { label: 'Fertiliser scoops per litre', unit: 'scoops', min: 0, max: 10, precision: 2 },
      tolerance: 0.21,
      start: 92,
    },
  },
  {
    slug: 'diffusion',
    chapterId: 'biology.cells-microscopy',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Diffusion',
    lab: 'osmosis',
    formula: 'J = -D\\nabla C',
    scenario: 'an incubator whose oxygen keeps pooling at one end',
    crisis: 'Gas keeps flowing instead of settling. The far chamber holds 6.5 mmol/L, and every dose injected into the near chamber lifts it by 1.3 mmol/L.',
    insight: 'Diffusion is driven by difference, not by amount. Once concentrations match, net movement stops.',
    resolution: 'At the solved number of doses the gradient disappears and the incubator stabilises.',
    model: {
      kind: 'fluxBalance',
      params: { outside: 6.5, perUnit: 1.3, leftName: 'Near chamber', rightName: 'Far chamber', productUnit: 'mmol/L' },
      control: { label: 'Oxygen doses injected', unit: 'doses', min: 0, max: 12, precision: 1 },
      tolerance: 0.27,
      start: 8,
    },
  },
  {
    slug: 'chloroplast-energy',
    chapterId: 'biology.plants-photosynthesis',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Chloroplast energy',
    lab: 'leaf',
    formula: 'glucose \\propto light',
    scenario: 'a vertical farm rationing electricity during a grid shortage',
    crisis: 'The crop needs 1.35 units of glucose per day. Each unit of light yields 0.045, and the lamp schedule is wrong.',
    insight: 'Light is the raw material of photosynthesis. Below a threshold, growth simply stops.',
    resolution: 'At the solved light exposure the crop makes exactly the glucose it needs, on the minimum power.',
    model: {
      kind: 'proportional',
      params: { k: 0.045, targetY: 1.35, leftName: 'Glucose produced', rightName: 'Crop requirement', productUnit: 'units' },
      control: { label: 'Light exposure', unit: 'h', min: 0, max: 65, precision: 2 },
      tolerance: 0.073,
      start: 8,
    },
  },
  {
    slug: 'mitochondria-output',
    chapterId: 'biology.cells-microscopy',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Mitochondria output',
    lab: 'mitochondria',
    formula: 'ATP \\propto O_2',
    scenario: 'an altitude training camp tracking why athletes fade after an hour',
    crisis: 'The session demands 88.4 units of ATP. Each unit of oxygen yields 2.6, and the oxygen delivery target is wrong.',
    insight: 'Aerobic respiration converts oxygen into usable energy. Run short of oxygen and the energy supply collapses.',
    resolution: 'At the solved oxygen delivery the athletes generate exactly the ATP the session demands.',
    model: {
      kind: 'proportional',
      params: { k: 2.6, targetY: 88.4, leftName: 'ATP generated', rightName: 'Session demand', productUnit: 'units' },
      control: { label: 'Oxygen delivery', unit: 'units', min: 0, max: 72, precision: 2 },
      tolerance: 4.7,
      start: 90,
    },
  },
  {
    slug: 'cell-division',
    chapterId: 'biology.cells-microscopy',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Cell division',
    lab: 'mitosis',
    formula: 'n = rt',
    scenario: 'a wound culture being grown to patch a graft',
    crisis: 'The graft needs 27 rounds of division. The culture divides 1.8 times per hour, and the incubation window is wrong.',
    insight: 'Cells divide on a clock. Rush the culture and the graft is too thin; overrun it and the cells exhaust their medium.',
    resolution: 'At the solved incubation time the culture reaches exactly 27 divisions.',
    model: {
      kind: 'proportional',
      params: { k: 1.8, targetY: 27, leftName: 'Divisions completed', rightName: 'Divisions required', productUnit: '' },
      control: { label: 'Incubation time', unit: 'h', min: 0, max: 32, precision: 2 },
      tolerance: 2.9,
      start: 8,
    },
  },
  {
    slug: 'dna-instructions',
    chapterId: 'biology.genetics-evolution',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'DNA instructions',
    lab: 'dna',
    formula: '3\\ bases = 1\\ codon',
    scenario: 'a gene sequencer flagging a read as corrupted',
    crisis: 'The clean read is 111 bases long. Every codon takes three bases, and the codon count on the report is wrong.',
    insight: 'DNA is read three letters at a time. Slip by a single base and every codon after it changes meaning.',
    resolution: 'At the solved codon count the read divides exactly and the sequence resolves.',
    model: {
      kind: 'ratioMatch',
      params: { a: 3, b: 111, c: 1, leftName: 'Bases consumed', rightName: 'Bases available', productUnit: 'bases' },
      control: { label: 'Codon count', unit: '', min: 0, max: 80, precision: 1 },
      tolerance: 6,
      start: 8,
    },
  },
  {
    slug: 'protein-synthesis',
    chapterId: 'biology.genetics-evolution',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Protein synthesis',
    lab: 'dna',
    formula: 'codon \\rightarrow amino\\ acid',
    scenario: 'an insulin production line running short of one amino acid',
    crisis: 'The chain needs 42 amino acids. Each comes from one codon, and the codon count loaded into the ribosome model is wrong.',
    insight: 'Each codon calls for exactly one amino acid. The order of the codons is the order of the protein.',
    resolution: 'At the solved codon count the chain assembles to full length.',
    model: {
      kind: 'ratioMatch',
      params: { a: 1, b: 1, c: 42, leftName: 'Amino acids called', rightName: 'Amino acids required', productUnit: '' },
      control: { label: 'Codons loaded', unit: '', min: 0, max: 90, precision: 1 },
      tolerance: 2.2,
      start: 90,
    },
  },
  {
    slug: 'immune-response',
    chapterId: 'biology.health-disease',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Immune response',
    lab: 'cell',
    formula: 'antibody = antigen',
    scenario: 'a ward tracking whether a patient is winning against an infection',
    crisis: 'The infection is neither clearing nor worsening. Antigen load sits at 60 units, and each batch of antibodies the body releases answers 12 of them.',
    insight: 'The immune system matches the threat. Too weak and infection wins; wildly excessive and the response damages the body.',
    resolution: 'At the solved number of batches the response exactly meets the antigen load and the infection turns.',
    model: {
      kind: 'fluxBalance',
      params: { outside: 60, perUnit: 12, leftName: 'Antibody response', rightName: 'Antigen load', productUnit: 'units' },
      control: { label: 'Antibody batches released', unit: 'batches', min: 0, max: 12, precision: 2 },
      tolerance: 0.27,
      start: 8,
    },
  },
  {
    slug: 'viral-defense',
    chapterId: 'biology.health-disease',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Viral defense',
    lab: 'cell',
    formula: 'load \\downarrow \\text{ as } response \\uparrow',
    scenario: 'a vaccination programme modelling how much coverage is enough',
    crisis: 'Outbreaks keep reseeding. Community viral pressure measures 48 units, and each round of vaccination adds 12 units of immune coverage.',
    insight: 'Protection is a population property, not just a personal one. Enough immune people and transmission chains break.',
    resolution: 'At the solved number of rounds coverage matches viral pressure and transmission stops spreading.',
    model: {
      kind: 'fluxBalance',
      params: { outside: 48, perUnit: 12, leftName: 'Immune coverage', rightName: 'Viral pressure', productUnit: 'units' },
      control: { label: 'Vaccination rounds', unit: 'rounds', min: 0, max: 10, precision: 2 },
      tolerance: 0.21,
      start: 92,
    },
  },
  {
    slug: 'food-webs',
    chapterId: 'biology.ecosystems',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Food webs',
    lab: 'ecosystem',
    formula: 'E_{next} = 0.1 E_{prev}',
    scenario: 'a reserve deciding how much grazing land its wolves require',
    crisis: 'The predator tier needs 4.2 energy units. Only a tenth of energy passes up each level, and the producer base is sized wrong.',
    insight: 'Roughly ninety percent of energy is lost at every step up a food chain. That is why top predators are always rare.',
    resolution: 'At the solved producer base the predator tier receives exactly the 4.2 units it needs.',
    model: {
      kind: 'proportional',
      params: { k: 0.1, targetY: 4.2, leftName: 'Energy reaching predators', rightName: 'Predator requirement', productUnit: 'units' },
      control: { label: 'Producer energy base', unit: 'units', min: 0, max: 90, precision: 2 },
      tolerance: 0.22,
      start: 8,
    },
  },
  {
    slug: 'predator-prey',
    chapterId: 'biology.ecosystems',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Predator-prey balance',
    lab: 'ecosystem',
    formula: '\\frac{dN}{dt} = rN\\left(1-\\frac{N}{K}\\right)',
    scenario: 'an island where an introduced deer herd is stripping the forest',
    crisis: 'The population keeps overshooting and crashing. The habitat supports 340 animals, and each breeding pair left on the island accounts for 4 of them.',
    insight: 'Populations do not grow forever. Growth slows as numbers approach what the habitat can actually support.',
    resolution: 'At the solved number of pairs the herd sits on capacity, growth reaches zero, and the population holds steady.',
    model: {
      kind: 'carryingCapacity',
      params: { capacity: 340, perUnit: 4, leftName: 'Herd size', rightName: 'Habitat capacity', productUnit: 'animals' },
      control: { label: 'Breeding pairs kept', unit: 'pairs', min: 0, max: 180, precision: 0 },
      tolerance: 4.5,
      start: 92,
    },
  },
  {
    slug: 'carrying-capacity',
    chapterId: 'biology.ecosystems',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Carrying capacity',
    lab: 'ecosystem',
    formula: 'N \\le K',
    scenario: 'a fishery setting a quota after two bad seasons',
    crisis: 'The quota in the plan is unsafe. The bay sustains 1250 tonnes of stock, and every licensed boat takes 25 tonnes out of it in a season.',
    insight: 'Carrying capacity is set by the scarcest resource, not the most abundant one.',
    resolution: 'At the solved number of licences the fleet lands exactly what the bay can carry and the quota is sustainable.',
    model: {
      kind: 'carryingCapacity',
      params: { capacity: 1250, perUnit: 25, leftName: 'Standing stock', rightName: 'Bay capacity', productUnit: 't' },
      control: { label: 'Licences issued', unit: 'boats', min: 0, max: 120, precision: 0 },
      tolerance: 2.6,
      start: 8,
    },
  },
  {
    slug: 'water-cycles',
    chapterId: 'biology.ecosystems',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Water cycles',
    lab: 'watercycle',
    formula: 'E + T = P',
    scenario: 'a catchment model that keeps predicting phantom floods',
    crisis: 'Evaporation accounts for 340 mm against a 505 mm total. The precipitation figure entered is wrong, so the balance never closes.',
    insight: 'Water is not consumed, only moved. Over a full cycle what leaves a catchment must equal what enters it.',
    resolution: 'At the solved precipitation the catchment balance closes and the flood predictions settle.',
    model: {
      kind: 'sumToConstant',
      params: { known: 340, total: 505, leftName: 'Water accounted', rightName: 'Catchment total', productUnit: 'mm' },
      control: { label: 'Precipitation', unit: 'mm', min: 0, max: 360, precision: 1 },
      tolerance: 9,
      start: 90,
    },
  },
  {
    slug: 'photosynthesis',
    chapterId: 'biology.plants-photosynthesis',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Photosynthesis',
    lab: 'leaf',
    formula: '6CO_2 + 6H_2O \\rightarrow C_6H_{12}O_6 + 6O_2',
    scenario: 'a sealed biosphere module scrubbing its own air',
    crisis: 'The plants must fix 0.8 mol of glucose. Each glucose takes six carbon dioxide molecules, and the CO₂ supply is set wrong.',
    insight: 'Photosynthesis is bookkeeping. Six carbon dioxide molecules go in for every one glucose that comes out.',
    resolution: 'At the solved CO₂ supply the module fixes exactly 0.8 mol of glucose and the air balances.',
    model: {
      kind: 'ratioMatch',
      params: { a: 1, b: 6, c: 0.8, leftName: 'CO₂ supplied', rightName: 'CO₂ required', productUnit: 'mol' },
      control: { label: 'Carbon dioxide supply', unit: 'mol', min: 0, max: 10, precision: 2 },
      tolerance: 0.25,
      start: 8,
    },
  },
  {
    slug: 'respiration',
    chapterId: 'biology.human-body',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Respiration',
    lab: 'lungs',
    formula: 'V_E = V_T f',
    scenario: 'a ventilator being set for a patient after surgery',
    crisis: 'The patient needs 7.5 L per minute of ventilation. Each breath delivers 0.5 L, and the rate on the machine is wrong.',
    insight: 'Minute ventilation is rate multiplied by depth. Shallow fast breathing can move less air than slow deep breathing.',
    resolution: 'At the solved rate the machine delivers exactly 7.5 L per minute.',
    model: {
      kind: 'rateVolume',
      params: { requiredOutput: 7.5, strokeVolume: 0.5, leftName: 'Minute ventilation', rightName: 'Patient requirement', productUnit: 'L/min' },
      control: { label: 'Breaths per minute', unit: '/min', min: 0, max: 32, precision: 1 },
      tolerance: 0.4,
      start: 90,
    },
  },
  {
    slug: 'pulmonary-volume',
    chapterId: 'biology.human-body',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Pulmonary volume',
    lab: 'lungs',
    formula: 'V_E = V_T f',
    scenario: 'a high-altitude clinic assessing a climber with shallow breathing',
    crisis: 'The climber needs 8.4 L per minute. Their tidal volume has dropped to 0.6 L, and the compensating rate is wrong.',
    insight: 'When depth falls, rate must rise to move the same air. The body makes this trade automatically, up to a limit.',
    resolution: 'At the solved rate the climber moves exactly 8.4 L per minute despite the shallow breaths.',
    model: {
      kind: 'rateVolume',
      params: { requiredOutput: 8.4, strokeVolume: 0.6, leftName: 'Minute ventilation', rightName: 'Oxygen demand', productUnit: 'L/min' },
      control: { label: 'Breathing rate', unit: '/min', min: 0, max: 30, precision: 1 },
      tolerance: 0.45,
      start: 8,
    },
  },
  {
    slug: 'cardiac-pulse',
    chapterId: 'biology.human-body',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Cardiac pulse',
    lab: 'heart',
    formula: 'CO = HR \\times SV',
    scenario: 'a marathon medical tent assessing a collapsed runner',
    crisis: 'The runner needs 5.4 L per minute of cardiac output. Each beat pushes 72 mL, and the assumed heart rate is wrong.',
    insight: 'Cardiac output is beats multiplied by the volume each beat moves. A strong heart can beat slower for the same output.',
    resolution: 'At the solved heart rate the output lands on exactly 5.4 L per minute.',
    model: {
      kind: 'rateVolume',
      params: { requiredOutput: 5.4, strokeVolume: 0.072, leftName: 'Cardiac output', rightName: 'Required output', productUnit: 'L/min' },
      control: { label: 'Heart rate', unit: 'bpm', min: 0, max: 160, precision: 0 },
      tolerance: 0.29,
      start: 92,
    },
  },
  {
    slug: 'blood-transport',
    chapterId: 'biology.human-body',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Blood transport',
    lab: 'heart',
    formula: 'Q = \\frac{\\Delta P}{R}',
    scenario: 'a dialysis line that keeps alarming for low flow',
    crisis: 'The circuit needs 0.65 L/min of flow through a fixed resistance. The pressure difference across the line is set wrong.',
    insight: 'Flow is driven by pressure difference and opposed by resistance. Narrow the tube and flow drops sharply.',
    resolution: 'At the solved pressure difference the circuit delivers exactly 0.65 L/min.',
    model: {
      kind: 'proportional',
      params: { k: 0.0125, targetY: 0.65, leftName: 'Achieved flow', rightName: 'Required flow', productUnit: 'L/min' },
      control: { label: 'Pressure difference', unit: 'mmHg', min: 0, max: 110, precision: 1 },
      tolerance: 0.034,
      start: 8,
    },
  },
  {
    slug: 'nervous-signals',
    chapterId: 'biology.human-body',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Nervous signals',
    lab: 'neuron',
    formula: 'v = \\frac{d}{t}',
    scenario: 'a nerve conduction test after a cycling accident',
    crisis: 'The signal must cross 1.8 m of nerve in 0.03 s to count as healthy. The measured conduction speed is wrong.',
    insight: 'Nerve signals are fast but not instant. Damage to the insulating sheath slows conduction measurably.',
    resolution: 'At the solved conduction speed the signal crosses in exactly 0.03 s and the nerve reads healthy.',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 1.8, leftB: 1, rightA: 0.03, leftName: 'Distance to cross', rightName: 'Speed × time', productUnit: 'm' },
      control: { label: 'Conduction speed', unit: 'm/s', min: 0, max: 130, precision: 1 },
      tolerance: 0.09,
      start: 8,
    },
  },
  {
    slug: 'plant-tropisms',
    chapterId: 'biology.plants-photosynthesis',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Plant tropisms',
    lab: 'leaf',
    formula: 'growth \\rightarrow stimulus',
    scenario: 'a research greenhouse where seedlings are bending into the walkway',
    crisis: 'The stems are tracking a light source at 38° off vertical. The corrective lamp angle is set wrong, so they keep leaning.',
    insight: 'Plants grow toward light by lengthening cells on the shaded side. The bend is growth, not movement.',
    resolution: 'At the solved lamp angle the stimulus is balanced and the seedlings grow straight.',
    model: {
      kind: 'fluxBalance',
      params: { outside: 38, leftName: 'Corrective lamp angle', rightName: 'Existing light angle', productUnit: '°' },
      control: { label: 'Corrective lamp angle', unit: '°', min: 0, max: 80, precision: 1 },
      tolerance: 2,
      start: 90,
    },
  },
  {
    slug: 'ecosystem-resilience',
    chapterId: 'biology.ecosystems',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Ecosystem resilience',
    lab: 'ecosystem',
    formula: 'resilience = diversity + recovery',
    scenario: 'a burnt hillside being replanted after a wildfire season',
    crisis: 'The slope supports 68 units of established growth. The replanting density is wrong, so young trees are competing themselves to death.',
    insight: 'Recovery is not about planting the most. It is about planting what the damaged system can currently support.',
    resolution: 'At the solved density the replanting matches what the slope can carry and the canopy re-establishes.',
    model: {
      kind: 'carryingCapacity',
      params: { capacity: 68, leftName: 'Replanting density', rightName: 'Slope capacity', productUnit: 'units' },
      control: { label: 'Replanting density', unit: 'units', min: 0, max: 145, precision: 1 },
      tolerance: 3.6,
      start: 92,
    },
  },
  {
    slug: 'biodiversity',
    chapterId: 'biology.ecosystems',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Biodiversity',
    lab: 'biodiversity',
    formula: 'stability \\propto biodiversity',
    scenario: 'a restored wetland being assessed for legal protection',
    crisis: 'The assessment is failing. The wetland can sustain 24 species at its current size, and each restored habitat patch brings back 3 of them.',
    insight: 'More species means more ways for a system to absorb a shock. Monocultures fail all at once.',
    resolution: 'At the solved number of patches the wetland sits exactly at its sustainable diversity.',
    model: {
      kind: 'carryingCapacity',
      params: { capacity: 24, perUnit: 3, leftName: 'Species present', rightName: 'Sustainable diversity', productUnit: 'species' },
      control: { label: 'Habitat patches restored', unit: 'patches', min: 0, max: 20, precision: 1 },
      tolerance: 0.42,
      start: 8,
    },
  },
  {
    slug: 'human-digestion',
    chapterId: 'biology.human-body',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Human digestion',
    lab: 'digestion',
    formula: 'absorbed = 0.62 \\times intake',
    scenario: 'a nutrition plan for a recovery ward',
    crisis: 'Patients must absorb 27.9 units of nutrient. Only 62% of intake is absorbed, and the prescribed intake is wrong.',
    insight: 'Eating is not absorbing. A large fraction of intake passes through without ever entering the bloodstream.',
    resolution: 'At the solved intake patients absorb exactly the 27.9 units the plan requires.',
    model: {
      kind: 'proportional',
      params: { k: 0.62, targetY: 27.9, leftName: 'Nutrient absorbed', rightName: 'Nutrient required', productUnit: 'units' },
      control: { label: 'Daily intake', unit: 'units', min: 0, max: 95, precision: 2 },
      tolerance: 1.5,
      start: 8,
    },
  },
  {
    slug: 'homeostasis',
    chapterId: 'biology.human-body',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Homeostasis',
    lab: 'cell',
    formula: '\\Delta_{internal} \\approx 0',
    scenario: 'a neonatal incubator drifting out of its safe band',
    crisis: 'The infant must be held at 37.0 °C core temperature. The incubator setpoint is wrong and the readout keeps climbing.',
    insight: 'Homeostasis is active work, not stillness. The body spends energy constantly to hold conditions steady.',
    resolution: 'At the solved setpoint the core temperature holds at 37.0 °C without correction.',
    model: {
      kind: 'fluxBalance',
      params: { outside: 37, leftName: 'Incubator setpoint', rightName: 'Target core temperature', productUnit: '°C' },
      control: { label: 'Incubator setpoint', unit: '°C', min: 33, max: 41, precision: 2 },
      tolerance: 0.2,
      start: 92,
    },
  },
  {
    slug: 'cell-magnification',
    chapterId: 'biology.cells-microscopy',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 5,
    title: 'Microscope magnification',
    lab: 'mitosis',
    formula: 'M = \\frac{\\text{image}}{\\text{actual}}',
    scenario: 'a school microscope being set up for a first look at onion skin',
    crisis: 'A cell 0.05 mm across has to appear 20 mm wide in the eyepiece for the class to sketch it. The objective in place gives nothing like that.',
    insight: 'Magnification is a ratio, not a size. It says how many times bigger the image is than the thing itself.',
    resolution: 'At the solved magnification the cell fills exactly the width the class needs to draw.',
    standardIds: ['cbse:5:2', 'uk:KS2:living-things'],
    model: {
      kind: 'proportional',
      params: { k: 0.05, targetY: 20, leftName: 'Image width', rightName: 'Required width', productUnit: 'mm' },
      control: { label: 'Magnification', unit: '×', min: 0, max: 900, precision: 0 },
      tolerance: 1.9,
      start: 92,
    },
  },
  {
    slug: 'surface-area-volume',
    chapterId: 'biology.cells-microscopy',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 9,
    title: 'Surface area to volume',
    lab: 'mitochondria',
    formula: '\\frac{SA}{V} = \\frac{6}{l}',
    scenario: 'a tissue-culture lab sizing agar cubes for a diffusion trial',
    crisis: 'The protocol demands a surface-to-volume ratio of exactly 4.0 per cm for the cubes to nourish through. The cubes cut this morning are the wrong size.',
    insight: 'As a cube grows, volume climbs faster than surface. That is why cells stay small and why large organisms need transport systems.',
    resolution: 'At the solved edge length the cubes hit the protocol ratio exactly.',
    standardIds: ['cbse:9:6', 'igcse:2.1'],
    model: {
      kind: 'proportional',
      params: { k: 4, targetY: 6, leftName: 'Ratio × edge', rightName: 'Six', productUnit: '' },
      control: { label: 'Cube edge', unit: 'cm', min: 0, max: 4, precision: 2 },
      tolerance: 0.55,
      start: 92,
    },
  },
  {
    slug: 'counting-heartbeats',
    chapterId: 'biology.human-body',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 3,
    title: 'Counting a pulse',
    lab: 'heart',
    formula: '\\text{beats} = \\text{rate} \\times \\text{time}',
    scenario: 'a school health check taking pulses after a skipping test',
    crisis: 'The nurse counts a resting rate of 84 beats per minute and the record sheet wants the count over a fixed run. The total on the sheet is 210.',
    insight: 'A rate tells you how much happens each minute. Multiplying by the minutes gives the whole count.',
    resolution: 'At the solved time the counted beats match the sheet exactly.',
    standardIds: ['cbse:3:8', 'uk:KS2:animals'],
    model: {
      kind: 'proportional',
      params: { k: 84, targetY: 210, leftName: 'Beats counted', rightName: 'Sheet total', productUnit: 'beats' },
      control: { label: 'Counting time', unit: 'min', min: 0, max: 6, precision: 2 },
      tolerance: 20,
      start: 92,
    },
  },
  {
    slug: 'balanced-plate',
    chapterId: 'biology.human-body',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 4,
    title: 'A balanced meal',
    lab: 'digestion',
    formula: '\\sum E = E_{\\text{total}}',
    scenario: 'a school kitchen planning a midday meal to a set energy figure',
    crisis: 'Rice and dal on the tray come to 1 480 kJ and the meal has to reach 2 100 kJ. The vegetable portion has not been decided.',
    insight: 'Energy from a meal is the sum of what every item on the plate contributes. No single food has to carry the whole figure.',
    resolution: 'At the solved portion energy the tray reaches exactly the meal target.',
    standardIds: ['cbse:4:3', 'uk:KS2:nutrition'],
    model: {
      kind: 'sumToConstant',
      params: { known: 1480, total: 2100, leftName: 'Tray energy', rightName: 'Meal target', productUnit: 'kJ' },
      control: { label: 'Vegetable energy', unit: 'kJ', min: 0, max: 1200, precision: 0 },
      tolerance: 30,
      start: 8,
    },
  },
  {
    slug: 'breathing-rate',
    chapterId: 'biology.human-body',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 7,
    title: 'Ventilation rate',
    lab: 'lungs',
    formula: 'V_{\\text{min}} = f \\times V_t',
    scenario: 'a high-altitude trekking clinic checking a client before a pass',
    crisis: 'Each breath moves 0.5 L and the clinic wants a minute volume of 7.5 L. The client\'s breathing rate is well off that figure.',
    insight: 'Minute volume is breaths per minute multiplied by the air each breath moves. Shallow fast breathing and deep slow breathing can give the same total.',
    resolution: 'At the solved rate the client\'s minute volume sits exactly where the clinic wants it.',
    standardIds: ['cbse:7:10', 'icse:7:respiration'],
    model: {
      kind: 'rateVolume',
      params: { requiredOutput: 7.5, strokeVolume: 0.5, leftName: 'Minute volume', rightName: 'Required volume', productUnit: 'L/min' },
      control: { label: 'Breathing rate', unit: 'breaths/min', min: 0, max: 32, precision: 0 },
      tolerance: 0.7,
      start: 92,
    },
  },
  {
    slug: 'reaction-time-relay',
    chapterId: 'biology.human-body',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Nerve signal speed',
    lab: 'neuron',
    formula: 't = \\frac{d}{v}',
    scenario: 'a sports lab measuring how fast a sprinter reacts to the gun',
    crisis: 'The nerve path from ear to leg runs 1.4 m and signals travel it at 70 m/s. The reaction budget logged for the conduction step is wrong.',
    insight: 'A nerve signal is fast but not instant. Distance divided by conduction speed gives the delay the body cannot avoid.',
    resolution: 'At the solved delay the conduction time matches the measured path exactly.',
    standardIds: ['cbse:8:8', 'icse:8:nervous-system'],
    model: {
      kind: 'proportional',
      params: { k: 70, targetY: 1.4, leftName: 'Distance covered', rightName: 'Nerve path', productUnit: 'm' },
      control: { label: 'Conduction time', unit: 's', min: 0, max: 0.06, precision: 4 },
      tolerance: 0.13,
      start: 92,
    },
  },
  {
    slug: 'seed-germination-water',
    chapterId: 'biology.plants-photosynthesis',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 2,
    title: 'Watering seed trays',
    lab: 'watercycle',
    formula: 'V = n \\times v',
    scenario: 'a nursery watering trays of seedlings before a hot afternoon',
    crisis: 'Every tray drinks 250 mL and the watering can holds 3 000 mL exactly. The gardener keeps running dry partway down the bench.',
    insight: 'Sharing a fixed amount between equal portions tells you how many portions you get. One can does not stretch further by wishing.',
    resolution: 'At the solved tray count the can empties exactly as the last tray is watered.',
    standardIds: ['cbse:2:6', 'uk:KS1:plants'],
    model: {
      kind: 'proportional',
      params: { k: 250, targetY: 3000, leftName: 'Water used', rightName: 'Can capacity', productUnit: 'mL' },
      control: { label: 'Trays watered', unit: 'trays', min: 0, max: 26, precision: 0 },
      tolerance: 280,
      start: 92,
    },
  },
  {
    slug: 'photosynthesis-rate',
    chapterId: 'biology.plants-photosynthesis',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 9,
    title: 'Limiting factors',
    lab: 'leaf',
    formula: 'r \\propto I',
    scenario: 'a research glasshouse tuning its lamps to a target growth rate',
    crisis: 'The crop fixes 0.045 mg of carbon per unit of light intensity and the trial demands 5.4 mg/h. The lamp bank is set well below that.',
    insight: 'Below saturation, photosynthesis climbs in step with light. Past it, some other factor takes over as the brake.',
    resolution: 'At the solved intensity the crop fixes carbon at exactly the trial rate.',
    standardIds: ['cbse:10:6', 'igcse:6.1'],
    model: {
      kind: 'proportional',
      params: { k: 0.045, targetY: 5.4, leftName: 'Carbon fixed', rightName: 'Trial rate', productUnit: 'mg/h' },
      control: { label: 'Light intensity', unit: 'units', min: 0, max: 260, precision: 0 },
      tolerance: 0.5,
      start: 92,
    },
  },
  {
    slug: 'food-chain-energy',
    chapterId: 'biology.ecosystems',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 4,
    title: 'Energy along a food chain',
    lab: 'biodiversity',
    formula: 'E_{n+1} = 0.1 E_n',
    scenario: 'a wetland survey explaining why big predators are rare',
    crisis: 'The plants at the base of this marsh carry 48 000 kJ and only a tenth passes to each level above. The heron count assumes far more energy reaches the top.',
    insight: 'Most energy at each step is spent living and lost as heat. Only a small fraction is left to build the level above.',
    resolution: 'At the solved energy the level above matches what the marsh can actually support.',
    standardIds: ['cbse:4:6', 'ngss:3-5-LS2-1'],
    model: {
      kind: 'proportional',
      params: { k: 10, targetY: 48000, leftName: 'Energy scaled up', rightName: 'Producer energy', productUnit: 'kJ' },
      control: { label: 'Energy at next level', unit: 'kJ', min: 0, max: 11000, precision: 0 },
      tolerance: 4400,
      start: 92,
    },
  },
  {
    slug: 'rainfall-catchment',
    chapterId: 'biology.ecosystems',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 7,
    title: 'Catchment and runoff',
    lab: 'watercycle',
    formula: 'V = A \\times d',
    scenario: 'a village sizing a rooftop rainwater tank before the monsoon',
    crisis: 'A season delivers 0.85 m of rain and the tank must fill with 102 m³ to see the village through. The roof area on the plan is wrong.',
    insight: 'Harvested water is rainfall depth multiplied by the area it lands on. A deeper monsoon and a wider roof do the same job.',
    resolution: 'At the solved roof area the season\'s rain fills the tank exactly.',
    standardIds: ['cbse:7:16', 'ngss:MS-ESS2-4'],
    model: {
      kind: 'proportional',
      params: { k: 0.85, targetY: 102, leftName: 'Water harvested', rightName: 'Tank capacity', productUnit: 'm³' },
      control: { label: 'Roof area', unit: 'm²', min: 0, max: 260, precision: 0 },
      tolerance: 9.5,
      start: 92,
    },
  },
  {
    slug: 'punnett-ratio',
    chapterId: 'biology.genetics-evolution',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Monohybrid ratio',
    lab: 'dna',
    formula: '3 : 1',
    scenario: 'a seed company checking a monohybrid cross against expectation',
    crisis: 'A cross of two heterozygotes should give three dominant offspring for every recessive one. The trial sowed 320 seeds and the recessive count on the tally sheet is disputed.',
    insight: 'A monohybrid cross gives a fixed ratio because each parent passes one allele at random. The ratio is a prediction, not a guarantee for small samples.',
    resolution: 'At the solved recessive count the tally matches the expected three-to-one split.',
    standardIds: ['cbse:10:9', 'icse:10:genetics', 'igcse:16.3'],
    model: {
      kind: 'proportional',
      params: { k: 4, targetY: 320, leftName: 'Total offspring implied', rightName: 'Seeds sown', productUnit: 'seeds' },
      control: { label: 'Recessive offspring', unit: 'seeds', min: 0, max: 190, precision: 0 },
      tolerance: 30,
      start: 92,
    },
  },
  {
    slug: 'vaccination-coverage',
    chapterId: 'biology.health-disease',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Herd immunity threshold',
    lab: 'cell',
    formula: 'V_c = 1 - \\frac{1}{R_0}',
    scenario: 'a district planning a measles campaign before the school year',
    crisis: 'The district holds 45 000 children and the threshold for this disease sits at 19 in every 20. The doses ordered fall short of that coverage.',
    insight: 'An outbreak stops spreading once enough of the population cannot pass it on. The threshold depends on how infectious the disease is.',
    resolution: 'At the solved number of doses the district reaches exactly its coverage threshold.',
    standardIds: ['cbse:8:2', 'igcse:10.2'],
    model: {
      kind: 'proportional',
      params: { k: 1, targetY: 42750, leftName: 'Children covered', rightName: 'Threshold coverage', productUnit: 'children' },
      control: { label: 'Doses delivered', unit: 'doses', min: 0, max: 45000, precision: 0 },
      tolerance: 4000,
      start: 8,
    },
  },
  {
    slug: 'sorting-living-things',
    chapterId: 'biology.cells-microscopy',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 1,
    title: 'Living and non-living',
    lab: 'cell',
    formula: 'n_{\\text{total}} = n_{\\text{living}} + n_{\\text{non}}',
    scenario: 'a nature walk sorting a collection tray back at the classroom',
    crisis: 'Twenty-four items came back from the walk and fifteen have been agreed as never-living. The living pile has not been counted.',
    insight: 'Sorting into two groups keeps the total fixed. Counting one group tells you the other without counting it again.',
    resolution: 'At the solved count both piles together account for the whole tray.',
    standardIds: ['cbse:1:3', 'ngss:K-2-LS1-1'],
    model: {
      kind: 'sumToConstant',
      params: { known: 15, total: 24, leftName: 'Items sorted', rightName: 'Items collected', productUnit: 'items' },
      control: { label: 'Living pile', unit: 'items', min: 0, max: 24, precision: 0 },
      tolerance: 0.7,
      start: 92,
    },
  },
  {
    slug: 'teeth-and-diet',
    chapterId: 'biology.human-body',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 2,
    title: 'Counting teeth',
    lab: 'digestion',
    formula: 'n_{\\text{total}} = n_{\\text{upper}} + n_{\\text{lower}}',
    scenario: 'a dental camp charting a child\'s milk teeth',
    crisis: 'A full set of milk teeth comes to twenty and the upper jaw chart shows eleven. The lower jaw column has been left blank.',
    insight: 'A full set is fixed, so the two jaws must share it between them. Counting one jaw settles the other.',
    resolution: 'At the solved count the chart totals a complete set of milk teeth.',
    standardIds: ['cbse:2:5', 'uk:KS1:animals'],
    model: {
      kind: 'sumToConstant',
      params: { known: 11, total: 20, leftName: 'Teeth charted', rightName: 'Full set', productUnit: 'teeth' },
      control: { label: 'Lower jaw teeth', unit: 'teeth', min: 0, max: 20, precision: 0 },
      tolerance: 0.7,
      start: 92,
    },
  },
  {
    slug: 'plant-parts-count',
    chapterId: 'biology.plants-photosynthesis',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 3,
    title: 'Roots, stems and leaves',
    lab: 'biodiversity',
    formula: 'n = k \\times p',
    scenario: 'a school garden club potting cuttings for a plant sale',
    crisis: 'Each cutting needs four leaves left on it and the club has 84 usable leaves stripped from the parent plant. The number of cuttings planned is wrong.',
    insight: 'A leaf is where a plant makes its food, so a cutting needs enough of them to survive. Sharing a fixed supply sets how many cuttings you get.',
    resolution: 'At the solved number of cuttings every leaf is used and none is wasted.',
    standardIds: ['cbse:3:6', 'uk:KS2:plants'],
    model: {
      kind: 'proportional',
      params: { k: 4, targetY: 84, leftName: 'Leaves used', rightName: 'Leaves available', productUnit: 'leaves' },
      control: { label: 'Cuttings potted', unit: 'cuttings', min: 0, max: 40, precision: 0 },
      tolerance: 7,
      start: 8,
    },
  },
  {
    slug: 'blood-circulation-output',
    chapterId: 'biology.human-body',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 9,
    title: 'Cardiac output',
    lab: 'heart',
    formula: 'CO = HR \\times SV',
    scenario: 'a cardiology unit checking output before clearing a patient to exercise',
    crisis: 'Each beat moves 0.07 L and the unit needs a cardiac output of 5.6 L per minute. The heart rate on the monitor sits away from that figure.',
    insight: 'Cardiac output is rate multiplied by the volume each beat moves. A trained heart reaches the same output at a lower rate.',
    resolution: 'At the solved rate the output lands exactly on the 5.6 L per minute target.',
    standardIds: ['cbse:10:6', 'icse:9:circulatory-system'],
    model: {
      kind: 'rateVolume',
      params: { requiredOutput: 5.6, strokeVolume: 0.07, leftName: 'Cardiac output', rightName: 'Required output', productUnit: 'L/min' },
      control: { label: 'Heart rate', unit: 'bpm', min: 0, max: 170, precision: 0 },
      tolerance: 0.5,
      start: 92,
    },
  },
  {
    slug: 'population-growth-limit',
    chapterId: 'biology.ecosystems',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 7,
    title: 'Carrying capacity',
    lab: 'biodiversity',
    formula: 'N = K',
    scenario: 'a reserve deciding how many deer a valley can carry through winter',
    crisis: 'The forage survey has fixed how many animals the valley can carry through winter, and the current herd is well above that line. The cull target has not been set.',
    insight: 'A habitat supports only as many animals as its scarcest resource allows. Above that line the population falls whatever anyone does.',
    resolution: 'At the solved herd size the valley supports the population through winter exactly.',
    standardIds: ['cbse:7:16', 'ngss:MS-LS2-1'],
    model: {
      kind: 'carryingCapacity',
      params: { capacity: 340, leftName: 'Herd size', rightName: 'Carrying capacity', productUnit: 'animals' },
      control: { label: 'Herd after cull', unit: 'animals', min: 0, max: 700, precision: 0 },
      tolerance: 22,
      start: 92,
    },
  },
  {
    slug: 'handwashing-spread',
    chapterId: 'biology.health-disease',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 3,
    title: 'Stopping germs spreading',
    lab: 'cell',
    formula: 'n_{\\text{blocked}} + n_{\\text{passed}} = n_{\\text{total}}',
    scenario: 'a school clinic charting absences through a stomach bug',
    crisis: 'Forty-five contacts were traced and thirty-one were stopped by handwashing before passing it on. The number who still spread it is not on the chart.',
    insight: 'Every contact either passes an infection on or does not. Simple hygiene moves people from one group to the other.',
    resolution: 'At the solved count the chart accounts for every traced contact.',
    standardIds: ['cbse:3:8', 'uk:KS2:health'],
    model: {
      kind: 'sumToConstant',
      params: { known: 31, total: 45, leftName: 'Contacts accounted for', rightName: 'Contacts traced', productUnit: 'contacts' },
      control: { label: 'Contacts who spread it', unit: 'contacts', min: 0, max: 45, precision: 0 },
      tolerance: 1.4,
      start: 92,
    },
  },
  {
    slug: 'root-water-uptake',
    chapterId: 'biology.plants-photosynthesis',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 7,
    title: 'Transpiration pull',
    lab: 'watercycle',
    formula: 'Q = A \\times r',
    scenario: 'an orchard scheduling irrigation against measured water loss',
    crisis: 'Each tree transpires 1.6 L a day per square metre of canopy and the block loses 240 L daily. The canopy area on the irrigation model is wrong.',
    insight: 'Water lost from leaves pulls more up from the roots. A larger canopy loses more and must be watered more.',
    resolution: 'At the solved canopy area the model matches the block\'s measured loss.',
    standardIds: ['cbse:7:11', 'igcse:6.3'],
    model: {
      kind: 'proportional',
      params: { k: 1.6, targetY: 240, leftName: 'Water transpired', rightName: 'Measured loss', productUnit: 'L/day' },
      control: { label: 'Canopy area', unit: 'm²', min: 0, max: 320, precision: 0 },
      tolerance: 22,
      start: 92,
    },
  },
  {
    slug: 'digestion-enzyme',
    chapterId: 'biology.human-body',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Enzymes and digestion',
    lab: 'digestion',
    formula: 'r \\propto [E]',
    scenario: 'a nutrition lab modelling starch breakdown in the small intestine',
    crisis: 'Each unit of amylase breaks down 0.45 g of starch per minute and the trial requires 5.4 g per minute. The enzyme concentration set is too low.',
    insight: 'An enzyme is a catalyst the body builds. Rate climbs with concentration until the substrate itself runs short.',
    resolution: 'At the solved concentration the model breaks starch down at exactly the trial rate.',
    standardIds: ['cbse:8:2', 'icse:8:digestion'],
    model: {
      kind: 'proportional',
      params: { k: 0.45, targetY: 5.4, leftName: 'Starch broken down', rightName: 'Trial rate', productUnit: 'g/min' },
      control: { label: 'Amylase concentration', unit: 'units', min: 0, max: 26, precision: 1 },
      tolerance: 0.5,
      start: 92,
    },
  },
];

export default biology;
