/** Biology missions. See physics.js for the shape of an entry. */

const biology = [
  {
    slug: 'cell-membranes',
    title: 'Cell membranes',
    lab: 'cell',
    formula: '\\Psi_{in} = \\Psi_{out}',
    scenario: 'a tissue sample being kept alive during transport to a burns unit',
    crisis: 'The surrounding fluid sits at 0.9% solute. The bathing solution inside the container is set wrong, so the cells are swelling.',
    insight: 'A membrane lets water cross freely. Water always moves toward the more concentrated side until the two match.',
    resolution: 'At the solved concentration nothing moves either way, and the tissue holds its shape.',
    model: {
      kind: 'fluxBalance',
      params: { outside: 0.9, leftName: 'Internal concentration', rightName: 'External concentration', productUnit: '%' },
      control: { label: 'Bathing solution', unit: '%', min: 0, max: 2, precision: 3 },
      tolerance: 0.05,
      start: 8,
    },
  },
  {
    slug: 'osmosis',
    title: 'Osmosis',
    lab: 'osmosis',
    formula: '\\Psi = \\Psi_s + \\Psi_p',
    scenario: 'a hydroponic bed where every seedling has wilted overnight',
    crisis: 'The root zone sits at 1.4 units of solute. The nutrient feed is mixed wrong, and water is being pulled out of the roots.',
    insight: 'Too much fertiliser can dehydrate a plant. Water leaves the roots when the outside is saltier than the inside.',
    resolution: 'At the solved feed concentration water stops leaving the roots and the seedlings recover.',
    model: {
      kind: 'fluxBalance',
      params: { outside: 1.4, leftName: 'Feed concentration', rightName: 'Root concentration', productUnit: 'units' },
      control: { label: 'Nutrient feed', unit: 'units', min: 0, max: 3, precision: 3 },
      tolerance: 0.075,
      start: 92,
    },
  },
  {
    slug: 'diffusion',
    title: 'Diffusion',
    lab: 'osmosis',
    formula: 'J = -D\\nabla C',
    scenario: 'an incubator whose oxygen keeps pooling at one end',
    crisis: 'The far chamber holds 6.5 mmol/L. The near chamber is set wrong, so gas keeps flowing instead of settling.',
    insight: 'Diffusion is driven by difference, not by amount. Once concentrations match, net movement stops.',
    resolution: 'At the solved concentration the gradient disappears and the incubator stabilises.',
    model: {
      kind: 'fluxBalance',
      params: { outside: 6.5, leftName: 'Near chamber', rightName: 'Far chamber', productUnit: 'mmol/L' },
      control: { label: 'Near chamber concentration', unit: 'mmol/L', min: 0, max: 14, precision: 2 },
      tolerance: 0.35,
      start: 8,
    },
  },
  {
    slug: 'chloroplast-energy',
    title: 'Chloroplast energy',
    lab: 'ecosystem',
    formula: 'glucose \\propto light',
    scenario: 'a vertical farm rationing electricity during a grid shortage',
    crisis: 'The crop needs 1.35 units of glucose per day. Each unit of light yields 0.045, and the lamp schedule is wrong.',
    insight: 'Light is the raw material of photosynthesis. Below a threshold, growth simply stops.',
    resolution: 'At the solved light exposure the crop makes exactly the glucose it needs, on the minimum power.',
    model: {
      kind: 'proportional',
      params: { k: 0.045, targetY: 1.35, leftName: 'Glucose produced', rightName: 'Crop requirement', productUnit: 'units' },
      control: { label: 'Light exposure', unit: 'h', min: 0, max: 65, precision: 2 },
      tolerance: 0.073,
      start: 8,
    },
  },
  {
    slug: 'mitochondria-output',
    title: 'Mitochondria output',
    lab: 'lungs',
    formula: 'ATP \\propto O_2',
    scenario: 'an altitude training camp tracking why athletes fade after an hour',
    crisis: 'The session demands 88.4 units of ATP. Each unit of oxygen yields 2.6, and the oxygen delivery target is wrong.',
    insight: 'Aerobic respiration converts oxygen into usable energy. Run short of oxygen and the energy supply collapses.',
    resolution: 'At the solved oxygen delivery the athletes generate exactly the ATP the session demands.',
    model: {
      kind: 'proportional',
      params: { k: 2.6, targetY: 88.4, leftName: 'ATP generated', rightName: 'Session demand', productUnit: 'units' },
      control: { label: 'Oxygen delivery', unit: 'units', min: 0, max: 72, precision: 2 },
      tolerance: 4.7,
      start: 90,
    },
  },
  {
    slug: 'cell-division',
    title: 'Cell division',
    lab: 'cell',
    formula: 'n = rt',
    scenario: 'a wound culture being grown to patch a graft',
    crisis: 'The graft needs 27 rounds of division. The culture divides 1.8 times per hour, and the incubation window is wrong.',
    insight: 'Cells divide on a clock. Rush the culture and the graft is too thin; overrun it and the cells exhaust their medium.',
    resolution: 'At the solved incubation time the culture reaches exactly 27 divisions.',
    model: {
      kind: 'proportional',
      params: { k: 1.8, targetY: 27, leftName: 'Divisions completed', rightName: 'Divisions required', productUnit: '' },
      control: { label: 'Incubation time', unit: 'h', min: 0, max: 32, precision: 2 },
      tolerance: 2.9,
      start: 8,
    },
  },
  {
    slug: 'dna-instructions',
    title: 'DNA instructions',
    lab: 'cell',
    formula: '3\\ bases = 1\\ codon',
    scenario: 'a gene sequencer flagging a read as corrupted',
    crisis: 'The clean read is 111 bases long. Every codon takes three bases, and the codon count on the report is wrong.',
    insight: 'DNA is read three letters at a time. Slip by a single base and every codon after it changes meaning.',
    resolution: 'At the solved codon count the read divides exactly and the sequence resolves.',
    model: {
      kind: 'ratioMatch',
      params: { a: 3, b: 111, c: 1, leftName: 'Bases consumed', rightName: 'Bases available', productUnit: 'bases' },
      control: { label: 'Codon count', unit: '', min: 0, max: 80, precision: 1 },
      tolerance: 6,
      start: 8,
    },
  },
  {
    slug: 'protein-synthesis',
    title: 'Protein synthesis',
    lab: 'cell',
    formula: 'codon \\rightarrow amino\\ acid',
    scenario: 'an insulin production line running short of one amino acid',
    crisis: 'The chain needs 42 amino acids. Each comes from one codon, and the codon count loaded into the ribosome model is wrong.',
    insight: 'Each codon calls for exactly one amino acid. The order of the codons is the order of the protein.',
    resolution: 'At the solved codon count the chain assembles to full length.',
    model: {
      kind: 'ratioMatch',
      params: { a: 1, b: 1, c: 42, leftName: 'Amino acids called', rightName: 'Amino acids required', productUnit: '' },
      control: { label: 'Codons loaded', unit: '', min: 0, max: 90, precision: 1 },
      tolerance: 2.2,
      start: 90,
    },
  },
  {
    slug: 'immune-response',
    title: 'Immune response',
    lab: 'cell',
    formula: 'antibody = antigen',
    scenario: 'a ward tracking whether a patient is winning against an infection',
    crisis: 'Antigen load sits at 62 units. The antibody response is set wrong, so the infection is neither clearing nor worsening on the chart.',
    insight: 'The immune system matches the threat. Too weak and infection wins; wildly excessive and the response damages the body.',
    resolution: 'At the solved antibody level the response exactly meets the antigen load and the infection turns.',
    model: {
      kind: 'fluxBalance',
      params: { outside: 62, leftName: 'Antibody response', rightName: 'Antigen load', productUnit: 'units' },
      control: { label: 'Antibody response', unit: 'units', min: 0, max: 130, precision: 1 },
      tolerance: 3.2,
      start: 8,
    },
  },
  {
    slug: 'viral-defense',
    title: 'Viral defense',
    lab: 'cell',
    formula: 'load \\downarrow \\text{ as } response \\uparrow',
    scenario: 'a vaccination programme modelling how much coverage is enough',
    crisis: 'Community viral pressure measures 48 units. The modelled immune coverage does not meet it, so outbreaks keep reseeding.',
    insight: 'Protection is a population property, not just a personal one. Enough immune people and transmission chains break.',
    resolution: 'At the solved coverage the response matches viral pressure and transmission stops spreading.',
    model: {
      kind: 'fluxBalance',
      params: { outside: 48, leftName: 'Immune coverage', rightName: 'Viral pressure', productUnit: 'units' },
      control: { label: 'Immune coverage', unit: 'units', min: 0, max: 100, precision: 1 },
      tolerance: 2.5,
      start: 92,
    },
  },
  {
    slug: 'food-webs',
    title: 'Food webs',
    lab: 'ecosystem',
    formula: 'E_{next} = 0.1 E_{prev}',
    scenario: 'a reserve deciding how much grazing land its wolves require',
    crisis: 'The predator tier needs 4.2 energy units. Only a tenth of energy passes up each level, and the producer base is sized wrong.',
    insight: 'Roughly ninety percent of energy is lost at every step up a food chain. That is why top predators are always rare.',
    resolution: 'At the solved producer base the predator tier receives exactly the 4.2 units it needs.',
    model: {
      kind: 'proportional',
      params: { k: 0.1, targetY: 4.2, leftName: 'Energy reaching predators', rightName: 'Predator requirement', productUnit: 'units' },
      control: { label: 'Producer energy base', unit: 'units', min: 0, max: 90, precision: 2 },
      tolerance: 0.22,
      start: 8,
    },
  },
  {
    slug: 'predator-prey',
    title: 'Predator-prey balance',
    lab: 'ecosystem',
    formula: '\\frac{dN}{dt} = rN\\left(1-\\frac{N}{K}\\right)',
    scenario: 'an island where an introduced deer herd is stripping the forest',
    crisis: 'The habitat supports 340 animals. The current herd size sits far from that, so the population keeps overshooting and crashing.',
    insight: 'Populations do not grow forever. Growth slows as numbers approach what the habitat can actually support.',
    resolution: 'At the solved herd size growth reaches zero and the population holds steady.',
    model: {
      kind: 'carryingCapacity',
      params: { capacity: 340, leftName: 'Herd size', rightName: 'Habitat capacity', productUnit: 'animals' },
      control: { label: 'Herd size', unit: 'animals', min: 0, max: 720, precision: 0 },
      tolerance: 18,
      start: 92,
    },
  },
  {
    slug: 'carrying-capacity',
    title: 'Carrying capacity',
    lab: 'ecosystem',
    formula: 'N \\le K',
    scenario: 'a fishery setting a quota after two bad seasons',
    crisis: 'The bay sustains 1250 tonnes of stock. The standing stock target in the plan is wrong, so the quota is unsafe.',
    insight: 'Carrying capacity is set by the scarcest resource, not the most abundant one.',
    resolution: 'At the solved standing stock the fishery sits exactly at capacity and the quota is sustainable.',
    model: {
      kind: 'carryingCapacity',
      params: { capacity: 1250, leftName: 'Standing stock', rightName: 'Bay capacity', productUnit: 't' },
      control: { label: 'Standing stock', unit: 't', min: 0, max: 2600, precision: 0 },
      tolerance: 65,
      start: 8,
    },
  },
  {
    slug: 'water-cycles',
    title: 'Water cycles',
    lab: 'ecosystem',
    formula: 'E + T = P',
    scenario: 'a catchment model that keeps predicting phantom floods',
    crisis: 'Evaporation accounts for 340 mm against a 505 mm total. The precipitation figure entered is wrong, so the balance never closes.',
    insight: 'Water is not consumed, only moved. Over a full cycle what leaves a catchment must equal what enters it.',
    resolution: 'At the solved precipitation the catchment balance closes and the flood predictions settle.',
    model: {
      kind: 'sumToConstant',
      params: { known: 340, total: 505, leftName: 'Water accounted', rightName: 'Catchment total', productUnit: 'mm' },
      control: { label: 'Precipitation', unit: 'mm', min: 0, max: 360, precision: 1 },
      tolerance: 9,
      start: 90,
    },
  },
  {
    slug: 'photosynthesis',
    title: 'Photosynthesis',
    lab: 'ecosystem',
    formula: '6CO_2 + 6H_2O \\rightarrow C_6H_{12}O_6 + 6O_2',
    scenario: 'a sealed biosphere module scrubbing its own air',
    crisis: 'The plants must fix 0.8 mol of glucose. Each glucose takes six carbon dioxide molecules, and the CO₂ supply is set wrong.',
    insight: 'Photosynthesis is bookkeeping. Six carbon dioxide molecules go in for every one glucose that comes out.',
    resolution: 'At the solved CO₂ supply the module fixes exactly 0.8 mol of glucose and the air balances.',
    model: {
      kind: 'ratioMatch',
      params: { a: 1, b: 6, c: 0.8, leftName: 'CO₂ supplied', rightName: 'CO₂ required', productUnit: 'mol' },
      control: { label: 'Carbon dioxide supply', unit: 'mol', min: 0, max: 10, precision: 2 },
      tolerance: 0.25,
      start: 8,
    },
  },
  {
    slug: 'respiration',
    title: 'Respiration',
    lab: 'lungs',
    formula: 'V_E = V_T f',
    scenario: 'a ventilator being set for a patient after surgery',
    crisis: 'The patient needs 7.5 L per minute of ventilation. Each breath delivers 0.5 L, and the rate on the machine is wrong.',
    insight: 'Minute ventilation is rate multiplied by depth. Shallow fast breathing can move less air than slow deep breathing.',
    resolution: 'At the solved rate the machine delivers exactly 7.5 L per minute.',
    model: {
      kind: 'rateVolume',
      params: { requiredOutput: 7.5, strokeVolume: 0.5, leftName: 'Minute ventilation', rightName: 'Patient requirement', productUnit: 'L/min' },
      control: { label: 'Breaths per minute', unit: '/min', min: 0, max: 32, precision: 1 },
      tolerance: 0.4,
      start: 90,
    },
  },
  {
    slug: 'pulmonary-volume',
    title: 'Pulmonary volume',
    lab: 'lungs',
    formula: 'V_E = V_T f',
    scenario: 'a high-altitude clinic assessing a climber with shallow breathing',
    crisis: 'The climber needs 8.4 L per minute. Their tidal volume has dropped to 0.6 L, and the compensating rate is wrong.',
    insight: 'When depth falls, rate must rise to move the same air. The body makes this trade automatically, up to a limit.',
    resolution: 'At the solved rate the climber moves exactly 8.4 L per minute despite the shallow breaths.',
    model: {
      kind: 'rateVolume',
      params: { requiredOutput: 8.4, strokeVolume: 0.6, leftName: 'Minute ventilation', rightName: 'Oxygen demand', productUnit: 'L/min' },
      control: { label: 'Breathing rate', unit: '/min', min: 0, max: 30, precision: 1 },
      tolerance: 0.45,
      start: 8,
    },
  },
  {
    slug: 'cardiac-pulse',
    title: 'Cardiac pulse',
    lab: 'lungs',
    formula: 'CO = HR \\times SV',
    scenario: 'a marathon medical tent assessing a collapsed runner',
    crisis: 'The runner needs 5.4 L per minute of cardiac output. Each beat pushes 72 mL, and the assumed heart rate is wrong.',
    insight: 'Cardiac output is beats multiplied by the volume each beat moves. A strong heart can beat slower for the same output.',
    resolution: 'At the solved heart rate the output lands on exactly 5.4 L per minute.',
    model: {
      kind: 'rateVolume',
      params: { requiredOutput: 5.4, strokeVolume: 0.072, leftName: 'Cardiac output', rightName: 'Required output', productUnit: 'L/min' },
      control: { label: 'Heart rate', unit: 'bpm', min: 0, max: 160, precision: 0 },
      tolerance: 0.29,
      start: 92,
    },
  },
  {
    slug: 'blood-transport',
    title: 'Blood transport',
    lab: 'lungs',
    formula: 'Q = \\frac{\\Delta P}{R}',
    scenario: 'a dialysis line that keeps alarming for low flow',
    crisis: 'The circuit needs 0.65 L/min of flow through a fixed resistance. The pressure difference across the line is set wrong.',
    insight: 'Flow is driven by pressure difference and opposed by resistance. Narrow the tube and flow drops sharply.',
    resolution: 'At the solved pressure difference the circuit delivers exactly 0.65 L/min.',
    model: {
      kind: 'proportional',
      params: { k: 0.0125, targetY: 0.65, leftName: 'Achieved flow', rightName: 'Required flow', productUnit: 'L/min' },
      control: { label: 'Pressure difference', unit: 'mmHg', min: 0, max: 110, precision: 1 },
      tolerance: 0.034,
      start: 8,
    },
  },
  {
    slug: 'nervous-signals',
    title: 'Nervous signals',
    lab: 'cell',
    formula: 'v = \\frac{d}{t}',
    scenario: 'a nerve conduction test after a cycling accident',
    crisis: 'The signal must cross 1.8 m of nerve in 0.03 s to count as healthy. The measured conduction speed is wrong.',
    insight: 'Nerve signals are fast but not instant. Damage to the insulating sheath slows conduction measurably.',
    resolution: 'At the solved conduction speed the signal crosses in exactly 0.03 s and the nerve reads healthy.',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 1.8, leftB: 1, rightA: 0.03, leftName: 'Distance to cross', rightName: 'Speed × time', productUnit: 'm' },
      control: { label: 'Conduction speed', unit: 'm/s', min: 0, max: 130, precision: 1 },
      tolerance: 0.09,
      start: 8,
    },
  },
  {
    slug: 'plant-tropisms',
    title: 'Plant tropisms',
    lab: 'ecosystem',
    formula: 'growth \\rightarrow stimulus',
    scenario: 'a research greenhouse where seedlings are bending into the walkway',
    crisis: 'The stems are tracking a light source at 38° off vertical. The corrective lamp angle is set wrong, so they keep leaning.',
    insight: 'Plants grow toward light by lengthening cells on the shaded side. The bend is growth, not movement.',
    resolution: 'At the solved lamp angle the stimulus is balanced and the seedlings grow straight.',
    model: {
      kind: 'fluxBalance',
      params: { outside: 38, leftName: 'Corrective lamp angle', rightName: 'Existing light angle', productUnit: '°' },
      control: { label: 'Corrective lamp angle', unit: '°', min: 0, max: 80, precision: 1 },
      tolerance: 2,
      start: 90,
    },
  },
  {
    slug: 'ecosystem-resilience',
    title: 'Ecosystem resilience',
    lab: 'ecosystem',
    formula: 'resilience = diversity + recovery',
    scenario: 'a burnt hillside being replanted after a wildfire season',
    crisis: 'The slope supports 68 units of established growth. The replanting density is wrong, so young trees are competing themselves to death.',
    insight: 'Recovery is not about planting the most. It is about planting what the damaged system can currently support.',
    resolution: 'At the solved density the replanting matches what the slope can carry and the canopy re-establishes.',
    model: {
      kind: 'carryingCapacity',
      params: { capacity: 68, leftName: 'Replanting density', rightName: 'Slope capacity', productUnit: 'units' },
      control: { label: 'Replanting density', unit: 'units', min: 0, max: 145, precision: 1 },
      tolerance: 3.6,
      start: 92,
    },
  },
  {
    slug: 'biodiversity',
    title: 'Biodiversity',
    lab: 'ecosystem',
    formula: 'stability \\propto biodiversity',
    scenario: 'a restored wetland being assessed for legal protection',
    crisis: 'The wetland can sustain 24 species at its current size. The recorded species count does not match, so the assessment fails.',
    insight: 'More species means more ways for a system to absorb a shock. Monocultures fail all at once.',
    resolution: 'At the solved species count the wetland sits exactly at its sustainable diversity.',
    model: {
      kind: 'carryingCapacity',
      params: { capacity: 24, leftName: 'Species present', rightName: 'Sustainable diversity', productUnit: 'species' },
      control: { label: 'Species present', unit: '', min: 0, max: 50, precision: 1 },
      tolerance: 1.25,
      start: 8,
    },
  },
  {
    slug: 'human-digestion',
    title: 'Human digestion',
    lab: 'osmosis',
    formula: 'absorbed = 0.62 \\times intake',
    scenario: 'a nutrition plan for a recovery ward',
    crisis: 'Patients must absorb 27.9 units of nutrient. Only 62% of intake is absorbed, and the prescribed intake is wrong.',
    insight: 'Eating is not absorbing. A large fraction of intake passes through without ever entering the bloodstream.',
    resolution: 'At the solved intake patients absorb exactly the 27.9 units the plan requires.',
    model: {
      kind: 'proportional',
      params: { k: 0.62, targetY: 27.9, leftName: 'Nutrient absorbed', rightName: 'Nutrient required', productUnit: 'units' },
      control: { label: 'Daily intake', unit: 'units', min: 0, max: 95, precision: 2 },
      tolerance: 1.5,
      start: 8,
    },
  },
  {
    slug: 'homeostasis',
    title: 'Homeostasis',
    lab: 'cell',
    formula: '\\Delta_{internal} \\approx 0',
    scenario: 'a neonatal incubator drifting out of its safe band',
    crisis: 'The infant must be held at 37.0 °C core temperature. The incubator setpoint is wrong and the readout keeps climbing.',
    insight: 'Homeostasis is active work, not stillness. The body spends energy constantly to hold conditions steady.',
    resolution: 'At the solved setpoint the core temperature holds at 37.0 °C without correction.',
    model: {
      kind: 'fluxBalance',
      params: { outside: 37, leftName: 'Incubator setpoint', rightName: 'Target core temperature', productUnit: '°C' },
      control: { label: 'Incubator setpoint', unit: '°C', min: 33, max: 41, precision: 2 },
      tolerance: 0.2,
      start: 92,
    },
  },
];

export default biology;
