/** Chemistry missions. See physics.js for the shape of an entry. */

const chemistry = [
  {
    slug: 'particle-motion',
    chapterId: 'chemistry.matter-particle',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Particle motion',
    lab: 'particle',
    formula: 'KE = \\tfrac{3}{2}k_BT',
    scenario: 'a sealed sample chamber on a high-altitude balloon',
    crisis: 'Nothing registers on the detector. It only triggers when particles carry 6.21 zJ of average kinetic energy, and the chamber temperature is set too low.',
    insight: 'Temperature is not a substance. It is a measure of how much kinetic energy the particles carry on average.',
    resolution: 'At the solved temperature the average particle energy hits 6.21 zJ and the detector triggers cleanly.',
    model: {
      kind: 'proportional',
      params: { k: 0.0207, targetY: 6.21, leftName: 'Average kinetic energy', rightName: 'Detector threshold', productUnit: 'zJ' },
      control: { label: 'Chamber temperature', unit: 'K', min: 100, max: 600, precision: 0 },
      tolerance: 0.25,
      start: 8,
    },
  },
  {
    slug: 'gas-compression',
    chapterId: 'chemistry.matter-particle',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Gas compression',
    lab: 'gas',
    formula: 'PV = nRT',
    scenario: 'a diving cylinder being refilled at a coastal station',
    crisis: 'The pressure gauge refuses to settle. 0.5 mol of gas sits at 300 K and one atmosphere, and the cylinder volume is set wrong.',
    insight: 'Squeeze a gas into less space and the same particles hit the walls more often. Pressure and volume trade against each other.',
    resolution: 'At the solved volume the gas law closes and the gauge holds steady at one atmosphere.',
    model: {
      kind: 'idealGas',
      params: { moles: 0.5, temperature: 300, pressure: 101325, leftName: 'Pressure × volume', rightName: 'nRT', productUnit: 'J' },
      control: { label: 'Cylinder volume', unit: 'm³', min: 0.002, max: 0.03, precision: 4 },
      tolerance: 70,
      start: 88,
    },
  },
  {
    slug: 'phase-changes',
    chapterId: 'chemistry.matter-particle',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Phase changes',
    lab: 'thermal',
    formula: 'Q = mL_v',
    scenario: 'a solar still producing drinking water on a stranded boat',
    crisis: 'The batch will not boil dry. The still can supply 904 kJ per cycle, water needs 2260 kJ per kilogram, and the batch size is wrong.',
    insight: 'Boiling costs enormous energy without raising the temperature at all. Every joule goes into tearing molecules apart.',
    resolution: 'At the solved batch mass the available energy vaporises the whole batch exactly.',
    model: {
      kind: 'proportional',
      params: { k: 2260000, targetY: 904000, leftName: 'Energy required', rightName: 'Energy available', productUnit: 'J' },
      control: { label: 'Batch mass', unit: 'kg', min: 0, max: 1.2, precision: 3 },
      tolerance: 60000,
      start: 88,
    },
  },
  {
    slug: 'thermal-expansion',
    chapterId: 'chemistry.matter-particle',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Thermal expansion',
    lab: 'thermal',
    formula: '\\Delta L = \\alpha L_0 \\Delta T',
    scenario: 'a 25 m steel footbridge installed on a hot afternoon',
    crisis: 'The joint will be torn apart by the first hot spell. It allows exactly 12 mm of growth, steel expands 12 millionths of its length per kelvin, and the assumed temperature swing is wrong.',
    insight: 'Solids grow when heated. Bridges, rails and pipes are all built with deliberate gaps because of it.',
    resolution: 'At the solved temperature swing the span grows exactly 12 mm and the joint absorbs it.',
    model: {
      kind: 'proportional',
      params: { k: 0.0003, targetY: 0.012, leftName: 'Predicted growth', rightName: 'Joint allowance', productUnit: 'm' },
      control: { label: 'Temperature swing', unit: 'K', min: 0, max: 100, precision: 1 },
      tolerance: 0.0007,
      start: 90,
    },
  },
  {
    slug: 'atomic-structure',
    chapterId: 'chemistry.atomic-structure',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Atomic structure',
    lab: 'atom',
    formula: 'A = Z + N',
    scenario: 'an isotope scanner checking a shipment of shielding plate',
    crisis: 'The scanner is flagging the plate as counterfeit. It should be iron-56 — 26 protons, mass number 56 — and the neutron count on the readout is wrong.',
    insight: 'Protons decide which element you have. Neutrons decide which version of it. Both together give the mass number.',
    resolution: 'At the solved neutron count the numbers add to 56 and the scanner clears the shipment.',
    model: {
      kind: 'sumToConstant',
      params: { known: 26, total: 56, leftName: 'Protons + neutrons', rightName: 'Mass number', productUnit: 'nucleons' },
      control: { label: 'Neutron count', unit: '', min: 0, max: 60, precision: 0 },
      tolerance: 1.5,
      start: 90,
    },
  },
  {
    slug: 'electron-shells',
    chapterId: 'chemistry.atomic-structure',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Electron shells',
    lab: 'atom',
    formula: 'E_n = -\\frac{13.6}{n^2}\\ \\mathrm{eV}',
    scenario: 'a spectrometer identifying gas in a sealed vault',
    crisis: 'The gas has come back unidentified. Its emission line places an electron at 0.85 eV of binding energy, and the assumed shell number is wrong.',
    insight: 'Electrons only sit at fixed energy levels. The further out the shell, the weaker the grip and the smaller the energy.',
    resolution: 'At the solved shell number the binding energy matches the observed line exactly.',
    model: {
      kind: 'inverseSquare',
      params: { constant: 13.6, targetForce: 0.85, leftName: 'Shell binding energy', rightName: 'Observed line', productUnit: 'eV' },
      control: { label: 'Shell number', unit: 'n', min: 1, max: 8, precision: 2 },
      tolerance: 0.06,
      start: 10,
    },
  },
  {
    slug: 'valence-electrons',
    chapterId: 'chemistry.atomic-structure',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Valence electrons',
    lab: 'atom',
    formula: 'v = Z - e_{core}',
    scenario: 'a materials lab predicting how a salt will bond',
    crisis: 'The bonding prediction keeps failing. The sample is chlorine — 17 electrons total, 10 locked in inner shells — and the outer-shell count is wrong.',
    insight: 'Only the outermost electrons take part in bonding. Everything underneath is spectator.',
    resolution: 'At the solved valence count the model predicts the correct bonding behaviour.',
    model: {
      kind: 'sumToConstant',
      params: { known: 10, total: 17, leftName: 'Core + valence', rightName: 'Total electrons', productUnit: 'e⁻' },
      control: { label: 'Valence electrons', unit: 'e⁻', min: 0, max: 14, precision: 0 },
      tolerance: 0.4,
      start: 92,
    },
  },
  {
    slug: 'ionic-bonding',
    chapterId: 'chemistry.atomic-structure',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Ionic bonding',
    lab: 'bond',
    formula: '\\sum q_{+} + \\sum q_{-} = 0',
    scenario: 'a de-icing compound being mixed for an airfield',
    crisis: 'The compound will not crystallise. Each magnesium ion carries a 2+ charge, chloride ions carry 1- each, and the ratio in the mix is wrong.',
    insight: 'Ionic compounds must come out electrically neutral. The ratio of ions is forced by their charges.',
    resolution: 'At the solved chloride count the charges cancel exactly and the crystal forms.',
    model: {
      kind: 'ratioMatch',
      params: { a: 1, b: 2, c: 1, leftName: 'Negative charge', rightName: 'Positive charge', productUnit: 'e' },
      control: { label: 'Chloride ions per magnesium', unit: '', min: 0, max: 6, precision: 2 },
      tolerance: 0.2,
      start: 90,
    },
  },
  {
    slug: 'covalent-bonding',
    chapterId: 'chemistry.atomic-structure',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Covalent bonding',
    lab: 'bond',
    formula: 'E_{total} = n E_{bond}',
    scenario: 'a fuel analysis rig measuring what a hydrocarbon releases',
    crisis: 'The bond count in the model cannot be right. Breaking the sample apart takes 1392 kJ/mol, and each carbon-carbon bond costs 348 kJ/mol.',
    insight: 'Covalent bonds are shared electrons, and each one takes a fixed amount of energy to break.',
    resolution: 'At the solved bond count the energy books balance at 1392 kJ/mol.',
    model: {
      kind: 'proportional',
      params: { k: 348, targetY: 1392, leftName: 'Energy to break', rightName: 'Measured energy', productUnit: 'kJ/mol' },
      control: { label: 'Carbon-carbon bonds', unit: '', min: 0, max: 10, precision: 2 },
      tolerance: 90,
      start: 88,
    },
  },
  {
    slug: 'chemical-equations',
    chapterId: 'chemistry.chemical-reactions',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Chemical equations',
    lab: 'reaction',
    formula: '2H_2 + O_2 \\rightarrow 2H_2O',
    scenario: 'a fuel cell being commissioned for a remote clinic',
    crisis: 'The cell will not start because atoms are going unaccounted for. The oxygen side supplies enough for 4 hydrogen atoms, and the hydrogen coefficient is wrong.',
    insight: 'Atoms are never created or destroyed in a reaction. Whatever goes in on the left must come out on the right.',
    resolution: 'At the solved coefficient every hydrogen atom is accounted for and the equation balances.',
    model: {
      kind: 'ratioMatch',
      params: { a: 2, b: 4, c: 1, leftName: 'Hydrogen atoms supplied', rightName: 'Hydrogen atoms needed', productUnit: 'atoms' },
      control: { label: 'H₂ coefficient', unit: '', min: 0, max: 8, precision: 2 },
      tolerance: 0.3,
      start: 88,
    },
  },
  {
    slug: 'conservation-of-mass',
    chapterId: 'chemistry.chemical-reactions',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Conservation of mass',
    lab: 'reaction',
    formula: 'm_{reactants} = m_{products}',
    scenario: 'a school lab that appears to have lost mass mid-reaction',
    crisis: 'Mass appears to have gone missing. 100 g of reactants went in, only 44 g of carbon dioxide was captured, and the remaining product mass is logged wrong.',
    insight: 'Reactions never lose mass. If the scale disagrees, something escaped as gas and was not measured.',
    resolution: 'At the solved product mass the totals match at 100 g and the apparent loss disappears.',
    model: {
      kind: 'sumToConstant',
      params: { known: 44, total: 100, leftName: 'Products measured', rightName: 'Reactants in', productUnit: 'g' },
      control: { label: 'Remaining product mass', unit: 'g', min: 0, max: 120, precision: 1 },
      tolerance: 3,
      start: 8,
    },
  },
  {
    slug: 'acid-base-balance',
    chapterId: 'chemistry.acids-bases',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Acid-base balance',
    lab: 'ph',
    formula: 'pH = -\\log_{10}[H^+]',
    scenario: 'a fish hatchery whose tanks have turned acidic overnight',
    crisis: 'The fry are dying. They survive at pH 6.0, the hydrogen ion concentration is far from that, and the buffer dose is set wrong.',
    insight: 'pH is a logarithm. Dropping one pH unit means ten times more hydrogen ions, not a little more.',
    resolution: 'At the solved concentration the tank reads pH 6.0 and the fry stabilise.',
    model: {
      kind: 'logAcidity',
      params: { targetPH: 6, leftName: 'Measured pH', rightName: 'Target pH', productUnit: 'pH' },
      control: { label: 'Hydrogen ion concentration', unit: 'µmol/L', min: 0.05, max: 4, precision: 3 },
      tolerance: 0.05,
      start: 88,
    },
  },
  {
    slug: 'ph-calibration',
    chapterId: 'chemistry.acids-bases',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'pH calibration',
    lab: 'ph',
    formula: 'pH = -\\log_{10}[H^+]',
    scenario: 'a soil probe being calibrated before a planting survey',
    crisis: 'The probe cannot be trusted until it agrees with the reference. That buffer is certified at pH 4.5, and the probe is reporting a concentration that does not correspond to it.',
    insight: 'A meter is only as trustworthy as its calibration. Match it against a known standard before you trust any field reading.',
    resolution: 'At the solved concentration the probe reads exactly 4.5 and the survey can begin.',
    model: {
      kind: 'logAcidity',
      params: { targetPH: 4.5, leftName: 'Probe pH', rightName: 'Buffer standard', productUnit: 'pH' },
      control: { label: 'Hydrogen ion concentration', unit: 'µmol/L', min: 2, max: 90, precision: 2 },
      tolerance: 0.03,
      start: 88,
    },
  },
  {
    slug: 'solute-saturation',
    chapterId: 'chemistry.mixtures-solutions',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Solute saturation',
    lab: 'solution',
    formula: 'S = \\frac{m_{solute}}{m_{solution}}',
    scenario: 'a brine tank feeding an ice-road de-icing rig',
    crisis: 'The rig is running on the wrong brine. It needs a solution that is 36% salt by mass, the batch holds 250 g of solution, and the salt mass is wrong.',
    insight: 'Concentration is a ratio, not an amount. The same mass of salt is strong in a cup and weak in a bucket.',
    resolution: 'At the solved salt mass the batch sits at exactly 36% and the rig sprays correctly.',
    model: {
      kind: 'proportional',
      params: { k: 0.004, targetY: 0.36, leftName: 'Mass fraction', rightName: 'Required fraction', productUnit: '' },
      control: { label: 'Salt mass', unit: 'g', min: 0, max: 200, precision: 1 },
      tolerance: 0.02,
      start: 8,
    },
  },
  {
    slug: 'solution-concentration',
    chapterId: 'chemistry.mixtures-solutions',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Solution concentration',
    lab: 'solution',
    formula: 'C = \\frac{n}{V}',
    scenario: 'a pharmacy diluting a stock solution for a paediatric dose',
    crisis: 'The dose as made up would be unsafe. 0.6 mol of active compound must end up at 0.25 mol/L, and the final volume is set wrong.',
    insight: 'Diluting does not remove anything. The same amount of substance is simply spread through more liquid.',
    resolution: 'At the solved final volume the concentration lands exactly on 0.25 mol/L.',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 0.6, leftB: 1, rightA: 0.25, leftName: 'Moles present', rightName: 'Concentration × volume', productUnit: 'mol' },
      control: { label: 'Final volume', unit: 'L', min: 0.5, max: 5, precision: 2 },
      tolerance: 0.03,
      start: 88,
    },
  },
  {
    slug: 'reaction-rates',
    chapterId: 'chemistry.rates-energetics',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Reaction rates',
    lab: 'reaction',
    formula: 'rate = \\frac{\\Delta[P]}{\\Delta t}',
    scenario: 'a chemical hand-warmer being timed before a mountain expedition',
    crisis: 'The schedule is built on the wrong duration. The reaction produces 0.045 mol/L of product at 0.0025 mol/L per second.',
    insight: 'Rate connects amount and time. Knowing any two of the three tells you the third.',
    resolution: 'At the solved duration the product yield matches exactly what the reaction delivers.',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 0.045, leftB: 1, rightA: 0.0025, leftName: 'Product formed', rightName: 'Rate × time', productUnit: 'mol/L' },
      control: { label: 'Reaction duration', unit: 's', min: 2, max: 40, precision: 1 },
      tolerance: 0.0022,
      start: 88,
    },
  },
  {
    slug: 'catalyst-pathways',
    chapterId: 'chemistry.rates-energetics',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Catalyst pathways',
    lab: 'reaction',
    formula: 'E_{a,cat} = E_a - \\Delta E',
    scenario: 'an exhaust converter that stopped working in cold weather',
    crisis: 'The converter cannot get the reaction over its barrier. Uncatalysed it needs 75 kJ/mol, the converter supplies only 52 kJ/mol, and the catalyst’s contribution is set wrong.',
    insight: 'A catalyst does not push the reaction. It opens a cheaper route with a lower barrier, and is unchanged at the end.',
    resolution: 'At the solved reduction the barrier drops to 52 kJ/mol and the converter lights off.',
    model: {
      kind: 'sumToConstant',
      params: { known: 52, total: 75, leftName: 'Barrier accounted', rightName: 'Uncatalysed barrier', productUnit: 'kJ/mol' },
      control: { label: 'Catalyst reduction', unit: 'kJ/mol', min: 0, max: 60, precision: 1 },
      tolerance: 1.8,
      start: 88,
    },
  },
  {
    slug: 'oxidation',
    chapterId: 'chemistry.rates-energetics',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Oxidation',
    lab: 'redox',
    formula: '\\mathrm{Ox}: e^- \\text{ lost}',
    scenario: 'a hull inspection finding rust below the waterline',
    crisis: 'The corrosion model will not close. It needs 6 electrons released per formula unit, and every iron atom that oxidises gives up 3 of them.',
    insight: 'Oxidation is electron loss. Rust is iron slowly giving its electrons away to oxygen.',
    resolution: 'At the solved number of iron atoms the half-reaction balances and the corrosion rate can be predicted.',
    model: {
      kind: 'proportional',
      params: { k: 3, targetY: 6, leftName: 'Electrons lost', rightName: 'Electrons required', productUnit: 'e⁻' },
      control: { label: 'Iron atoms oxidised', unit: 'atoms', min: 0, max: 6, precision: 2 },
      tolerance: 0.13,
      start: 92,
    },
  },
  {
    slug: 'reduction',
    chapterId: 'chemistry.rates-energetics',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Reduction',
    lab: 'redox',
    formula: '\\mathrm{Red}: e^- \\text{ gained}',
    scenario: 'a silver recovery cell reclaiming metal from waste solution',
    crisis: 'The plating is patchy. Every electron lost on one side must be gained on the other, the cell needs 6 electrons, and each copper atom that dissolves releases 2.',
    insight: 'Reduction and oxidation always happen together. Electrons do not vanish — they move.',
    resolution: 'At the solved number of copper atoms both half-reactions match and silver plates out cleanly.',
    model: {
      kind: 'proportional',
      params: { k: 2, targetY: 6, leftName: 'Electrons gained', rightName: 'Electrons available', productUnit: 'e⁻' },
      control: { label: 'Copper atoms dissolved', unit: 'atoms', min: 0, max: 8, precision: 2 },
      tolerance: 0.18,
      start: 90,
    },
  },
  {
    slug: 'periodic-patterns',
    chapterId: 'chemistry.atomic-structure',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Periodic patterns',
    lab: 'atom',
    formula: 'Z_{eff} = Z - S',
    scenario: 'a trends worksheet that keeps predicting the wrong atomic radius',
    crisis: 'The model predicts the wrong pull on sulfur’s outer electrons. It has 16 protons, they feel an effective pull of 6.1, and the shielding value is wrong.',
    insight: 'Inner electrons shield the outer ones from the nucleus. That shielding is why atoms get bigger down a group.',
    resolution: 'At the solved shielding value the effective charge lands on 6.1 and the radius prediction works.',
    model: {
      kind: 'sumToConstant',
      params: { known: 6.1, total: 16, leftName: 'Effective + shielding', rightName: 'Nuclear charge', productUnit: 'e' },
      control: { label: 'Shielding constant', unit: '', min: 0, max: 20, precision: 2 },
      tolerance: 0.6,
      start: 8,
    },
  },
  {
    slug: 'density-layers',
    chapterId: 'chemistry.mixtures-solutions',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Density layers',
    lab: 'solution',
    formula: '\\rho = \\frac{m}{V}',
    scenario: 'an oil spill response team predicting where a slick will sit',
    crisis: 'The sample will not float on seawater. It weighs 240 g and must have a density of 0.8 g/mL, and the measured volume is wrong.',
    insight: 'Density decides what floats. It is not about being heavy — it is about mass packed into a given space.',
    resolution: 'At the solved volume the density lands on 0.8 g/mL and the slick behaviour can be predicted.',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 240, leftB: 1, rightA: 0.8, leftName: 'Sample mass', rightName: 'Density × volume', productUnit: 'g' },
      control: { label: 'Sample volume', unit: 'mL', min: 50, max: 600, precision: 1 },
      tolerance: 14,
      start: 8,
    },
  },
  {
    slug: 'separation-methods',
    chapterId: 'chemistry.mixtures-solutions',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Separation methods',
    lab: 'chromatography',
    formula: 'R_f = \\frac{d_{solute}}{d_{solvent}}',
    scenario: 'a forensic lab matching ink from a disputed document',
    crisis: 'The logged distance does not identify the dye. The reference has an R_f of 0.42, and the solvent front travelled 8.5 cm.',
    insight: 'R_f is a ratio, so it stays the same whatever size the paper is. That is what makes it a usable fingerprint.',
    resolution: 'At the solved solute distance the R_f lands on 0.42 and the ink is identified.',
    model: {
      kind: 'ratioMatch',
      params: { a: 1, b: 0.42, c: 8.5, leftName: 'Solute distance', rightName: 'R_f × solvent front', productUnit: 'cm' },
      control: { label: 'Solute distance', unit: 'cm', min: 0, max: 9, precision: 2 },
      tolerance: 0.25,
      start: 90,
    },
  },
  {
    slug: 'molecular-polarity',
    chapterId: 'chemistry.atomic-structure',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Molecular polarity',
    lab: 'bond',
    formula: '\\mu = qr',
    scenario: 'a membrane filter that lets the wrong molecules through',
    crisis: 'The prediction is useless as it stands. The filter blocks anything with a dipole moment above 1.85 D, and the modelled charge separation is wrong.',
    insight: 'Polarity comes from charge separated across a distance. Shape matters as much as which atoms are present.',
    resolution: 'At the solved separation the dipole moment lands on 1.85 D and the filter model matches reality.',
    model: {
      kind: 'proportional',
      params: { k: 1.2, targetY: 1.85, leftName: 'Dipole moment', rightName: 'Filter threshold', productUnit: 'D' },
      control: { label: 'Charge separation', unit: 'Å', min: 0, max: 3.2, precision: 3 },
      tolerance: 0.11,
      start: 8,
    },
  },
  {
    slug: 'heat-of-reaction',
    chapterId: 'chemistry.rates-energetics',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Heat of reaction',
    lab: 'thermal',
    formula: '\\Delta H = \\frac{q}{n}',
    scenario: 'a calorimeter checking a new hand-warmer formula',
    crisis: 'The amount of reactant on the sheet cannot be right. The run released 57 kJ, and the formula is rated at 38 kJ per mole.',
    insight: 'Enthalpy change is energy per mole, not per run. Doubling the reactant doubles the heat, not the rating.',
    resolution: 'At the solved amount the released heat matches 57 kJ and the rating is confirmed.',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 57000, leftB: 1, rightA: 38000, leftName: 'Heat released', rightName: 'ΔH × moles', productUnit: 'J' },
      control: { label: 'Amount of reactant', unit: 'mol', min: 0.2, max: 3.2, precision: 3 },
      tolerance: 2600,
      start: 90,
    },
  },
  {
    slug: 'carbon-cycles',
    chapterId: 'chemistry.chemical-reactions',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Carbon cycles',
    lab: 'ecosystem',
    formula: 'C + O_2 \\rightarrow CO_2',
    scenario: 'a biochar kiln being tuned so it burns clean',
    crisis: 'The kiln smokes instead of burning fully. It feeds in 2.4 mol of carbon per cycle, and the oxygen supply is set wrong.',
    insight: 'Complete combustion needs one oxygen molecule per carbon atom. Starve it and you get soot and carbon monoxide.',
    resolution: 'At the solved oxygen supply every carbon atom finds a partner and the kiln burns clean.',
    model: {
      kind: 'ratioMatch',
      params: { a: 1, b: 1, c: 2.4, leftName: 'Oxygen supplied', rightName: 'Oxygen required', productUnit: 'mol' },
      control: { label: 'Oxygen supply', unit: 'mol', min: 0, max: 6, precision: 2 },
      tolerance: 0.16,
      start: 8,
    },
  },
  {
    slug: 'melting-ice',
    chapterId: 'chemistry.matter-particle',
    difficulty: 'Explorer',
    gradeGroup: 'high',
    gradeLevel: 9,
    title: 'Solid, liquid, gas',
    lab: 'particle',
    formula: 'Q = mL_f',
    scenario: 'a fish stall keeping its catch under crushed ice',
    crisis: 'Nobody has worked out how much ice the morning eats. Melting one kilogram soaks up 334 kJ, and the stall gains 1 002 kJ of heat across the morning.',
    insight: 'Melting takes energy without changing the temperature at all. The heat goes into breaking the solid apart, not into making it warmer.',
    resolution: 'At the solved mass, the ice absorbs exactly the heat the morning delivers.',
    standardIds: ['cbse:3:4', 'ngss:3-5-PS1-1'],
    model: {
      kind: 'proportional',
      params: { k: 334, targetY: 1002, leftName: 'Heat absorbed', rightName: 'Heat gained', productUnit: 'kJ' },
      control: { label: 'Ice melted', unit: 'kg', min: 0, max: 8, precision: 2 },
      tolerance: 95,
      start: 92,
    },
  },
  {
    slug: 'density-float',
    chapterId: 'chemistry.matter-particle',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 5,
    title: 'Density and floating',
    lab: 'gas',
    formula: '\\rho = \\frac{m}{V}',
    scenario: 'a river ferry being loaded to a painted safety line',
    crisis: 'The loading crew cannot agree how much of the hull goes under water. It displaces water at 1 000 kg per cubic metre, and the safe displacement is 4 500 kg.',
    insight: 'A floating object sinks until it pushes aside its own weight in water. Density links the mass you load to the volume you submerge.',
    resolution: 'At the solved submerged volume the ferry floats exactly on its safety line.',
    standardIds: ['cbse:5:5', 'igcse:1.4'],
    model: {
      kind: 'proportional',
      params: { k: 1000, targetY: 4500, leftName: 'Water displaced', rightName: 'Safe displacement', productUnit: 'kg' },
      control: { label: 'Submerged volume', unit: 'm³', min: 0, max: 10, precision: 2 },
      tolerance: 420,
      start: 92,
    },
  },
  {
    slug: 'gas-pressure-volume',
    chapterId: 'chemistry.matter-particle',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 9,
    title: 'Boyle\'s law',
    lab: 'gas',
    formula: 'P_1V_1 = P_2V_2',
    scenario: 'a diving cylinder being decanted into a smaller travel bottle',
    crisis: 'The travel bottle will be overfilled. It is rated to 80 bar, the store cylinder holds gas at 200 bar in 12 L, and the fill volume has been set wrong.',
    insight: 'Squeeze a fixed amount of gas into less space and its pressure rises in exact proportion. The product of pressure and volume does not move.',
    resolution: 'At the solved volume the decanted gas sits exactly at the bottle\'s 80 bar rating.',
    standardIds: ['cbse:9:1', 'icse:9:matter', 'igcse:1.4'],
    model: {
      kind: 'inverseProduct',
      params: { leftA: 200, leftB: 12, rightA: 80, leftName: 'Store cylinder PV', rightName: 'Travel bottle PV', productUnit: 'bar·L' },
      control: { label: 'Travel bottle volume', unit: 'L', min: 0, max: 60, precision: 1 },
      tolerance: 220,
      start: 92,
    },
  },
  {
    slug: 'valency-count',
    chapterId: 'chemistry.atomic-structure',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Valency and formulae',
    lab: 'bond',
    formula: 'n_1 v_1 = n_2 v_2',
    scenario: 'a fertiliser plant checking a batch formula before mixing',
    crisis: 'The compound on the batch sheet is left carrying a charge. Four aluminium ions each carry a charge of 3, and the oxide ions each carry 2.',
    insight: 'A compound is electrically neutral overall. The total positive charge has to be matched exactly by the total negative charge.',
    resolution: 'At the solved oxide count the batch formula balances to zero net charge.',
    standardIds: ['cbse:9:3', 'icse:8:chemical-bonding'],
    model: {
      // Four Al³⁺ (12+) against oxide at 2- each solves to 6 ions: Al₄O₆, two
      // formula units of Al₂O₃, which is what a batch sheet would carry.
      //
      // Three Al³⁺ was the original and demands 4.5 oxide ions — a compound that
      // cannot exist. Two Al³⁺ fixes the chemistry but solves to 3, and 3 is the
      // aluminium charge printed in the crisis, so the answer could be read
      // straight off the page. Four is the smallest count that is both whole and
      // absent from the prose.
      kind: 'proportional',
      params: { k: 2, targetY: 12, leftName: 'Negative charge', rightName: 'Positive charge', productUnit: 'units' },
      control: { label: 'Oxide ions', unit: 'ions', min: 0, max: 10, precision: 0 },
      tolerance: 0.5,
      start: 92,
    },
  },
  {
    slug: 'balancing-equations',
    chapterId: 'chemistry.chemical-reactions',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 7,
    title: 'Balancing an equation',
    lab: 'reaction',
    formula: '\\text{CH}_4 + x\\,\\text{O}_2 \\rightarrow \\text{CO}_2 + 2\\text{H}_2\\text{O}',
    scenario: 'a burner rig being set for complete combustion',
    crisis: 'Carbon monoxide is coming out of the flue. Burning one methane molecule releases four oxygen atoms into the products, and the oxygen supply coefficient on the rig is wrong.',
    insight: 'Atoms are never created or destroyed in a reaction, only rearranged. Every atom on the left has to appear on the right.',
    resolution: 'At the solved coefficient every atom balances and the flue runs clean.',
    standardIds: ['cbse:7:6', 'icse:7:chemical-reactions'],
    model: {
      kind: 'proportional',
      params: { k: 2, targetY: 4, leftName: 'Oxygen atoms supplied', rightName: 'Oxygen atoms needed', productUnit: 'atoms' },
      control: { label: 'Oxygen molecules', unit: 'O₂', min: 0, max: 6, precision: 1 },
      tolerance: 0.45,
      start: 92,
    },
  },
  {
    slug: 'mass-conservation',
    chapterId: 'chemistry.chemical-reactions',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 5,
    title: 'Mass is conserved',
    lab: 'reaction',
    formula: 'm_{\\text{reactants}} = m_{\\text{products}}',
    scenario: 'a sealed flask on a balance during a fizzing reaction',
    crisis: 'The class thinks mass has vanished. The flask starts at 84 g of reactants, one product weighs in at 36 g, and the second has not been weighed.',
    insight: 'A sealed reaction cannot gain or lose mass. Anything that seems to disappear has turned into something still inside the flask.',
    resolution: 'At the solved mass the products account for every gram that went in.',
    standardIds: ['cbse:5:6', 'ngss:3-5-PS1-2'],
    model: {
      kind: 'sumToConstant',
      params: { known: 36, total: 84, leftName: 'Product mass', rightName: 'Reactant mass', productUnit: 'g' },
      control: { label: 'Second product mass', unit: 'g', min: 0, max: 80, precision: 1 },
      tolerance: 2.2,
      start: 8,
    },
  },
  {
    slug: 'neutralising-soil',
    chapterId: 'chemistry.acids-bases',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 5,
    title: 'Neutralising acid soil',
    lab: 'reaction',
    formula: '\\text{acid} + \\text{base} \\rightarrow \\text{salt} + \\text{water}',
    scenario: 'a tea estate liming a plot that has turned too acidic',
    crisis: 'The crop is suffering. The plot carries 96 acid units, the lime being spread neutralises 12 units per sack, and the order placed is short.',
    insight: 'A base cancels an acid unit for unit. Neutralising is not about making soil alkaline, only about reaching the middle.',
    resolution: 'At the solved number of sacks the plot lands exactly at neutral.',
    standardIds: ['cbse:7:5', 'ngss:3-5-PS1-2'],
    model: {
      kind: 'proportional',
      params: { k: 12, targetY: 96, leftName: 'Acid neutralised', rightName: 'Acid present', productUnit: 'units' },
      control: { label: 'Lime sacks', unit: 'sacks', min: 0, max: 16, precision: 0 },
      tolerance: 9,
      start: 92,
    },
  },
  {
    slug: 'titration-endpoint',
    chapterId: 'chemistry.acids-bases',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Titration endpoint',
    lab: 'ph',
    formula: 'M_1V_1 = M_2V_2',
    scenario: 'a water board titrating a sample against standard alkali',
    crisis: 'The colour change is overshot every time. The acid sample is 0.15 M in 25 mL, and the alkali in the burette is 0.10 M.',
    insight: 'At the endpoint the moles of acid and the moles of alkali are equal. Concentration times volume gives moles on both sides.',
    resolution: 'At the solved burette volume the indicator turns exactly at the endpoint.',
    standardIds: ['cbse:10:2', 'icse:10:analytical-chemistry', 'igcse:6.2'],
    model: {
      kind: 'inverseProduct',
      params: { leftA: 0.15, leftB: 25, rightA: 0.1, leftName: 'Acid moles', rightName: 'Alkali moles', productUnit: 'mmol' },
      control: { label: 'Alkali volume', unit: 'mL', min: 0, max: 70, precision: 1 },
      tolerance: 0.35,
      start: 8,
    },
  },
  {
    slug: 'dissolving-sugar',
    chapterId: 'chemistry.mixtures-solutions',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 4,
    title: 'Dissolving and saturation',
    lab: 'particle',
    formula: 'c = \\frac{m}{V}',
    scenario: 'a sweet shop mixing syrup to a fixed recipe',
    crisis: 'This morning’s batch went out visibly thin. The recipe calls for 400 g of sugar in every litre, and the pan holds 2.5 L.',
    insight: 'Concentration is how much solute sits in each unit of solvent. Doubling the water without doubling the sugar halves the strength.',
    resolution: 'At the solved sugar mass the pan matches the recipe exactly.',
    standardIds: ['cbse:4:5', 'uk:KS2:materials'],
    model: {
      kind: 'proportional',
      // The pan holds 2.5 L, so grams of sugar divided by 2.5 is the strength in
      // g/L; k is that 1/2.5. Both sides are concentrations, and the recipe's
      // 400 g/L is what the learner has to reach — 1000 g of sugar.
      params: { k: 0.4, targetY: 400, leftName: 'Strength in the pan', rightName: 'Recipe strength', productUnit: 'g/L' },
      control: { label: 'Sugar added', unit: 'g', min: 0, max: 2000, precision: 0 },
      tolerance: 10,
      start: 92,
    },
  },
  {
    slug: 'filtration-recovery',
    chapterId: 'chemistry.mixtures-solutions',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 5,
    title: 'Separating a mixture',
    lab: 'chromatography',
    formula: 'm_{\\text{total}} = m_{\\text{residue}} + m_{\\text{filtrate}}',
    scenario: 'a salt pan separating grit from the day\'s harvest',
    crisis: 'The day’s books do not close. The raw scrape comes to 62 kg, the grit caught on the sieve weighs 17 kg, and the clean salt has not been weighed.',
    insight: 'Filtering sorts a mixture without changing what is in it. What went in has to come out, split across the two piles.',
    resolution: 'At the solved mass the two piles account for the whole scrape.',
    standardIds: ['cbse:5:4', 'uk:KS2:materials'],
    model: {
      kind: 'sumToConstant',
      params: { known: 17, total: 62, leftName: 'Mass accounted for', rightName: 'Raw scrape', productUnit: 'kg' },
      control: { label: 'Clean salt', unit: 'kg', min: 0, max: 70, precision: 1 },
      tolerance: 1.8,
      start: 8,
    },
  },
  {
    slug: 'dilution-factor',
    chapterId: 'chemistry.mixtures-solutions',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 9,
    title: 'Diluting a stock',
    lab: 'solution',
    formula: 'M_1V_1 = M_2V_2',
    scenario: 'a hospital pharmacy stepping a stock solution down to a dose strength',
    crisis: 'The ward’s bag is being made up wrong. It has to finish at 0.4 M, the stock is 2.4 M, and only 30 mL of it may be used.',
    insight: 'Diluting adds solvent but no solute, so the moles present never change. Volume rises exactly as concentration falls.',
    resolution: 'At the solved final volume the bag sits exactly at the prescribed 0.4 M.',
    standardIds: ['cbse:9:2', 'igcse:6.1'],
    model: {
      kind: 'inverseProduct',
      params: { leftA: 2.4, leftB: 30, rightA: 0.4, leftName: 'Stock moles', rightName: 'Diluted moles', productUnit: 'mmol' },
      control: { label: 'Final volume', unit: 'mL', min: 0, max: 400, precision: 0 },
      tolerance: 6.5,
      start: 92,
    },
  },
  {
    slug: 'reaction-rate-surface',
    chapterId: 'chemistry.rates-energetics',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Surface area and rate',
    lab: 'reaction',
    formula: 'r \\propto A',
    scenario: 'a limestone kiln deciding how finely to crush its feedstock',
    crisis: 'The line is running short of feed. The kiln must hit 21 g/s, each square metre of exposed surface reacts at 0.6 g/s, and the crush setting gives far too little surface.',
    insight: 'A reaction happens where the surfaces meet. Crushing a solid does not change its mass but multiplies the area available.',
    resolution: 'At the solved surface area the kiln reaches exactly its required rate.',
    standardIds: ['cbse:8:6', 'igcse:7.1'],
    model: {
      kind: 'proportional',
      params: { k: 0.6, targetY: 21, leftName: 'Rate achieved', rightName: 'Rate required', productUnit: 'g/s' },
      control: { label: 'Exposed surface', unit: 'm²', min: 0, max: 70, precision: 1 },
      tolerance: 2,
      start: 92,
    },
  },
  {
    slug: 'electrolysis-charge',
    chapterId: 'chemistry.rates-energetics',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Charge in electrolysis',
    lab: 'redox',
    formula: 'Q = It',
    scenario: 'an electroplating bath depositing a fixed mass of nickel',
    crisis: 'The plating is patchy because the timer was set on a guess. The rectifier is locked at 6 A, and the job needs 10 800 C through the cell.',
    insight: 'The mass deposited depends on the total charge passed, which is current multiplied by time. A weaker current simply needs longer.',
    resolution: 'At the solved time the bath passes exactly the charge the job requires.',
    standardIds: ['cbse:10:3', 'icse:10:electrolysis'],
    model: {
      kind: 'proportional',
      params: { k: 6, targetY: 10800, leftName: 'Charge passed', rightName: 'Charge required', productUnit: 'C' },
      control: { label: 'Plating time', unit: 's', min: 0, max: 3600, precision: 0 },
      tolerance: 1000,
      start: 92,
    },
  },
  {
    slug: 'sorting-materials',
    chapterId: 'chemistry.matter-particle',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 1,
    title: 'Grouping materials',
    lab: 'particle',
    formula: 'n_{\\text{total}} = n_a + n_b',
    scenario: 'an infant class sorting a tray of objects into metal and not-metal',
    crisis: 'The tray does not tally. It holds eighteen objects, eleven have been put in the metal pile, and the other pile has not been counted.',
    insight: 'Sorting splits a group without changing how many there are. The two piles together always rebuild the original.',
    resolution: 'At the solved count the two piles account for the whole tray.',
    standardIds: ['cbse:1:4', 'ngss:K-2-PS1-1'],
    model: {
      kind: 'sumToConstant',
      params: { known: 11, total: 18, leftName: 'Objects accounted for', rightName: 'Objects on the tray', productUnit: 'objects' },
      control: { label: 'Not-metal pile', unit: 'objects', min: 0, max: 18, precision: 0 },
      tolerance: 0.7,
      start: 92,
    },
  },
  {
    slug: 'evaporating-salt',
    chapterId: 'chemistry.mixtures-solutions',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 3,
    title: 'Evaporating to dryness',
    lab: 'chromatography',
    formula: 'm_{\\text{solution}} = m_{\\text{salt}} + m_{\\text{water}}',
    scenario: 'a coastal school evaporating seawater on a windowsill',
    crisis: 'The salt left in the dish has not been weighed. It started as 240 g of seawater, and 232 g of that left as vapour over the week.',
    insight: 'Evaporation removes only the water. Everything dissolved in it stays behind, which is how salt pans have always worked.',
    resolution: 'At the solved mass the salt and the vapour account for the whole dish.',
    standardIds: ['cbse:3:4', 'uk:KS2:materials'],
    model: {
      kind: 'sumToConstant',
      params: { known: 232, total: 240, leftName: 'Mass accounted for', rightName: 'Starting mass', productUnit: 'g' },
      control: { label: 'Salt recovered', unit: 'g', min: 0, max: 24, precision: 1 },
      tolerance: 0.75,
      start: 92,
    },
  },
  {
    slug: 'molar-mass-count',
    chapterId: 'chemistry.atomic-structure',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Moles and mass',
    lab: 'particle',
    formula: 'n = \\frac{m}{M}',
    scenario: 'a lab weighing out sodium chloride for a standard solution',
    crisis: 'The mass on the weighing boat is wrong. The protocol calls for 0.25 mol, and sodium chloride runs at 58.5 g per mole.',
    insight: 'A mole is a fixed count of particles, and molar mass converts that count into something a balance can read.',
    resolution: 'At the solved mass the boat holds exactly the 0.25 mol the protocol requires.',
    standardIds: ['cbse:9:3', 'icse:10:mole-concept', 'igcse:4.1'],
    model: {
      kind: 'proportional',
      params: { k: 0.017094017094017096, targetY: 0.25, leftName: 'Moles present', rightName: 'Moles required', productUnit: 'mol' },
      control: { label: 'Mass weighed', unit: 'g', min: 0, max: 40, precision: 2 },
      tolerance: 0.022,
      start: 92,
    },
  },
  {
    slug: 'rusting-rate',
    chapterId: 'chemistry.rates-energetics',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 7,
    title: 'Rusting and oxygen',
    lab: 'redox',
    formula: '4\\text{Fe} + 3\\text{O}_2 \\rightarrow 2\\text{Fe}_2\\text{O}_3',
    scenario: 'a bridge inspector estimating iron lost to a season of rust',
    crisis: 'The oxygen figure in the report cannot be right. Every mole consumed accounts for 74.5 g of iron converted, and the survey logs 596 g converted.',
    insight: 'Rusting is iron combining with oxygen in a fixed ratio. Knowing one side of that ratio fixes the other exactly.',
    resolution: 'At the solved oxygen figure the report matches the iron actually lost.',
    standardIds: ['cbse:8:6', 'icse:7:chemical-reactions'],
    model: {
      kind: 'proportional',
      params: { k: 74.5, targetY: 596, leftName: 'Iron converted', rightName: 'Survey figure', productUnit: 'g' },
      control: { label: 'Oxygen consumed', unit: 'mol', min: 0, max: 20, precision: 2 },
      tolerance: 55,
      start: 92,
    },
  },
  {
    slug: 'ph-scale-reading',
    chapterId: 'chemistry.acids-bases',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 9,
    title: 'The pH scale',
    lab: 'ph',
    formula: '\\text{pH} = -\\log_{10}[\\text{H}^+]',
    scenario: 'a brewery holding mash acidity inside a narrow window',
    crisis: 'The meter is reading well off. The mash must sit at pH 5.4, and the acid dose in micromoles per litre has not been worked out.',
    insight: 'The pH scale is logarithmic, so one step is a tenfold change in acidity. Small pH errors are large chemical ones.',
    resolution: 'At the solved dose the mash settles exactly on pH 5.4.',
    standardIds: ['cbse:10:2', 'igcse:8.2'],
    model: {
      kind: 'logAcidity',
      params: { targetPH: 5.4, leftName: 'Measured pH', rightName: 'Target pH', productUnit: 'pH' },
      control: { label: 'Acid dose', unit: 'µmol/L', min: 0, max: 9, precision: 2 },
      tolerance: 0.14,
      start: 92,
    },
  },
  {
    slug: 'exothermic-heat',
    chapterId: 'chemistry.rates-energetics',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Exothermic reactions',
    lab: 'thermal',
    formula: '\\Delta H < 0',
    scenario: 'a self-heating ration pack being specified for a relief agency',
    crisis: 'The pack is not warming its contents. It must deliver 33 600 J, the reagent releases 480 J per gram, and the charge loaded is the wrong mass.',
    insight: 'An exothermic reaction releases energy to its surroundings. The mass of reagent sets the total energy available.',
    resolution: 'At the solved reagent mass the pack delivers exactly the heat the meal needs.',
    standardIds: ['cbse:8:6', 'igcse:6.2'],
    model: {
      kind: 'proportional',
      params: { k: 480, targetY: 33600, leftName: 'Heat released', rightName: 'Heat required', productUnit: 'J' },
      control: { label: 'Reagent mass', unit: 'g', min: 0, max: 160, precision: 1 },
      tolerance: 3100,
      start: 92,
    },
  },
  {
    slug: 'catalyst-effect',
    chapterId: 'chemistry.chemical-reactions',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Catalysts and rate',
    lab: 'ecosystem',
    formula: 'r = kc',
    scenario: 'an effluent plant dosing a catalyst to clear a tank overnight',
    crisis: 'The tank is not clearing fast enough. It must run at 1.44 kg/h, each unit of catalyst delivers 0.18 kg/h of throughput, and the dose set on the pump is wrong.',
    insight: 'A catalyst speeds a reaction without being consumed by it. More catalyst means more sites for the reaction to happen on.',
    resolution: 'At the solved dose the tank clears at exactly the overnight rate.',
    standardIds: ['cbse:8:6', 'igcse:7.2'],
    model: {
      kind: 'proportional',
      params: { k: 0.18, targetY: 1.44, leftName: 'Throughput achieved', rightName: 'Throughput needed', productUnit: 'kg/h' },
      control: { label: 'Catalyst dose', unit: 'units', min: 0, max: 22, precision: 1 },
      tolerance: 0.13,
      start: 92,
    },
  },
  {
    slug: 'solubility-temperature',
    chapterId: 'chemistry.mixtures-solutions',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 5,
    title: 'Solubility and heat',
    lab: 'chromatography',
    formula: 's \\propto T',
    scenario: 'a jam kitchen dissolving sugar into fruit pulp',
    crisis: 'The pan is nowhere near hot enough. The recipe needs 154 g in solution, and the pulp dissolves 3.5 g of sugar for every degree above room temperature.',
    insight: 'Most solids dissolve better in hot liquid because the particles move faster and separate more readily.',
    resolution: 'At the solved temperature rise the pulp holds exactly the sugar the recipe calls for.',
    standardIds: ['cbse:5:4', 'uk:KS2:materials'],
    model: {
      kind: 'proportional',
      params: { k: 3.5, targetY: 154, leftName: 'Sugar dissolved', rightName: 'Sugar required', productUnit: 'g' },
      control: { label: 'Temperature rise', unit: '°C', min: 0, max: 90, precision: 1 },
      tolerance: 14,
      start: 92,
    },
  },
  /* Classes 2-3 and class 9 — see the note in lib/topics/physics.js. */
  {
    slug: 'melting-cubes',
    chapterId: 'chemistry.matter-particle',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 2,
    title: 'Ice on the tray',
    lab: 'particle',
    formula: 'n_1 + n_2 = n_{total}',
    scenario: 'a classroom melting experiment that needs a full tray to start',
    crisis: 'The experiment cannot start with a part-full tray. Four cubes have already gone in, and the tray takes 10 before the lesson can begin.',
    insight: 'Ice and water are the same stuff in two states. Warming does not make more water — it only lets the same particles move past each other.',
    resolution: 'At the solved number of cubes the tray is full and the melting can be timed.',
    standardIds: ['cbse:2:5', 'uk:KS1:materials'],
    model: {
      kind: 'sumToConstant',
      params: { known: 4, total: 10, leftName: 'Cubes on the tray', rightName: 'Tray holds', productUnit: 'cubes' },
      control: { label: 'Cubes added', unit: 'cubes', min: 0, max: 10, precision: 0 },
      tolerance: 0.4,
      start: 92,
    },
  },
  {
    slug: 'paint-mixing-jars',
    chapterId: 'chemistry.mixtures-solutions',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 3,
    title: 'Mixing to the same shade',
    lab: 'particle',
    formula: 'n \\times c = C',
    scenario: 'an art room mixing jars of poster paint to one agreed shade',
    crisis: 'The jars are coming out in different shades and the mural will look patchy. Each jar takes 3 spoons of pigment, and there are 21 spoons of pigment left in the tin.',
    insight: 'A mixture keeps its recipe whatever size the batch. Same pigment per jar means same shade in every jar.',
    resolution: 'At the solved number of jars every jar gets its full three spoons and the shade matches.',
    standardIds: ['cbse:3:1', 'uk:KS2:materials'],
    model: {
      kind: 'proportional',
      params: { k: 3, targetY: 21, leftName: 'Pigment used', rightName: 'Pigment available', productUnit: 'spoons' },
      control: { label: 'Jars mixed', unit: 'jars', min: 0, max: 12, precision: 0 },
      tolerance: 1.2,
      start: 92,
    },
  },
  {
    slug: 'salt-spoons',
    chapterId: 'chemistry.mixtures-solutions',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 3,
    title: 'Salting to the recipe',
    lab: 'ratio',
    formula: 'm = n \\times m_1',
    scenario: 'a school kitchen brining vegetables to a written recipe',
    crisis: 'The brine is coming out weak and the vegetables are spoiling. One level spoon carries 5 g of salt, and the recipe calls for 45 g in the pot.',
    insight: 'Counting spoons is a way of weighing without scales, but only if every spoon holds the same amount.',
    resolution: 'At the solved number of spoons the pot carries exactly the salt the recipe asks for.',
    standardIds: ['cbse:3:5', 'uk:KS2:materials'],
    model: {
      kind: 'proportional',
      params: { k: 5, targetY: 45, leftName: 'Salt added', rightName: 'Recipe calls for', productUnit: 'g' },
      control: { label: 'Spoons added', unit: 'spoons', min: 0, max: 15, precision: 0 },
      tolerance: 2,
      start: 92,
    },
  },
  {
    slug: 'mole-ratio-burn',
    chapterId: 'chemistry.chemical-reactions',
    difficulty: 'Explorer',
    gradeGroup: 'high',
    gradeLevel: 9,
    title: 'Fuel to oxygen ratio',
    lab: 'bond',
    formula: 'CH_4 + 2O_2 \\rightarrow CO_2 + 2H_2O',
    scenario: 'a boiler house setting the gas feed against a fixed oxygen supply',
    crisis: 'The burner is sooting up and the flue is running rich. Every mole of methane needs 2 moles of oxygen to burn clean, and the supply line delivers 10 moles of oxygen a cycle.',
    insight: 'A balanced equation is a recipe in fixed proportions. Feed more fuel than the oxygen can match and the extra burns incompletely.',
    resolution: 'At the solved methane feed every molecule finds the oxygen it needs and the flame burns clean.',
    standardIds: ['cbse:9:3', 'igcse:4.3'],
    model: {
      kind: 'proportional',
      params: { k: 2, targetY: 10, leftName: 'Oxygen demanded', rightName: 'Oxygen supplied', productUnit: 'mol' },
      control: { label: 'Methane fed', unit: 'mol', min: 0, max: 12, precision: 1 },
      tolerance: 0.4,
      start: 92,
    },
  },
  {
    slug: 'antacid-tablets',
    chapterId: 'chemistry.acids-bases',
    difficulty: 'Explorer',
    gradeGroup: 'high',
    gradeLevel: 9,
    title: 'Dosing an antacid',
    lab: 'reaction',
    formula: 'n_{base} = n_{acid}',
    scenario: 'a pharmacy technician checking a dose against a stomach acid load',
    crisis: 'The dose on the label is not settling the acid. Each tablet neutralises 8 units of acid, and the load being treated comes to 56 units.',
    insight: 'A base cancels an acid unit for unit, so the dose is fixed by the acid present, not by how bad the discomfort feels.',
    resolution: 'At the solved number of tablets the acid load is exactly neutralised.',
    standardIds: ['cbse:9:2', 'igcse:8.2'],
    model: {
      kind: 'proportional',
      params: { k: 8, targetY: 56, leftName: 'Acid neutralised', rightName: 'Acid load', productUnit: 'units' },
      control: { label: 'Tablets taken', unit: 'tablets', min: 0, max: 14, precision: 0 },
      tolerance: 3,
      start: 92,
    },
  },
];

export default chemistry;
