/** Chemistry missions. See physics.js for the shape of an entry. */

const chemistry = [
  {
    slug: 'particle-motion',
    title: 'Particle motion',
    lab: 'particle',
    formula: 'KE = \\tfrac{3}{2}k_BT',
    scenario: 'a sealed sample chamber on a high-altitude balloon',
    crisis: 'The detector only triggers when particles carry 6.21 zJ of average kinetic energy. The chamber temperature is set wrong and nothing registers.',
    insight: 'Temperature is not a substance. It is a measure of how much kinetic energy the particles carry on average.',
    resolution: 'At the solved temperature the average particle energy hits 6.21 zJ and the detector triggers cleanly.',
    model: {
      kind: 'proportional',
      params: { k: 0.0207, targetY: 6.21, leftName: 'Average kinetic energy', rightName: 'Detector threshold', productUnit: 'zJ' },
      control: { label: 'Chamber temperature', unit: 'K', min: 100, max: 600, precision: 0 },
      tolerance: 0.25,
      start: 8,
    },
  },
  {
    slug: 'gas-compression',
    title: 'Gas compression',
    lab: 'particle',
    formula: 'PV = nRT',
    scenario: 'a diving cylinder being refilled at a coastal station',
    crisis: '0.5 mol of gas sits at 300 K and one atmosphere. The cylinder volume is set wrong, so the pressure gauge refuses to settle.',
    insight: 'Squeeze a gas into less space and the same particles hit the walls more often. Pressure and volume trade against each other.',
    resolution: 'At the solved volume the gas law closes and the gauge holds steady at one atmosphere.',
    model: {
      kind: 'idealGas',
      params: { moles: 0.5, temperature: 300, pressure: 101325, leftName: 'Pressure × volume', rightName: 'nRT', productUnit: 'J' },
      control: { label: 'Cylinder volume', unit: 'm³', min: 0.002, max: 0.03, precision: 4 },
      tolerance: 70,
      start: 88,
    },
  },
  {
    slug: 'phase-changes',
    title: 'Phase changes',
    lab: 'reaction',
    formula: 'Q = mL_v',
    scenario: 'a solar still producing drinking water on a stranded boat',
    crisis: 'The still can supply 904 kJ per cycle. Water needs 2260 kJ per kilogram to boil away, and the batch size is wrong.',
    insight: 'Boiling costs enormous energy without raising the temperature at all. Every joule goes into tearing molecules apart.',
    resolution: 'At the solved batch mass the available energy vaporises the whole batch exactly.',
    model: {
      kind: 'proportional',
      params: { k: 2260000, targetY: 904000, leftName: 'Energy required', rightName: 'Energy available', productUnit: 'J' },
      control: { label: 'Batch mass', unit: 'kg', min: 0, max: 1.2, precision: 3 },
      tolerance: 60000,
      start: 88,
    },
  },
  {
    slug: 'thermal-expansion',
    title: 'Thermal expansion',
    lab: 'reaction',
    formula: '\\Delta L = \\alpha L_0 \\Delta T',
    scenario: 'a 25 m steel footbridge installed on a hot afternoon',
    crisis: 'The expansion joint allows exactly 12 mm of growth. Steel expands 12 millionths of its length per kelvin, and the assumed temperature swing is wrong.',
    insight: 'Solids grow when heated. Bridges, rails and pipes are all built with deliberate gaps because of it.',
    resolution: 'At the solved temperature swing the span grows exactly 12 mm and the joint absorbs it.',
    model: {
      kind: 'proportional',
      params: { k: 0.0003, targetY: 0.012, leftName: 'Predicted growth', rightName: 'Joint allowance', productUnit: 'm' },
      control: { label: 'Temperature swing', unit: 'K', min: 0, max: 100, precision: 1 },
      tolerance: 0.0007,
      start: 90,
    },
  },
  {
    slug: 'atomic-structure',
    title: 'Atomic structure',
    lab: 'atom',
    formula: 'A = Z + N',
    scenario: 'an isotope scanner checking a shipment of shielding plate',
    crisis: 'The plate should be iron-56: 26 protons, mass number 56. The neutron count on the readout is wrong, so the scanner flags it as counterfeit.',
    insight: 'Protons decide which element you have. Neutrons decide which version of it. Both together give the mass number.',
    resolution: 'At the solved neutron count the numbers add to 56 and the scanner clears the shipment.',
    model: {
      kind: 'sumToConstant',
      params: { known: 26, total: 56, leftName: 'Protons + neutrons', rightName: 'Mass number', productUnit: 'nucleons' },
      control: { label: 'Neutron count', unit: '', min: 0, max: 60, precision: 0 },
      tolerance: 1.5,
      start: 90,
    },
  },
  {
    slug: 'electron-shells',
    title: 'Electron shells',
    lab: 'atom',
    formula: 'E_n = -\\frac{13.6}{n^2}\\ \\mathrm{eV}',
    scenario: 'a spectrometer identifying gas in a sealed vault',
    crisis: 'The emission line places an electron at 0.85 eV of binding energy. The assumed shell number is wrong, so the gas comes back unidentified.',
    insight: 'Electrons only sit at fixed energy levels. The further out the shell, the weaker the grip and the smaller the energy.',
    resolution: 'At the solved shell number the binding energy matches the observed line exactly.',
    model: {
      kind: 'inverseSquare',
      params: { constant: 13.6, targetForce: 0.85, leftName: 'Shell binding energy', rightName: 'Observed line', productUnit: 'eV' },
      control: { label: 'Shell number', unit: 'n', min: 1, max: 8, precision: 2 },
      tolerance: 0.06,
      start: 10,
    },
  },
  {
    slug: 'valence-electrons',
    title: 'Valence electrons',
    lab: 'atom',
    formula: 'v = Z - e_{core}',
    scenario: 'a materials lab predicting how a salt will bond',
    crisis: 'The sample is chlorine: 17 electrons total, 10 locked in inner shells. The outer-shell count is wrong and the bonding prediction fails.',
    insight: 'Only the outermost electrons take part in bonding. Everything underneath is spectator.',
    resolution: 'At the solved valence count the model predicts the correct bonding behaviour.',
    model: {
      kind: 'sumToConstant',
      params: { known: 10, total: 17, leftName: 'Core + valence', rightName: 'Total electrons', productUnit: 'e⁻' },
      control: { label: 'Valence electrons', unit: 'e⁻', min: 0, max: 14, precision: 0 },
      tolerance: 0.4,
      start: 92,
    },
  },
  {
    slug: 'ionic-bonding',
    title: 'Ionic bonding',
    lab: 'atom',
    formula: '\\sum q_{+} + \\sum q_{-} = 0',
    scenario: 'a de-icing compound being mixed for an airfield',
    crisis: 'Each magnesium ion carries a 2+ charge. Chloride ions carry 1- each, and the ratio in the mix is wrong, so the compound will not crystallise.',
    insight: 'Ionic compounds must come out electrically neutral. The ratio of ions is forced by their charges.',
    resolution: 'At the solved chloride count the charges cancel exactly and the crystal forms.',
    model: {
      kind: 'ratioMatch',
      params: { a: 1, b: 2, c: 1, leftName: 'Negative charge', rightName: 'Positive charge', productUnit: 'e' },
      control: { label: 'Chloride ions per magnesium', unit: '', min: 0, max: 6, precision: 2 },
      tolerance: 0.2,
      start: 90,
    },
  },
  {
    slug: 'covalent-bonding',
    title: 'Covalent bonding',
    lab: 'atom',
    formula: 'E_{total} = n E_{bond}',
    scenario: 'a fuel analysis rig measuring what a hydrocarbon releases',
    crisis: 'Breaking the sample apart takes 1392 kJ/mol. Each carbon-carbon bond costs 348 kJ/mol, and the assumed bond count is wrong.',
    insight: 'Covalent bonds are shared electrons, and each one takes a fixed amount of energy to break.',
    resolution: 'At the solved bond count the energy books balance at 1392 kJ/mol.',
    model: {
      kind: 'proportional',
      params: { k: 348, targetY: 1392, leftName: 'Energy to break', rightName: 'Measured energy', productUnit: 'kJ/mol' },
      control: { label: 'Carbon-carbon bonds', unit: '', min: 0, max: 10, precision: 2 },
      tolerance: 90,
      start: 88,
    },
  },
  {
    slug: 'chemical-equations',
    title: 'Chemical equations',
    lab: 'reaction',
    formula: '2H_2 + O_2 \\rightarrow 2H_2O',
    scenario: 'a fuel cell being commissioned for a remote clinic',
    crisis: 'The oxygen side supplies enough for 4 hydrogen atoms. The hydrogen coefficient is wrong, so atoms go unaccounted for and the cell will not start.',
    insight: 'Atoms are never created or destroyed in a reaction. Whatever goes in on the left must come out on the right.',
    resolution: 'At the solved coefficient every hydrogen atom is accounted for and the equation balances.',
    model: {
      kind: 'ratioMatch',
      params: { a: 2, b: 4, c: 1, leftName: 'Hydrogen atoms supplied', rightName: 'Hydrogen atoms needed', productUnit: 'atoms' },
      control: { label: 'H₂ coefficient', unit: '', min: 0, max: 8, precision: 2 },
      tolerance: 0.3,
      start: 88,
    },
  },
  {
    slug: 'conservation-of-mass',
    title: 'Conservation of mass',
    lab: 'reaction',
    formula: 'm_{reactants} = m_{products}',
    scenario: 'a school lab that appears to have lost mass mid-reaction',
    crisis: '100 g of reactants went in. Only 44 g of carbon dioxide was captured, and the remaining product mass is logged wrong.',
    insight: 'Reactions never lose mass. If the scale disagrees, something escaped as gas and was not measured.',
    resolution: 'At the solved product mass the totals match at 100 g and the apparent loss disappears.',
    model: {
      kind: 'sumToConstant',
      params: { known: 44, total: 100, leftName: 'Products measured', rightName: 'Reactants in', productUnit: 'g' },
      control: { label: 'Remaining product mass', unit: 'g', min: 0, max: 120, precision: 1 },
      tolerance: 3,
      start: 8,
    },
  },
  {
    slug: 'acid-base-balance',
    title: 'Acid-base balance',
    lab: 'ph',
    formula: 'pH = -\\log_{10}[H^+]',
    scenario: 'a fish hatchery whose tanks have turned acidic overnight',
    crisis: 'The fry survive at pH 6.0. The hydrogen ion concentration is far from that, and the buffer dose is set wrong.',
    insight: 'pH is a logarithm. Dropping one pH unit means ten times more hydrogen ions, not a little more.',
    resolution: 'At the solved concentration the tank reads pH 6.0 and the fry stabilise.',
    model: {
      kind: 'logAcidity',
      params: { targetPH: 6, leftName: 'Measured pH', rightName: 'Target pH', productUnit: 'pH' },
      control: { label: 'Hydrogen ion concentration', unit: 'µmol/L', min: 0.05, max: 4, precision: 3 },
      tolerance: 0.05,
      start: 88,
    },
  },
  {
    slug: 'ph-calibration',
    title: 'pH calibration',
    lab: 'ph',
    formula: 'pH = -\\log_{10}[H^+]',
    scenario: 'a soil probe being calibrated before a planting survey',
    crisis: 'The reference buffer is certified at pH 4.5. The probe is reporting a concentration that does not correspond to it.',
    insight: 'A meter is only as trustworthy as its calibration. Match it against a known standard before you trust any field reading.',
    resolution: 'At the solved concentration the probe reads exactly 4.5 and the survey can begin.',
    model: {
      kind: 'logAcidity',
      params: { targetPH: 4.5, leftName: 'Probe pH', rightName: 'Buffer standard', productUnit: 'pH' },
      control: { label: 'Hydrogen ion concentration', unit: 'µmol/L', min: 2, max: 90, precision: 2 },
      tolerance: 0.03,
      start: 88,
    },
  },
  {
    slug: 'solute-saturation',
    title: 'Solute saturation',
    lab: 'particle',
    formula: 'S = \\frac{m_{solute}}{m_{solution}}',
    scenario: 'a brine tank feeding an ice-road de-icing rig',
    crisis: 'The rig needs a solution that is 36% salt by mass. The batch holds 250 g of solution, and the salt mass is wrong.',
    insight: 'Concentration is a ratio, not an amount. The same mass of salt is strong in a cup and weak in a bucket.',
    resolution: 'At the solved salt mass the batch sits at exactly 36% and the rig sprays correctly.',
    model: {
      kind: 'proportional',
      params: { k: 0.004, targetY: 0.36, leftName: 'Mass fraction', rightName: 'Required fraction', productUnit: '' },
      control: { label: 'Salt mass', unit: 'g', min: 0, max: 200, precision: 1 },
      tolerance: 0.02,
      start: 8,
    },
  },
  {
    slug: 'solution-concentration',
    title: 'Solution concentration',
    lab: 'particle',
    formula: 'C = \\frac{n}{V}',
    scenario: 'a pharmacy diluting a stock solution for a paediatric dose',
    crisis: '0.6 mol of active compound must end up at 0.25 mol/L. The final volume is set wrong, and the dose would be unsafe.',
    insight: 'Diluting does not remove anything. The same amount of substance is simply spread through more liquid.',
    resolution: 'At the solved final volume the concentration lands exactly on 0.25 mol/L.',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 0.6, leftB: 1, rightA: 0.25, leftName: 'Moles present', rightName: 'Concentration × volume', productUnit: 'mol' },
      control: { label: 'Final volume', unit: 'L', min: 0.5, max: 5, precision: 2 },
      tolerance: 0.03,
      start: 88,
    },
  },
  {
    slug: 'reaction-rates',
    title: 'Reaction rates',
    lab: 'reaction',
    formula: 'rate = \\frac{\\Delta[P]}{\\Delta t}',
    scenario: 'a chemical hand-warmer being timed before a mountain expedition',
    crisis: 'The reaction produces 0.045 mol/L of product at 0.0025 mol/L per second. The predicted duration is wrong.',
    insight: 'Rate connects amount and time. Knowing any two of the three tells you the third.',
    resolution: 'At the solved duration the product yield matches exactly what the reaction delivers.',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 0.045, leftB: 1, rightA: 0.0025, leftName: 'Product formed', rightName: 'Rate × time', productUnit: 'mol/L' },
      control: { label: 'Reaction duration', unit: 's', min: 2, max: 40, precision: 1 },
      tolerance: 0.0022,
      start: 88,
    },
  },
  {
    slug: 'catalyst-pathways',
    title: 'Catalyst pathways',
    lab: 'reaction',
    formula: 'E_{a,cat} = E_a - \\Delta E',
    scenario: 'an exhaust converter that stopped working in cold weather',
    crisis: 'Uncatalysed, the reaction needs 75 kJ/mol. The converter only supplies 52 kJ/mol, and the catalyst’s contribution is set wrong.',
    insight: 'A catalyst does not push the reaction. It opens a cheaper route with a lower barrier, and is unchanged at the end.',
    resolution: 'At the solved reduction the barrier drops to 52 kJ/mol and the converter lights off.',
    model: {
      kind: 'sumToConstant',
      params: { known: 52, total: 75, leftName: 'Barrier accounted', rightName: 'Uncatalysed barrier', productUnit: 'kJ/mol' },
      control: { label: 'Catalyst reduction', unit: 'kJ/mol', min: 0, max: 60, precision: 1 },
      tolerance: 1.8,
      start: 88,
    },
  },
  {
    slug: 'oxidation',
    title: 'Oxidation',
    lab: 'reaction',
    formula: '\\mathrm{Ox}: e^- \\text{ lost}',
    scenario: 'a hull inspection finding rust below the waterline',
    crisis: 'The corrosion model only closes if the metal releases exactly 6 electrons per formula unit. The logged count is wrong.',
    insight: 'Oxidation is electron loss. Rust is iron slowly giving its electrons away to oxygen.',
    resolution: 'At the solved electron count the half-reaction balances and the corrosion rate can be predicted.',
    model: {
      kind: 'proportional',
      params: { k: 1, targetY: 6, leftName: 'Electrons lost', rightName: 'Electrons required', productUnit: 'e⁻' },
      control: { label: 'Electrons released', unit: 'e⁻', min: 0, max: 14, precision: 2 },
      tolerance: 0.4,
      start: 92,
    },
  },
  {
    slug: 'reduction',
    title: 'Reduction',
    lab: 'reaction',
    formula: '\\mathrm{Red}: e^- \\text{ gained}',
    scenario: 'a silver recovery cell reclaiming metal from waste solution',
    crisis: 'Every electron lost on one side must be gained on the other. The cell expects 4 electrons per unit, and the count is wrong.',
    insight: 'Reduction and oxidation always happen together. Electrons do not vanish — they move.',
    resolution: 'At the solved electron count both half-reactions match and silver plates out cleanly.',
    model: {
      kind: 'proportional',
      params: { k: 1, targetY: 4, leftName: 'Electrons gained', rightName: 'Electrons available', productUnit: 'e⁻' },
      control: { label: 'Electrons accepted', unit: 'e⁻', min: 0, max: 12, precision: 2 },
      tolerance: 0.35,
      start: 90,
    },
  },
  {
    slug: 'periodic-patterns',
    title: 'Periodic patterns',
    lab: 'atom',
    formula: 'Z_{eff} = Z - S',
    scenario: 'a trends worksheet that keeps predicting the wrong atomic radius',
    crisis: 'Sulfur has 16 protons, and its outer electrons feel an effective pull of 6.1. The shielding value in the model is wrong.',
    insight: 'Inner electrons shield the outer ones from the nucleus. That shielding is why atoms get bigger down a group.',
    resolution: 'At the solved shielding value the effective charge lands on 6.1 and the radius prediction works.',
    model: {
      kind: 'sumToConstant',
      params: { known: 6.1, total: 16, leftName: 'Effective + shielding', rightName: 'Nuclear charge', productUnit: 'e' },
      control: { label: 'Shielding constant', unit: '', min: 0, max: 20, precision: 2 },
      tolerance: 0.6,
      start: 8,
    },
  },
  {
    slug: 'density-layers',
    title: 'Density layers',
    lab: 'particle',
    formula: '\\rho = \\frac{m}{V}',
    scenario: 'an oil spill response team predicting where a slick will sit',
    crisis: 'The sample weighs 240 g and must have a density of 0.8 g/mL to float on seawater. The measured volume is wrong.',
    insight: 'Density decides what floats. It is not about being heavy — it is about mass packed into a given space.',
    resolution: 'At the solved volume the density lands on 0.8 g/mL and the slick behaviour can be predicted.',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 240, leftB: 1, rightA: 0.8, leftName: 'Sample mass', rightName: 'Density × volume', productUnit: 'g' },
      control: { label: 'Sample volume', unit: 'mL', min: 50, max: 600, precision: 1 },
      tolerance: 14,
      start: 8,
    },
  },
  {
    slug: 'separation-methods',
    title: 'Separation methods',
    lab: 'ratio',
    formula: 'R_f = \\frac{d_{solute}}{d_{solvent}}',
    scenario: 'a forensic lab matching ink from a disputed document',
    crisis: 'The reference dye has an R_f of 0.42. The solvent front travelled 8.5 cm, and the logged solute distance does not match.',
    insight: 'R_f is a ratio, so it stays the same whatever size the paper is. That is what makes it a usable fingerprint.',
    resolution: 'At the solved solute distance the R_f lands on 0.42 and the ink is identified.',
    model: {
      kind: 'ratioMatch',
      params: { a: 1, b: 0.42, c: 8.5, leftName: 'Solute distance', rightName: 'R_f × solvent front', productUnit: 'cm' },
      control: { label: 'Solute distance', unit: 'cm', min: 0, max: 9, precision: 2 },
      tolerance: 0.25,
      start: 90,
    },
  },
  {
    slug: 'molecular-polarity',
    title: 'Molecular polarity',
    lab: 'atom',
    formula: '\\mu = qr',
    scenario: 'a membrane filter that lets the wrong molecules through',
    crisis: 'The filter blocks anything with a dipole moment above 1.85 D. The modelled charge separation is wrong, so the prediction is useless.',
    insight: 'Polarity comes from charge separated across a distance. Shape matters as much as which atoms are present.',
    resolution: 'At the solved separation the dipole moment lands on 1.85 D and the filter model matches reality.',
    model: {
      kind: 'proportional',
      params: { k: 1.2, targetY: 1.85, leftName: 'Dipole moment', rightName: 'Filter threshold', productUnit: 'D' },
      control: { label: 'Charge separation', unit: 'Å', min: 0, max: 3.2, precision: 3 },
      tolerance: 0.11,
      start: 8,
    },
  },
  {
    slug: 'heat-of-reaction',
    title: 'Heat of reaction',
    lab: 'reaction',
    formula: '\\Delta H = \\frac{q}{n}',
    scenario: 'a calorimeter checking a new hand-warmer formula',
    crisis: 'The run released 57 kJ. The formula is rated at 38 kJ per mole, and the assumed amount of reactant is wrong.',
    insight: 'Enthalpy change is energy per mole, not per run. Doubling the reactant doubles the heat, not the rating.',
    resolution: 'At the solved amount the released heat matches 57 kJ and the rating is confirmed.',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 57000, leftB: 1, rightA: 38000, leftName: 'Heat released', rightName: 'ΔH × moles', productUnit: 'J' },
      control: { label: 'Amount of reactant', unit: 'mol', min: 0.2, max: 3.2, precision: 3 },
      tolerance: 2600,
      start: 90,
    },
  },
  {
    slug: 'carbon-cycles',
    title: 'Carbon cycles',
    lab: 'ecosystem',
    formula: 'C + O_2 \\rightarrow CO_2',
    scenario: 'a biochar kiln being tuned so it burns clean',
    crisis: 'The kiln feeds in 2.4 mol of carbon per cycle. The oxygen supply is set wrong, so it smokes instead of burning fully.',
    insight: 'Complete combustion needs one oxygen molecule per carbon atom. Starve it and you get soot and carbon monoxide.',
    resolution: 'At the solved oxygen supply every carbon atom finds a partner and the kiln burns clean.',
    model: {
      kind: 'ratioMatch',
      params: { a: 1, b: 1, c: 2.4, leftName: 'Oxygen supplied', rightName: 'Oxygen required', productUnit: 'mol' },
      control: { label: 'Oxygen supply', unit: 'mol', min: 0, max: 6, precision: 2 },
      tolerance: 0.16,
      start: 8,
    },
  },
];

export default chemistry;
