/** Mathematics missions. See physics.js for the shape of an entry. */

const mathematics = [
  {
    slug: 'ratios',
    chapterId: 'mathematics.ratio-proportion',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Ratios',
    lab: 'ratio',
    formula: 'a : b = c : x',
    scenario: 'a concrete mixer on a bridge repair with one bag of cement left',
    crisis: 'The mix is specified 3 parts cement to 5 parts sand. There are 12 units of cement in the hopper and the sand feed is set wrong.',
    insight: 'A ratio is a rule about relative size, not fixed amounts. Scale both sides together and the mix stays correct.',
    resolution: 'At the solved sand quantity the mix holds the 3:5 rule exactly and the pour goes ahead.',
    model: {
      kind: 'ratioMatch',
      params: { a: 3, b: 5, c: 12, leftName: 'Cement × sand', rightName: 'Required ratio', productUnit: 'units' },
      control: { label: 'Sand quantity', unit: 'units', min: 0, max: 40, precision: 2 },
      tolerance: 3,
      start: 90,
    },
  },
  {
    slug: 'proportions',
    chapterId: 'mathematics.ratio-proportion',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Proportions',
    lab: 'ratio',
    formula: 'y = kx',
    scenario: 'a water pump costed by the hour for a drought response',
    crisis: 'The pump moves 2.4 kL per hour and the reservoir needs 42 kL before nightfall. The runtime booked is wrong.',
    insight: 'In direct proportion the ratio never changes. Double the hours and you double the water, exactly.',
    resolution: 'At the solved runtime the pump delivers precisely 42 kL.',
    model: {
      kind: 'proportional',
      params: { k: 2.4, targetY: 42, leftName: 'Water delivered', rightName: 'Reservoir need', productUnit: 'kL' },
      control: { label: 'Pump runtime', unit: 'h', min: 0, max: 40, precision: 2 },
      tolerance: 2.4,
      start: 8,
    },
  },
  {
    slug: 'fractions',
    chapterId: 'mathematics.fractions-decimals',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Fractions',
    lab: 'fraction',
    formula: '\\frac{part}{whole}',
    scenario: 'a relief warehouse splitting 64 pallets between two districts',
    crisis: 'The larger district must receive 40 pallets. The fraction written on the dispatch order is wrong.',
    insight: 'A fraction is a division waiting to happen. It tells you which slice of the whole you are taking.',
    resolution: 'At the solved fraction the split gives exactly 40 pallets to the larger district.',
    model: {
      kind: 'proportional',
      params: { k: 64, targetY: 40, leftName: 'Pallets allocated', rightName: 'Pallets required', productUnit: 'pallets' },
      control: { label: 'Fraction of the whole', unit: '', min: 0, max: 1, precision: 3 },
      tolerance: 1.6,
      start: 10,
    },
  },
  {
    slug: 'linear-equations',
    chapterId: 'mathematics.algebra-equations',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Linear equations',
    lab: 'coordinate',
    formula: 'ax = c',
    scenario: 'a ferry loading ramp rated by axle weight',
    crisis: 'Each vehicle loads 4 tonnes onto the ramp. The ramp is certified to exactly 68 tonnes and the vehicle count is wrong.',
    insight: 'Solving an equation means undoing what was done to the unknown, in reverse order.',
    resolution: 'At the solved vehicle count the ramp carries exactly its certified load.',
    model: {
      kind: 'proportional',
      params: { k: 4, targetY: 68, leftName: 'Total load', rightName: 'Ramp rating', productUnit: 't' },
      control: { label: 'Vehicles on the ramp', unit: '', min: 0, max: 40, precision: 2 },
      tolerance: 4,
      start: 92,
    },
  },
  {
    slug: 'coordinate-planes',
    chapterId: 'mathematics.coordinate-graphs',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Coordinate planes',
    lab: 'coordinate',
    formula: 'd^2 = x^2 + y^2',
    scenario: 'a drone flying a straight line to a stranded hiker',
    crisis: 'The hiker is 6 km east of the launch point. The drone has fuel for exactly 10 km of straight-line flight, and the north offset is wrong.',
    insight: 'On a grid, straight-line distance is never the sum of the legs. It is the diagonal, and it is always shorter.',
    resolution: 'At the solved north offset the direct distance is exactly 10 km, at the edge of the fuel range.',
    model: {
      kind: 'pythagoras',
      params: { known: 6, hypotenuse: 10, leftName: 'Direct distance', rightName: 'Fuel range', productUnit: 'km' },
      control: { label: 'North offset', unit: 'km', min: 0, max: 16, precision: 2 },
      tolerance: 0.35,
      start: 92,
    },
  },
  {
    slug: 'gradient-paths',
    chapterId: 'mathematics.coordinate-graphs',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Gradient paths',
    lab: 'coordinate',
    formula: 'm = \\frac{\\Delta y}{\\Delta x}',
    scenario: 'a wheelchair ramp being designed for a village clinic',
    crisis: 'The regulation gradient is 0.75 over the available 12 m run. The proposed rise does not match it.',
    insight: 'Gradient is rise divided by run. A steeper line covers more height in the same horizontal distance.',
    resolution: 'At the solved rise the ramp sits exactly on the 0.75 gradient the regulation requires.',
    model: {
      kind: 'proportional',
      params: { k: 0.08333, targetY: 0.75, leftName: 'Actual gradient', rightName: 'Regulation gradient', productUnit: '' },
      control: { label: 'Vertical rise', unit: 'm', min: 0, max: 20, precision: 2 },
      tolerance: 0.04,
      start: 8,
    },
  },
  {
    slug: 'scale-drawings',
    chapterId: 'mathematics.ratio-proportion',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Scale drawings',
    lab: 'ratio',
    formula: 'scale = \\frac{drawing}{actual}',
    scenario: 'an evacuation floor plan being redrawn for a school wall',
    crisis: 'The corridor is 45 m long and the plan uses 0.4 cm per metre. The drawn length is wrong, so the exits sit in the wrong place.',
    insight: 'A scale drawing keeps every proportion. Get one length wrong and every distance derived from it is wrong too.',
    resolution: 'At the solved drawn length the plan is faithful and the exits land correctly.',
    model: {
      kind: 'ratioMatch',
      params: { a: 1, b: 0.4, c: 45, leftName: 'Drawn length', rightName: 'Scale × actual', productUnit: 'cm' },
      control: { label: 'Drawn corridor length', unit: 'cm', min: 0, max: 40, precision: 2 },
      tolerance: 0.9,
      start: 90,
    },
  },
  {
    slug: 'similar-shapes',
    chapterId: 'mathematics.ratio-proportion',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Similar shapes',
    lab: 'ratio',
    formula: '\\frac{a}{b} = \\frac{a\'}{b\'}',
    scenario: 'a replacement sail being cut from a photograph of the original',
    crisis: 'The original measured 8 m by 12 m. The new luff is 14 m and the matching edge is cut wrong, so the sail sets badly.',
    insight: 'Similar shapes share angles and scale every length by the same factor. One wrong side breaks the similarity.',
    resolution: 'At the solved edge length the new sail is truly similar to the original.',
    model: {
      kind: 'ratioMatch',
      params: { a: 8, b: 12, c: 14, leftName: 'New shape ratio', rightName: 'Original ratio', productUnit: 'm²' },
      control: { label: 'Matching edge', unit: 'm', min: 0, max: 45, precision: 2 },
      tolerance: 8,
      start: 8,
    },
  },
  {
    slug: 'interior-angles',
    chapterId: 'mathematics.geometry-shape',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Interior angles',
    lab: 'geometry',
    formula: '\\sum\\theta = 180^\\circ',
    scenario: 'a roof truss being cut on site with one angle unmarked',
    crisis: 'Two angles of the triangle measure 112° together. The third is cut wrong and the truss will not close.',
    insight: 'Every triangle, no matter its shape, holds exactly 180° inside it. That is what makes the third angle knowable.',
    resolution: 'At the solved angle the triangle closes exactly and the truss seats flush.',
    model: {
      kind: 'sumToConstant',
      params: { known: 112, total: 180, leftName: 'Angle sum', rightName: 'Triangle total', productUnit: '°' },
      control: { label: 'Third angle', unit: '°', min: 0, max: 140, precision: 1 },
      tolerance: 3.5,
      start: 92,
    },
  },
  {
    slug: 'triangle-properties',
    chapterId: 'mathematics.geometry-shape',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Triangle properties',
    lab: 'triangle',
    formula: 'a^2 + b^2 = c^2',
    scenario: 'a radio mast held by a guy wire on a rocky slope',
    crisis: 'The anchor sits 9 m from the base and the wire is exactly 15 m long. The attachment height on the mast is wrong.',
    insight: 'In a right triangle the two shorter sides squared always add to the longest side squared. No measurement needed for the third.',
    resolution: 'At the solved attachment height the wire is exactly 15 m taut and the mast is stable.',
    model: {
      kind: 'pythagoras',
      params: { known: 9, hypotenuse: 15, leftName: 'Wire length needed', rightName: 'Wire available', productUnit: 'm' },
      control: { label: 'Attachment height', unit: 'm', min: 0, max: 24, precision: 2 },
      tolerance: 0.55,
      start: 8,
    },
  },
  {
    slug: 'pythagorean-paths',
    chapterId: 'mathematics.geometry-shape',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Pythagorean paths',
    lab: 'triangle',
    formula: 'd^2 = x^2 + y^2',
    scenario: 'a supply run cutting diagonally across a flooded grid of streets',
    crisis: 'The depot is 20 blocks west. The vehicle has range for a 29 block diagonal, and the north leg is planned wrong.',
    insight: 'The diagonal is always shorter than going around, but it grows fast — squares add, not lengths.',
    resolution: 'At the solved north leg the diagonal is exactly 29 blocks and the run is inside range.',
    model: {
      kind: 'pythagoras',
      params: { known: 20, hypotenuse: 29, leftName: 'Diagonal distance', rightName: 'Vehicle range', productUnit: 'blocks' },
      control: { label: 'North leg', unit: 'blocks', min: 0, max: 40, precision: 2 },
      tolerance: 0.9,
      start: 92,
    },
  },
  {
    slug: 'circle-measures',
    chapterId: 'mathematics.measurement-mensuration',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Circle measures',
    lab: 'circle',
    formula: 'C = 2\\pi r',
    scenario: 'a water tank being wrapped with a fixed length of insulation',
    crisis: 'There is exactly 44 m of insulating band. The tank radius on the order form is wrong, so the band will not meet.',
    insight: 'Circumference grows in a straight line with radius, and the constant linking them is always π.',
    resolution: 'At the solved radius the circumference is exactly 44 m and the band closes.',
    model: {
      kind: 'proportional',
      params: { k: 6.2832, targetY: 44, leftName: 'Circumference', rightName: 'Band length', productUnit: 'm' },
      control: { label: 'Tank radius', unit: 'm', min: 0, max: 15, precision: 3 },
      tolerance: 2.4,
      start: 90,
    },
  },
  {
    slug: 'golden-ratio',
    chapterId: 'mathematics.ratio-proportion',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Golden ratio',
    lab: 'area',
    formula: '\\varphi = \\frac{1+\\sqrt5}{2}',
    scenario: 'a museum frame being cut to the proportions of the painting inside',
    crisis: 'The long side is fixed at 16.18 cm. The short side is cut wrong, so the frame reads visibly off-balance.',
    insight: 'The golden ratio is a proportion, not a magic number. It shows up wherever a whole relates to its larger part the way that part relates to the smaller.',
    resolution: 'At the solved short side the frame sits exactly on φ and the proportion reads correct.',
    model: {
      kind: 'proportional',
      params: { k: 1.618, targetY: 16.18, leftName: 'Scaled length', rightName: 'Long side', productUnit: 'cm' },
      control: { label: 'Short side', unit: 'cm', min: 0, max: 22, precision: 3 },
      tolerance: 0.8,
      start: 8,
    },
  },
  {
    slug: 'transformations',
    chapterId: 'mathematics.geometry-shape',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Transformations',
    lab: 'numberline',
    formula: '(x, y) \\rightarrow (x + a, y + b)',
    scenario: 'a survey dataset logged against the wrong origin marker',
    crisis: 'Every point sits at -14 on the east axis but should read 23. The correction offset applied is wrong.',
    insight: 'A translation slides every point by the same amount. Shape and size never change, only position.',
    resolution: 'At the solved offset every logged point lands on its true coordinate.',
    model: {
      kind: 'sumToConstant',
      params: { known: -14, total: 23, leftName: 'Corrected position', rightName: 'True position', productUnit: 'm' },
      control: { label: 'Correction offset', unit: 'm', min: 0, max: 80, precision: 1 },
      tolerance: 2,
      start: 8,
    },
  },
  {
    slug: 'symmetry',
    chapterId: 'mathematics.geometry-shape',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Symmetry',
    lab: 'mirror',
    formula: 'x\' = 2a - x',
    scenario: 'a stage lighting rig being mirrored to the opposite wing',
    crisis: 'A fixture sits at position 8. Its mirror must land at 26, and the mirror line is set wrong.',
    insight: 'A reflection sits exactly as far past the mirror line as the original sits before it. The line is always halfway between.',
    resolution: 'At the solved mirror line the fixture reflects precisely onto 26.',
    model: {
      kind: 'proportional',
      params: { k: 2, targetY: 34, leftName: 'Original + reflection', rightName: 'Required span', productUnit: 'm' },
      control: { label: 'Mirror line position', unit: 'm', min: 0, max: 36, precision: 2 },
      tolerance: 1.8,
      start: 8,
    },
  },
  {
    slug: 'probability',
    chapterId: 'mathematics.data-statistics',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Probability',
    lab: 'probability',
    formula: 'P(A) = \\frac{favourable}{total}',
    scenario: 'a raffle for a community solar panel with a promised win rate',
    crisis: '40 tickets are in the drum. The organisers promised a 0.35 chance of drawing a winner, and the winning ticket count is wrong.',
    insight: 'Probability is a ratio between 0 and 1. It says how much of the whole outcome space counts as success.',
    resolution: 'At the solved winner count the draw offers exactly the promised 0.35 chance.',
    model: {
      kind: 'proportional',
      params: { k: 0.025, targetY: 0.35, leftName: 'Actual probability', rightName: 'Promised probability', productUnit: '' },
      control: { label: 'Winning tickets', unit: '', min: 0, max: 30, precision: 2 },
      tolerance: 0.02,
      start: 92,
    },
  },
  {
    slug: 'mean-and-median',
    chapterId: 'mathematics.data-statistics',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Mean and median',
    lab: 'data',
    formula: '\\bar{x} = \\frac{\\sum x}{n}',
    scenario: 'a rainfall station filing a monthly average with one day missing',
    crisis: 'Five days read 38, 56, 72, 64 and 44 mm. The month must average 55 mm, and the missing day is logged wrong.',
    insight: 'The mean is a balance point. One unusual value can drag it a long way, especially in a small sample.',
    resolution: 'At the solved value for the missing day the six-day mean lands exactly on 55 mm.',
    model: {
      kind: 'mean',
      params: { samples: [38, 56, 72, 64, 44], targetMean: 55, leftName: 'Sample mean', rightName: 'Required mean', productUnit: 'mm' },
      control: { label: 'Missing day rainfall', unit: 'mm', min: 0, max: 100, precision: 1 },
      tolerance: 0.45,
      start: 8,
    },
  },
  {
    slug: 'data-spread',
    chapterId: 'mathematics.data-statistics',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Data spread',
    lab: 'data',
    formula: 'range = max - min',
    scenario: 'a cold chain audit on a vaccine shipment',
    crisis: 'The lowest logged temperature was 18. The highest reading must be 65 for the audit to reconstruct, and the recorded range is wrong.',
    insight: 'Range only looks at the two extremes. It says how wide the data is, not how it is distributed inside.',
    resolution: 'At the solved range the reconstructed maximum lands exactly on 65.',
    model: {
      kind: 'sumToConstant',
      params: { known: 18, total: 65, leftName: 'Min + range', rightName: 'Recorded maximum', productUnit: '' },
      control: { label: 'Data range', unit: '', min: 0, max: 90, precision: 1 },
      tolerance: 2.2,
      start: 90,
    },
  },
  {
    slug: 'number-patterns',
    chapterId: 'mathematics.number-sense',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Number patterns',
    lab: 'sequence',
    formula: 'a_n = a_1 + (n-1)d',
    scenario: 'a terraced planting scheme stepping down a hillside',
    crisis: 'The first terrace sits at 7 m elevation and the ninth must reach 63 m. The step between terraces is wrong.',
    insight: 'An arithmetic sequence adds the same amount each time. Knowing any two terms fixes the whole pattern.',
    resolution: 'At the solved step the ninth terrace lands exactly on 63 m.',
    model: {
      kind: 'proportional',
      params: { k: 8, targetY: 56, leftName: 'Total climb', rightName: 'Required climb', productUnit: 'm' },
      control: { label: 'Step between terraces', unit: 'm', min: 0, max: 15, precision: 3 },
      tolerance: 3,
      start: 8,
    },
  },
  {
    slug: 'negative-numbers',
    chapterId: 'mathematics.number-sense',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Negative numbers',
    lab: 'numberline',
    formula: 'a + x = b',
    scenario: 'a submersible logging depth against a shifting sea-level datum',
    crisis: 'The craft reads -23 m on the old datum and must read -8 m on the new one. The correction applied is wrong.',
    insight: 'Negative numbers are directions, not just smaller numbers. Adding a positive to a negative moves you toward zero.',
    resolution: 'At the solved correction the depth log reads -8 m exactly.',
    model: {
      kind: 'sumToConstant',
      params: { known: -23, total: -8, leftName: 'Corrected depth', rightName: 'Target depth', productUnit: 'm' },
      control: { label: 'Datum correction', unit: 'm', min: -40, max: 40, precision: 1 },
      tolerance: 2,
      start: 8,
    },
  },
  {
    slug: 'algebraic-balance',
    chapterId: 'mathematics.algebra-equations',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Algebraic balance',
    lab: 'balance',
    formula: 'L = R',
    scenario: 'a budget reconciliation for a school science fund',
    crisis: 'Confirmed spending is 29 units against a 74 unit ledger total. The outstanding commitment is entered wrong.',
    insight: 'An equation is a balance. Whatever you do to one side you must do to the other, or the truth breaks.',
    resolution: 'At the solved commitment both sides read 74 and the ledger reconciles.',
    model: {
      kind: 'sumToConstant',
      params: { known: 29, total: 74, leftName: 'Left side', rightName: 'Right side', productUnit: 'units' },
      control: { label: 'Outstanding commitment', unit: 'units', min: 0, max: 90, precision: 1 },
      tolerance: 2.2,
      start: 90,
    },
  },
  {
    slug: 'inequalities',
    chapterId: 'mathematics.algebra-equations',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Inequalities',
    lab: 'numberline',
    formula: 'ax \\le c',
    scenario: 'a lift with a strict load limit in a hospital tower',
    crisis: 'Each crate weighs 4 units and the limit is 92 units. The boundary crate count is set wrong, so the alarm keeps firing.',
    insight: 'An inequality marks a boundary, not a single answer. Everything on one side of it is allowed.',
    resolution: 'At the solved boundary count the lift sits exactly on its limit, the last safe load.',
    model: {
      kind: 'proportional',
      params: { k: 4, targetY: 92, leftName: 'Loaded weight', rightName: 'Lift limit', productUnit: 'units' },
      control: { label: 'Crates loaded', unit: '', min: 0, max: 50, precision: 2 },
      tolerance: 5,
      start: 8,
    },
  },
  {
    slug: 'area-and-perimeter',
    chapterId: 'mathematics.measurement-mensuration',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Area and perimeter',
    lab: 'area',
    formula: 'A = lw',
    scenario: 'a tarpaulin being cut to cover a damaged grain store',
    crisis: 'The store needs 252 m² of cover and the tarp is 14 m along its fixed edge. The cut width is wrong.',
    insight: 'Area is a product of two lengths, so it grows twice as fast as either one. Doubling both quadruples the area.',
    resolution: 'At the solved width the tarp covers exactly 252 m².',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 252, leftB: 1, rightA: 14, leftName: 'Area required', rightName: 'Length × width', productUnit: 'm²' },
      control: { label: 'Cut width', unit: 'm', min: 0, max: 40, precision: 2 },
      tolerance: 14,
      start: 92,
    },
  },
  {
    slug: 'volume-scaling',
    chapterId: 'mathematics.measurement-mensuration',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Volume scaling',
    lab: 'volume',
    formula: 'V = A_{base} h',
    scenario: 'a rainwater cistern being sized for a rooftop garden',
    crisis: 'The cistern must hold 1080 L and its base area is fixed at 72 dm². The planned height is wrong.',
    insight: 'Volume is area multiplied by height. Scaling every dimension by two multiplies volume by eight, not two.',
    resolution: 'At the solved height the cistern holds exactly 1080 L.',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 1080, leftB: 1, rightA: 72, leftName: 'Volume required', rightName: 'Base × height', productUnit: 'L' },
      control: { label: 'Cistern height', unit: 'dm', min: 0, max: 32, precision: 2 },
      tolerance: 58,
      start: 8,
    },
  },
  {
    slug: 'graph-interpretation',
    chapterId: 'mathematics.coordinate-graphs',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Graph interpretation',
    lab: 'coordinate',
    formula: 'y = f(x)',
    scenario: 'a clinic reading a dosage chart it cannot afford to misread',
    crisis: 'The chart rises 3.5 units of dose per kilogram of body mass. The prescribed dose is 91 units and the mass read off the axis is wrong.',
    insight: 'A graph is a picture of a relationship. Reading it means moving between the axes, not just looking at the line.',
    resolution: 'At the solved body mass the chart gives exactly the 91 unit dose.',
    model: {
      kind: 'proportional',
      params: { k: 3.5, targetY: 91, leftName: 'Charted dose', rightName: 'Prescribed dose', productUnit: 'units' },
      control: { label: 'Body mass', unit: 'kg', min: 0, max: 55, precision: 2 },
      tolerance: 4.8,
      start: 92,
    },
  },
];

export default mathematics;
