/** Mathematics missions. See physics.js for the shape of an entry. */

const mathematics = [
  {
    slug: 'ratios',
    chapterId: 'mathematics.ratio-proportion',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Ratios',
    lab: 'ratio',
    formula: 'a : b = c : x',
    scenario: 'a concrete mixer on a bridge repair with one bag of cement left',
    crisis: 'The mix is specified 3 parts cement to 5 parts sand. There are 12 units of cement in the hopper and the sand feed is set wrong.',
    insight: 'A ratio is a rule about relative size, not fixed amounts. Scale both sides together and the mix stays correct.',
    resolution: 'At the solved sand quantity the mix holds the 3:5 rule exactly and the pour goes ahead.',
    model: {
      kind: 'ratioMatch',
      params: { a: 3, b: 5, c: 12, leftName: 'Cement × sand', rightName: 'Required ratio', productUnit: 'units' },
      control: { label: 'Sand quantity', unit: 'units', min: 0, max: 40, precision: 2 },
      tolerance: 3,
      start: 90,
    },
  },
  {
    slug: 'proportions',
    chapterId: 'mathematics.ratio-proportion',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Proportions',
    lab: 'ratio',
    formula: 'y = kx',
    scenario: 'a water pump costed by the hour for a drought response',
    crisis: 'The pump moves 2.4 kL per hour and the reservoir needs 42 kL before nightfall. The runtime booked is wrong.',
    insight: 'In direct proportion the ratio never changes. Double the hours and you double the water, exactly.',
    resolution: 'At the solved runtime the pump delivers precisely 42 kL.',
    model: {
      kind: 'proportional',
      params: { k: 2.4, targetY: 42, leftName: 'Water delivered', rightName: 'Reservoir need', productUnit: 'kL' },
      control: { label: 'Pump runtime', unit: 'h', min: 0, max: 40, precision: 2 },
      tolerance: 2.4,
      start: 8,
    },
  },
  {
    slug: 'fractions',
    chapterId: 'mathematics.fractions-decimals',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Fractions',
    lab: 'fraction',
    formula: '\\frac{part}{whole}',
    scenario: 'a relief warehouse splitting 64 pallets between two districts',
    crisis: 'The larger district must receive 40 pallets. The fraction written on the dispatch order is wrong.',
    insight: 'A fraction is a division waiting to happen. It tells you which slice of the whole you are taking.',
    resolution: 'At the solved fraction the split gives exactly 40 pallets to the larger district.',
    model: {
      kind: 'proportional',
      params: { k: 64, targetY: 40, leftName: 'Pallets allocated', rightName: 'Pallets required', productUnit: 'pallets' },
      control: { label: 'Fraction of the whole', unit: '', min: 0, max: 1, precision: 3 },
      tolerance: 1.6,
      start: 10,
    },
  },
  {
    slug: 'linear-equations',
    chapterId: 'mathematics.algebra-equations',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Linear equations',
    lab: 'coordinate',
    formula: 'ax = c',
    scenario: 'a ferry loading ramp rated by axle weight',
    crisis: 'Each vehicle loads 4 tonnes onto the ramp. The ramp is certified to exactly 68 tonnes and the vehicle count is wrong.',
    insight: 'Solving an equation means undoing what was done to the unknown, in reverse order.',
    resolution: 'At the solved vehicle count the ramp carries exactly its certified load.',
    model: {
      kind: 'proportional',
      params: { k: 4, targetY: 68, leftName: 'Total load', rightName: 'Ramp rating', productUnit: 't' },
      control: { label: 'Vehicles on the ramp', unit: '', min: 0, max: 40, precision: 2 },
      tolerance: 4,
      start: 92,
    },
  },
  {
    slug: 'coordinate-planes',
    chapterId: 'mathematics.coordinate-graphs',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Coordinate planes',
    lab: 'coordinate',
    formula: 'd^2 = x^2 + y^2',
    scenario: 'a drone flying a straight line to a stranded hiker',
    crisis: 'The hiker is 6 km east of the launch point. The drone has fuel for exactly 10 km of straight-line flight, and the north offset is wrong.',
    insight: 'On a grid, straight-line distance is never the sum of the legs. It is the diagonal, and it is always shorter.',
    resolution: 'At the solved north offset the direct distance is exactly 10 km, at the edge of the fuel range.',
    model: {
      kind: 'pythagoras',
      params: { known: 6, hypotenuse: 10, leftName: 'Direct distance', rightName: 'Fuel range', productUnit: 'km' },
      control: { label: 'North offset', unit: 'km', min: 0, max: 16, precision: 2 },
      tolerance: 0.35,
      start: 92,
    },
  },
  {
    slug: 'gradient-paths',
    chapterId: 'mathematics.coordinate-graphs',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Gradient paths',
    lab: 'coordinate',
    formula: 'm = \\frac{\\Delta y}{\\Delta x}',
    scenario: 'a wheelchair ramp being designed for a village clinic',
    crisis: 'The regulation gradient is 0.75 over the available 12 m run. The proposed rise does not match it.',
    insight: 'Gradient is rise divided by run. A steeper line covers more height in the same horizontal distance.',
    resolution: 'At the solved rise the ramp sits exactly on the 0.75 gradient the regulation requires.',
    model: {
      kind: 'proportional',
      params: { k: 0.08333, targetY: 0.75, leftName: 'Actual gradient', rightName: 'Regulation gradient', productUnit: '' },
      control: { label: 'Vertical rise', unit: 'm', min: 0, max: 20, precision: 2 },
      tolerance: 0.04,
      start: 8,
    },
  },
  {
    slug: 'scale-drawings',
    chapterId: 'mathematics.ratio-proportion',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Scale drawings',
    lab: 'ratio',
    formula: 'scale = \\frac{drawing}{actual}',
    scenario: 'an evacuation floor plan being redrawn for a school wall',
    crisis: 'The corridor is 45 m long and the plan uses 0.4 cm per metre. The drawn length is wrong, so the exits sit in the wrong place.',
    insight: 'A scale drawing keeps every proportion. Get one length wrong and every distance derived from it is wrong too.',
    resolution: 'At the solved drawn length the plan is faithful and the exits land correctly.',
    model: {
      kind: 'ratioMatch',
      params: { a: 1, b: 0.4, c: 45, leftName: 'Drawn length', rightName: 'Scale × actual', productUnit: 'cm' },
      control: { label: 'Drawn corridor length', unit: 'cm', min: 0, max: 40, precision: 2 },
      tolerance: 0.9,
      start: 90,
    },
  },
  {
    slug: 'similar-shapes',
    chapterId: 'mathematics.ratio-proportion',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Similar shapes',
    lab: 'ratio',
    formula: '\\frac{a}{b} = \\frac{a\'}{b\'}',
    scenario: 'a replacement sail being cut from a photograph of the original',
    crisis: 'The original measured 8 m by 12 m. The new luff is 14 m and the matching edge is cut wrong, so the sail sets badly.',
    insight: 'Similar shapes share angles and scale every length by the same factor. One wrong side breaks the similarity.',
    resolution: 'At the solved edge length the new sail is truly similar to the original.',
    model: {
      kind: 'ratioMatch',
      params: { a: 8, b: 12, c: 14, leftName: 'New shape ratio', rightName: 'Original ratio', productUnit: 'm²' },
      control: { label: 'Matching edge', unit: 'm', min: 0, max: 45, precision: 2 },
      tolerance: 8,
      start: 8,
    },
  },
  {
    slug: 'interior-angles',
    chapterId: 'mathematics.geometry-shape',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Interior angles',
    lab: 'geometry',
    formula: '\\sum\\theta = 180^\\circ',
    scenario: 'a roof truss being cut on site with one angle unmarked',
    crisis: 'Two angles of the triangle measure 112° together. The third is cut wrong and the truss will not close.',
    insight: 'Every triangle, no matter its shape, holds exactly 180° inside it. That is what makes the third angle knowable.',
    resolution: 'At the solved angle the triangle closes exactly and the truss seats flush.',
    model: {
      kind: 'sumToConstant',
      params: { known: 112, total: 180, leftName: 'Angle sum', rightName: 'Triangle total', productUnit: '°' },
      control: { label: 'Third angle', unit: '°', min: 0, max: 140, precision: 1 },
      tolerance: 3.5,
      start: 92,
    },
  },
  {
    slug: 'triangle-properties',
    chapterId: 'mathematics.geometry-shape',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Triangle properties',
    lab: 'triangle',
    formula: 'a^2 + b^2 = c^2',
    scenario: 'a radio mast held by a guy wire on a rocky slope',
    crisis: 'The anchor sits 9 m from the base and the wire is exactly 15 m long. The attachment height on the mast is wrong.',
    insight: 'In a right triangle the two shorter sides squared always add to the longest side squared. No measurement needed for the third.',
    resolution: 'At the solved attachment height the wire is exactly 15 m taut and the mast is stable.',
    model: {
      kind: 'pythagoras',
      params: { known: 9, hypotenuse: 15, leftName: 'Wire length needed', rightName: 'Wire available', productUnit: 'm' },
      control: { label: 'Attachment height', unit: 'm', min: 0, max: 24, precision: 2 },
      tolerance: 0.55,
      start: 8,
    },
  },
  {
    slug: 'pythagorean-paths',
    chapterId: 'mathematics.geometry-shape',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Pythagorean paths',
    lab: 'triangle',
    formula: 'd^2 = x^2 + y^2',
    scenario: 'a supply run cutting diagonally across a flooded grid of streets',
    crisis: 'The depot is 20 blocks west. The vehicle has range for a 29 block diagonal, and the north leg is planned wrong.',
    insight: 'The diagonal is always shorter than going around, but it grows fast — squares add, not lengths.',
    resolution: 'At the solved north leg the diagonal is exactly 29 blocks and the run is inside range.',
    model: {
      kind: 'pythagoras',
      params: { known: 20, hypotenuse: 29, leftName: 'Diagonal distance', rightName: 'Vehicle range', productUnit: 'blocks' },
      control: { label: 'North leg', unit: 'blocks', min: 0, max: 40, precision: 2 },
      tolerance: 0.9,
      start: 92,
    },
  },
  {
    slug: 'circle-measures',
    chapterId: 'mathematics.measurement-mensuration',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Circle measures',
    lab: 'circle',
    formula: 'C = 2\\pi r',
    scenario: 'a water tank being wrapped with a fixed length of insulation',
    crisis: 'There is exactly 44 m of insulating band. The tank radius on the order form is wrong, so the band will not meet.',
    insight: 'Circumference grows in a straight line with radius, and the constant linking them is always π.',
    resolution: 'At the solved radius the circumference is exactly 44 m and the band closes.',
    model: {
      kind: 'proportional',
      params: { k: 6.2832, targetY: 44, leftName: 'Circumference', rightName: 'Band length', productUnit: 'm' },
      control: { label: 'Tank radius', unit: 'm', min: 0, max: 15, precision: 3 },
      tolerance: 2.4,
      start: 90,
    },
  },
  {
    slug: 'golden-ratio',
    chapterId: 'mathematics.ratio-proportion',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Golden ratio',
    lab: 'area',
    formula: '\\varphi = \\frac{1+\\sqrt5}{2}',
    scenario: 'a museum frame being cut to the proportions of the painting inside',
    crisis: 'The long side is fixed at 16.18 cm. The short side is cut wrong, so the frame reads visibly off-balance.',
    insight: 'The golden ratio is a proportion, not a magic number. It shows up wherever a whole relates to its larger part the way that part relates to the smaller.',
    resolution: 'At the solved short side the frame sits exactly on φ and the proportion reads correct.',
    model: {
      kind: 'proportional',
      params: { k: 1.618, targetY: 16.18, leftName: 'Scaled length', rightName: 'Long side', productUnit: 'cm' },
      control: { label: 'Short side', unit: 'cm', min: 0, max: 22, precision: 3 },
      tolerance: 0.8,
      start: 8,
    },
  },
  {
    slug: 'transformations',
    chapterId: 'mathematics.geometry-shape',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Transformations',
    lab: 'numberline',
    formula: '(x, y) \\rightarrow (x + a, y + b)',
    scenario: 'a survey dataset logged against the wrong origin marker',
    crisis: 'Every point sits at -14 on the east axis but should read 23. The correction offset applied is wrong.',
    insight: 'A translation slides every point by the same amount. Shape and size never change, only position.',
    resolution: 'At the solved offset every logged point lands on its true coordinate.',
    model: {
      kind: 'sumToConstant',
      params: { known: -14, total: 23, leftName: 'Corrected position', rightName: 'True position', productUnit: 'm' },
      control: { label: 'Correction offset', unit: 'm', min: 0, max: 80, precision: 1 },
      tolerance: 2,
      start: 8,
    },
  },
  {
    slug: 'symmetry',
    chapterId: 'mathematics.geometry-shape',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Symmetry',
    lab: 'mirror',
    formula: 'x\' = 2a - x',
    scenario: 'a stage lighting rig being mirrored to the opposite wing',
    crisis: 'A fixture sits at position 8. Its mirror must land at 26, and the mirror line is set wrong.',
    insight: 'A reflection sits exactly as far past the mirror line as the original sits before it. The line is always halfway between.',
    resolution: 'At the solved mirror line the fixture reflects precisely onto 26.',
    model: {
      kind: 'proportional',
      params: { k: 2, targetY: 34, leftName: 'Original + reflection', rightName: 'Required span', productUnit: 'm' },
      control: { label: 'Mirror line position', unit: 'm', min: 0, max: 36, precision: 2 },
      tolerance: 1.8,
      start: 8,
    },
  },
  {
    slug: 'probability',
    chapterId: 'mathematics.data-statistics',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Probability',
    lab: 'probability',
    formula: 'P(A) = \\frac{favourable}{total}',
    scenario: 'a raffle for a community solar panel with a promised win rate',
    crisis: '40 tickets are in the drum. The organisers promised a 0.35 chance of drawing a winner, and the winning ticket count is wrong.',
    insight: 'Probability is a ratio between 0 and 1. It says how much of the whole outcome space counts as success.',
    resolution: 'At the solved winner count the draw offers exactly the promised 0.35 chance.',
    model: {
      kind: 'proportional',
      params: { k: 0.025, targetY: 0.35, leftName: 'Actual probability', rightName: 'Promised probability', productUnit: '' },
      control: { label: 'Winning tickets', unit: '', min: 0, max: 30, precision: 2 },
      tolerance: 0.02,
      start: 92,
    },
  },
  {
    slug: 'mean-and-median',
    chapterId: 'mathematics.data-statistics',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Mean and median',
    lab: 'data',
    formula: '\\bar{x} = \\frac{\\sum x}{n}',
    scenario: 'a rainfall station filing a monthly average with one day missing',
    crisis: 'Five days read 38, 56, 72, 64 and 44 mm. The month must average 55 mm, and the missing day is logged wrong.',
    insight: 'The mean is a balance point. One unusual value can drag it a long way, especially in a small sample.',
    resolution: 'At the solved value for the missing day the six-day mean lands exactly on 55 mm.',
    model: {
      kind: 'mean',
      params: { samples: [38, 56, 72, 64, 44], targetMean: 55, leftName: 'Sample mean', rightName: 'Required mean', productUnit: 'mm' },
      control: { label: 'Missing day rainfall', unit: 'mm', min: 0, max: 100, precision: 1 },
      tolerance: 0.45,
      start: 8,
    },
  },
  {
    slug: 'data-spread',
    chapterId: 'mathematics.data-statistics',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Data spread',
    lab: 'data',
    formula: 'range = max - min',
    scenario: 'a cold chain audit on a vaccine shipment',
    crisis: 'The lowest logged temperature was 18. The highest reading must be 65 for the audit to reconstruct, and the recorded range is wrong.',
    insight: 'Range only looks at the two extremes. It says how wide the data is, not how it is distributed inside.',
    resolution: 'At the solved range the reconstructed maximum lands exactly on 65.',
    model: {
      kind: 'sumToConstant',
      params: { known: 18, total: 65, leftName: 'Min + range', rightName: 'Recorded maximum', productUnit: '' },
      control: { label: 'Data range', unit: '', min: 0, max: 90, precision: 1 },
      tolerance: 2.2,
      start: 90,
    },
  },
  {
    slug: 'number-patterns',
    chapterId: 'mathematics.number-sense',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Number patterns',
    lab: 'sequence',
    formula: 'a_n = a_1 + (n-1)d',
    scenario: 'a terraced planting scheme stepping down a hillside',
    /**
     * The first terrace used to sit at 7 m and the ninth at 63 m — a 56 m climb
     * over eight steps, so the step is 7 m, the same number the sentence opens
     * with. A learner could read the answer off the first clause and never touch
     * the sequence. Shifted the whole scheme down by 2 m: the climb is still
     * 56 m, the step is still 7 m, and nothing in the model changed.
     */
    crisis: 'The first terrace sits at 5 m elevation and the ninth must reach 61 m. The step between terraces is wrong.',
    insight: 'An arithmetic sequence adds the same amount each time. Knowing any two terms fixes the whole pattern.',
    resolution: 'At the solved step the ninth terrace lands exactly on 61 m.',
    model: {
      kind: 'proportional',
      params: { k: 8, targetY: 56, leftName: 'Total climb', rightName: 'Required climb', productUnit: 'm' },
      control: { label: 'Step between terraces', unit: 'm', min: 0, max: 15, precision: 3 },
      tolerance: 3,
      start: 8,
    },
  },
  {
    slug: 'negative-numbers',
    chapterId: 'mathematics.number-sense',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Negative numbers',
    lab: 'numberline',
    formula: 'a + x = b',
    scenario: 'a submersible logging depth against a shifting sea-level datum',
    crisis: 'The craft reads -23 m on the old datum and must read -8 m on the new one. The correction applied is wrong.',
    insight: 'Negative numbers are directions, not just smaller numbers. Adding a positive to a negative moves you toward zero.',
    resolution: 'At the solved correction the depth log reads -8 m exactly.',
    model: {
      kind: 'sumToConstant',
      params: { known: -23, total: -8, leftName: 'Corrected depth', rightName: 'Target depth', productUnit: 'm' },
      control: { label: 'Datum correction', unit: 'm', min: -40, max: 40, precision: 1 },
      tolerance: 2,
      start: 8,
    },
  },
  {
    slug: 'algebraic-balance',
    chapterId: 'mathematics.algebra-equations',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Algebraic balance',
    lab: 'balance',
    formula: 'L = R',
    scenario: 'a budget reconciliation for a school science fund',
    crisis: 'Confirmed spending is 29 units against a 74 unit ledger total. The outstanding commitment is entered wrong.',
    insight: 'An equation is a balance. Whatever you do to one side you must do to the other, or the truth breaks.',
    resolution: 'At the solved commitment both sides read 74 and the ledger reconciles.',
    model: {
      kind: 'sumToConstant',
      params: { known: 29, total: 74, leftName: 'Left side', rightName: 'Right side', productUnit: 'units' },
      control: { label: 'Outstanding commitment', unit: 'units', min: 0, max: 90, precision: 1 },
      tolerance: 2.2,
      start: 90,
    },
  },
  {
    slug: 'inequalities',
    chapterId: 'mathematics.algebra-equations',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Inequalities',
    lab: 'numberline',
    formula: 'ax \\le c',
    scenario: 'a lift with a strict load limit in a hospital tower',
    crisis: 'Each crate weighs 4 units and the limit is 92 units. The boundary crate count is set wrong, so the alarm keeps firing.',
    insight: 'An inequality marks a boundary, not a single answer. Everything on one side of it is allowed.',
    resolution: 'At the solved boundary count the lift sits exactly on its limit, the last safe load.',
    model: {
      kind: 'proportional',
      params: { k: 4, targetY: 92, leftName: 'Loaded weight', rightName: 'Lift limit', productUnit: 'units' },
      control: { label: 'Crates loaded', unit: '', min: 0, max: 50, precision: 2 },
      tolerance: 5,
      start: 8,
    },
  },
  {
    slug: 'area-and-perimeter',
    chapterId: 'mathematics.measurement-mensuration',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Area and perimeter',
    lab: 'area',
    formula: 'A = lw',
    scenario: 'a tarpaulin being cut to cover a damaged grain store',
    crisis: 'The store needs 252 m² of cover and the tarp is 14 m along its fixed edge. The cut width is wrong.',
    insight: 'Area is a product of two lengths, so it grows twice as fast as either one. Doubling both quadruples the area.',
    resolution: 'At the solved width the tarp covers exactly 252 m².',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 252, leftB: 1, rightA: 14, leftName: 'Area required', rightName: 'Length × width', productUnit: 'm²' },
      control: { label: 'Cut width', unit: 'm', min: 0, max: 40, precision: 2 },
      tolerance: 14,
      start: 92,
    },
  },
  {
    slug: 'volume-scaling',
    chapterId: 'mathematics.measurement-mensuration',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Volume scaling',
    lab: 'volume',
    formula: 'V = A_{base} h',
    scenario: 'a rainwater cistern being sized for a rooftop garden',
    crisis: 'The cistern must hold 1080 L and its base area is fixed at 72 dm². The planned height is wrong.',
    insight: 'Volume is area multiplied by height. Scaling every dimension by two multiplies volume by eight, not two.',
    resolution: 'At the solved height the cistern holds exactly 1080 L.',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 1080, leftB: 1, rightA: 72, leftName: 'Volume required', rightName: 'Base × height', productUnit: 'L' },
      control: { label: 'Cistern height', unit: 'dm', min: 0, max: 32, precision: 2 },
      tolerance: 58,
      start: 8,
    },
  },
  {
    slug: 'graph-interpretation',
    chapterId: 'mathematics.coordinate-graphs',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Graph interpretation',
    lab: 'coordinate',
    formula: 'y = f(x)',
    scenario: 'a clinic reading a dosage chart it cannot afford to misread',
    crisis: 'The chart rises 3.5 units of dose per kilogram of body mass. The prescribed dose is 91 units and the mass read off the axis is wrong.',
    insight: 'A graph is a picture of a relationship. Reading it means moving between the axes, not just looking at the line.',
    resolution: 'At the solved body mass the chart gives exactly the 91 unit dose.',
    model: {
      kind: 'proportional',
      params: { k: 3.5, targetY: 91, leftName: 'Charted dose', rightName: 'Prescribed dose', productUnit: 'units' },
      control: { label: 'Body mass', unit: 'kg', min: 0, max: 55, precision: 2 },
      tolerance: 4.8,
      start: 92,
    },
  },
  {
    slug: 'making-ten',
    chapterId: 'mathematics.number-sense',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 1,
    title: 'Making ten',
    lab: 'numberline',
    formula: '6 + x = 10',
    scenario: 'a bakery tray that has to leave with ten buns on it',
    crisis: 'Six buns are already on the tray and the delivery box holds exactly ten. The baker keeps guessing and the tray keeps going out short.',
    insight: 'Counting on from a number you already have is faster than starting again from one. The gap between what you have and what you need is the answer.',
    resolution: 'With the right number added, the tray holds ten and the box closes.',
    standardIds: ['cbse:1:1', 'ngss:K-2-PS1-1', 'uk:KS1:number'],
    model: {
      kind: 'sumToConstant',
      params: { known: 6, total: 10, leftName: 'Buns on the tray', rightName: 'Buns needed', productUnit: 'buns' },
      control: { label: 'Buns added', unit: 'buns', min: 0, max: 9, precision: 0 },
      tolerance: 0.4,
      start: 92,
    },
  },
  {
    slug: 'counting-pairs',
    chapterId: 'mathematics.number-sense',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 2,
    title: 'Counting in twos',
    lab: 'sequence',
    formula: '2 \\times x = 14',
    scenario: 'a shoe rack in a school corridor before a class trip',
    crisis: 'Fourteen shoes are on the rack and every child leaves exactly two. Nobody can agree how many children are already inside.',
    insight: 'When things always come in twos, counting the pairs is the same as halving the total. Skip counting is multiplication wearing a different coat.',
    resolution: 'At the right number of children, the pairs account for all fourteen shoes.',
    standardIds: ['cbse:2:2', 'uk:KS1:multiplication'],
    model: {
      kind: 'proportional',
      params: { k: 2, targetY: 14, leftName: 'Shoes on the rack', rightName: 'Shoes counted', productUnit: 'shoes' },
      control: { label: 'Children inside', unit: 'children', min: 0, max: 15, precision: 0 },
      tolerance: 0.6,
      start: 92,
    },
  },
  {
    slug: 'sharing-equally',
    chapterId: 'mathematics.number-sense',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 2,
    title: 'Sharing equally',
    lab: 'fraction',
    formula: '4 \\times x = 20',
    scenario: 'four friends splitting a bag of marbles on a school step',
    crisis: 'Twenty marbles have to be split four ways with none left over. Every attempt so far has left somebody short and an argument going.',
    insight: 'Sharing equally means every share is the same size. Four equal shares that use up twenty means each share is twenty divided by four.',
    resolution: 'At the right share size, all twenty marbles are used and every friend has the same number.',
    standardIds: ['cbse:2:4', 'uk:KS1:division'],
    model: {
      kind: 'proportional',
      params: { k: 4, targetY: 20, leftName: 'Marbles handed out', rightName: 'Marbles in the bag', productUnit: 'marbles' },
      control: { label: 'Marbles each', unit: 'marbles', min: 0, max: 12, precision: 0 },
      tolerance: 0.8,
      start: 92,
    },
  },
  {
    slug: 'place-value-carry',
    chapterId: 'mathematics.number-sense',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 3,
    title: 'Place value',
    lab: 'numberline',
    formula: '250 + x = 400',
    scenario: 'a school library counting books back onto the shelves',
    crisis: 'Two hundred and fifty books are shelved and the catalogue insists there are four hundred. The rest are still in crates in the corridor.',
    insight: 'Hundreds, tens and ones each hold their own column. Finding the gap means working column by column rather than guessing at the whole number.',
    resolution: 'With the missing count added, the shelves and the catalogue agree at four hundred.',
    standardIds: ['cbse:3:1', 'uk:KS2:place-value'],
    model: {
      kind: 'sumToConstant',
      params: { known: 250, total: 400, leftName: 'Books shelved', rightName: 'Catalogue total', productUnit: 'books' },
      control: { label: 'Books still in crates', unit: 'books', min: 0, max: 300, precision: 0 },
      tolerance: 6,
      start: 92,
    },
  },
  {
    slug: 'times-table-array',
    chapterId: 'mathematics.number-sense',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 3,
    title: 'Rows and columns',
    lab: 'area',
    formula: '6 \\times x = 42',
    scenario: 'a village hall laying out chairs for a prize evening',
    crisis: 'Forty-two chairs must go out in six equal rows. The caretaker has tried it twice by eye and the back row keeps ending up ragged.',
    insight: 'An array turns multiplication into a picture. Six rows of the same length covering forty-two chairs fixes the length of every row.',
    resolution: 'At the right row length, six rows use exactly forty-two chairs and the block is square-edged.',
    standardIds: ['cbse:3:5', 'uk:KS2:multiplication'],
    model: {
      kind: 'proportional',
      params: { k: 6, targetY: 42, leftName: 'Chairs laid out', rightName: 'Chairs available', productUnit: 'chairs' },
      control: { label: 'Chairs per row', unit: 'chairs', min: 0, max: 14, precision: 0 },
      tolerance: 1.6,
      start: 92,
    },
  },
  {
    slug: 'perimeter-fence',
    chapterId: 'mathematics.measurement-mensuration',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 4,
    title: 'Perimeter of a plot',
    lab: 'geometry',
    formula: '2(l + b) = P',
    scenario: 'a kitchen garden being fenced against rabbits',
    crisis: 'The plot is 9 m along one side and there are 44 m of fencing on the roll. The gardener has cut once already and does not want to cut wrong twice.',
    insight: 'Perimeter is the walk all the way round. A rectangle has two of each side, so the two unknown sides share whatever the two known ones leave.',
    resolution: 'At the solved width, the fence closes the loop with nothing spare and nothing short.',
    standardIds: ['cbse:4:11', 'uk:KS2:measurement'],
    model: {
      kind: 'sumToConstant',
      params: { known: 9, total: 22, leftName: 'Half the perimeter used', rightName: 'Half the fencing', productUnit: 'm' },
      control: { label: 'Plot width', unit: 'm', min: 0, max: 20, precision: 1 },
      tolerance: 0.5,
      start: 8,
    },
  },
  {
    slug: 'money-change',
    chapterId: 'mathematics.fractions-decimals',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 4,
    title: 'Counting change',
    lab: 'numberline',
    formula: '\\text{spent} + \\text{change} = \\text{paid}',
    scenario: 'a stationery counter at the start of a school term',
    crisis: 'A note worth 500 rupees went across the counter for goods costing 285. The till is disputing the change and the queue is growing.',
    insight: 'Change is what is left of what you handed over. Counting up from the price to the note is easier than subtracting downward.',
    resolution: 'At the correct change, the price and the change together account for the whole note.',
    standardIds: ['cbse:4:2', 'uk:KS2:money'],
    model: {
      kind: 'sumToConstant',
      params: { known: 285, total: 500, leftName: 'Price plus change', rightName: 'Note handed over', productUnit: '₹' },
      control: { label: 'Change returned', unit: '₹', min: 0, max: 400, precision: 0 },
      tolerance: 8,
      start: 8,
    },
  },
  {
    slug: 'equivalent-fractions',
    chapterId: 'mathematics.fractions-decimals',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 4,
    title: 'Equivalent fractions',
    lab: 'fraction',
    formula: '\\frac{3}{4} = \\frac{x}{20}',
    scenario: 'a pizza kitchen scaling a recipe from four slices to twenty',
    crisis: 'The old tray was cut into four and three parts were cheese. The new tray is cut into twenty and nobody knows how many parts to cover.',
    insight: 'Two fractions are equivalent when they describe the same amount of the whole. Cutting the tray into more pieces does not change how much cheese there is.',
    resolution: 'At the solved count, the twenty-piece tray carries exactly the same share as three quarters did.',
    standardIds: ['cbse:4:7', 'uk:KS2:fractions'],
    model: {
      kind: 'ratioMatch',
      params: { a: 4, b: 3, c: 20, leftName: 'Quarters scaled up', rightName: 'Twentieths needed', productUnit: 'parts' },
      control: { label: 'Cheese pieces', unit: 'pieces', min: 0, max: 20, precision: 0 },
      tolerance: 1.2,
      start: 8,
    },
  },
  {
    slug: 'decimal-place',
    chapterId: 'mathematics.fractions-decimals',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 5,
    title: 'Decimal addition',
    lab: 'numberline',
    formula: '1.35 + x = 2.00',
    scenario: 'a chemist weighing out a prescription on a digital balance',
    crisis: 'The pan reads 1.35 g and the prescription calls for exactly 2 g. Adding by eye keeps overshooting the second decimal place.',
    insight: 'A decimal point does not change how addition works, only which column counts as one. Tenths line up under tenths.',
    resolution: 'At the solved mass the balance settles on exactly 2.00 g.',
    standardIds: ['cbse:5:8', 'uk:KS2:decimals'],
    model: {
      kind: 'sumToConstant',
      params: { known: 1.35, total: 2, leftName: 'Mass on the pan', rightName: 'Prescribed mass', productUnit: 'g' },
      control: { label: 'Powder added', unit: 'g', min: 0, max: 1.2, precision: 2 },
      tolerance: 0.03,
      start: 8,
    },
  },
  {
    slug: 'average-score',
    chapterId: 'mathematics.data-statistics',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 5,
    title: 'Finding the average',
    lab: 'data',
    formula: '\\bar{x} = \\frac{\\sum x}{n}',
    scenario: 'a cricket coach picking an opener on batting average',
    crisis: 'Four innings are on the sheet — 32, 48, 21 and 39 — and the selector wants a five-innings average of exactly 36. The fifth innings has not been played.',
    insight: 'An average is the number every entry would be if the total were shared out evenly. Fixing the average fixes the total, and the total fixes the missing entry.',
    resolution: 'With that score in the fifth innings, the five-innings average lands on 36.',
    standardIds: ['cbse:5:12', 'uk:KS2:statistics'],
    model: {
      kind: 'mean',
      params: { samples: [32, 48, 21, 39], targetMean: 36, leftName: 'Average so far', rightName: 'Target average', productUnit: 'runs' },
      control: { label: 'Fifth innings score', unit: 'runs', min: 0, max: 90, precision: 0 },
      tolerance: 0.9,
      start: 92,
    },
  },
  {
    slug: 'area-of-rectangle',
    chapterId: 'mathematics.measurement-mensuration',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 5,
    title: 'Area of a floor',
    lab: 'area',
    formula: 'A = l \\times b',
    scenario: 'a classroom being retiled over a weekend',
    crisis: 'The room is 7 m long and the order slip says 56 square metres of tile. The width on the plan has been smudged illegible.',
    insight: 'Area counts the squares that fit inside, not the distance round the edge. Length times width is a shortcut for counting every square.',
    resolution: 'At the solved width the floor is exactly 56 square metres and the tile order is right.',
    standardIds: ['cbse:5:11', 'uk:KS2:area'],
    model: {
      kind: 'proportional',
      params: { k: 7, targetY: 56, leftName: 'Floor area', rightName: 'Tiles ordered', productUnit: 'm²' },
      control: { label: 'Room width', unit: 'm', min: 0, max: 16, precision: 1 },
      tolerance: 1.4,
      start: 92,
    },
  },
  {
    slug: 'map-scale',
    chapterId: 'mathematics.ratio-proportion',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 5,
    title: 'Reading a map scale',
    lab: 'coordinate',
    formula: '1 : 50000',
    scenario: 'a trekking group planning a day walk from a paper map',
    crisis: 'The map scale is 1 cm to 500 m, and the group is carrying water for a 7000 m walk and no further. Nobody knows how long that route is allowed to be on the paper.',
    insight: 'A scale is a ratio between two lengths, one on paper and one on the ground. Every centimetre carries the same fixed number of metres.',
    resolution: 'At the solved ground distance, the paper measurement and the scale agree.',
    standardIds: ['cbse:5:10', 'uk:KS2:ratio'],
    model: {
      kind: 'proportional',
      params: { k: 500, targetY: 7000, leftName: 'Ground distance', rightName: 'Route length', productUnit: 'm' },
      control: { label: 'Map distance', unit: 'cm', min: 0, max: 30, precision: 1 },
      tolerance: 140,
      start: 92,
    },
  },
  {
    slug: 'odd-and-even',
    chapterId: 'mathematics.number-sense',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 1,
    title: 'Odd and even',
    lab: 'sequence',
    formula: '2n = \\text{even}',
    scenario: 'a classroom pairing up for a partner game',
    crisis: 'The teacher needs every child in a pair with nobody left standing, and twenty-six children are on the register today.',
    insight: 'A number is even when it splits into two equal groups with nothing over. Pairing is the test, not a rule to memorise.',
    resolution: 'At the solved number of pairs every child has a partner.',
    standardIds: ['cbse:1:2', 'uk:KS1:number'],
    model: {
      kind: 'proportional',
      params: { k: 2, targetY: 26, leftName: 'Children paired', rightName: 'Children present', productUnit: 'children' },
      control: { label: 'Pairs formed', unit: 'pairs', min: 0, max: 26, precision: 0 },
      tolerance: 1.4,
      start: 92,
    },
  },
  {
    slug: 'skip-counting-fives',
    chapterId: 'mathematics.number-sense',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 2,
    title: 'Counting in fives',
    lab: 'numberline',
    formula: '5n = 45',
    scenario: 'a tuck shop counting five-rupee coins into a bag',
    crisis: 'The bag has to hold forty-five rupees in five-rupee coins exactly. The shopkeeper keeps losing count partway.',
    insight: 'Counting in fives jumps along the number line in equal strides. The number of strides is what you are really after.',
    resolution: 'At the solved coin count the bag holds exactly forty-five rupees.',
    standardIds: ['cbse:2:3', 'uk:KS1:multiplication'],
    model: {
      kind: 'proportional',
      params: { k: 5, targetY: 45, leftName: 'Value in the bag', rightName: 'Target value', productUnit: '₹' },
      control: { label: 'Coins', unit: 'coins', min: 0, max: 20, precision: 0 },
      tolerance: 2.4,
      start: 92,
    },
  },
  {
    slug: 'unit-conversion-length',
    chapterId: 'mathematics.measurement-mensuration',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 4,
    title: 'Metres and centimetres',
    lab: 'numberline',
    formula: '1\\,\\text{m} = 100\\,\\text{cm}',
    scenario: 'a tailor cutting cloth from a bolt marked in metres',
    crisis: 'The order is written as 350 cm and the bolt is marked only in metres. The last cut was made on a guess and came out short.',
    insight: 'Changing units does not change the length, only the number you write down. Smaller units always give a bigger number.',
    resolution: 'At the solved metre reading the cut matches the order exactly.',
    standardIds: ['cbse:4:10', 'uk:KS2:measurement'],
    model: {
      kind: 'proportional',
      params: { k: 100, targetY: 350, leftName: 'Length in cm', rightName: 'Order length', productUnit: 'cm' },
      control: { label: 'Cloth cut', unit: 'm', min: 0, max: 8, precision: 2 },
      tolerance: 33,
      start: 92,
    },
  },
  {
    slug: 'percentage-discount',
    chapterId: 'mathematics.fractions-decimals',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 7,
    title: 'Percentage discount',
    lab: 'fraction',
    formula: '\\text{price} \\times (1 - d) = \\text{sale}',
    scenario: 'a shop repricing stock for an end-of-season sale',
    crisis: 'A jacket marked at 2 400 rupees has to ring up at 1 800 at the till. The discount entered into the register is wrong.',
    insight: 'A percentage is a fraction of the original, not a fixed amount. The same percentage takes more off a dearer item.',
    resolution: 'At the solved discount the till rings the jacket at exactly the sale price.',
    standardIds: ['cbse:7:8', 'uk:KS3:percentages'],
    model: {
      kind: 'proportional',
      params: { k: 24, targetY: 600, leftName: 'Amount taken off', rightName: 'Required reduction', productUnit: '₹' },
      control: { label: 'Discount', unit: '%', min: 0, max: 60, precision: 1 },
      tolerance: 55,
      start: 92,
    },
  },
  {
    slug: 'simple-interest',
    chapterId: 'mathematics.ratio-proportion',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 7,
    title: 'Simple interest',
    lab: 'coordinate',
    formula: 'I = \\frac{PRT}{100}',
    scenario: 'a cooperative bank quoting a smallholder on a seasonal loan',
    crisis: 'The principal is 40 000 rupees over 2 years and the interest quoted comes to 7 200. The rate written on the slip does not produce that figure.',
    insight: 'Simple interest grows with principal, rate and time in equal measure. Doubling any one of the three doubles the interest.',
    resolution: 'At the solved rate the interest works out to exactly the quoted figure.',
    standardIds: ['cbse:7:8', 'icse:7:commercial-mathematics'],
    model: {
      kind: 'proportional',
      params: { k: 800, targetY: 7200, leftName: 'Interest accrued', rightName: 'Quoted interest', productUnit: '₹' },
      control: { label: 'Interest rate', unit: '%', min: 0, max: 20, precision: 2 },
      tolerance: 680,
      start: 92,
    },
  },
  {
    slug: 'angle-sum-triangle',
    chapterId: 'mathematics.geometry-shape',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 7,
    title: 'Angles in a triangle',
    lab: 'geometry',
    formula: '\\alpha + \\beta + \\gamma = 180°',
    scenario: 'a roof truss being set out on the workshop floor',
    crisis: 'Two of the truss angles are cut at 52° and 61°. The third has been marked by eye and the frame will not close.',
    insight: 'The three angles of any triangle always add to a straight angle. Fixing two of them leaves no choice about the third.',
    resolution: 'At the solved angle the truss closes cleanly with no gap at the apex.',
    standardIds: ['cbse:7:6', 'uk:KS3:geometry'],
    model: {
      kind: 'sumToConstant',
      params: { known: 113, total: 180, leftName: 'Angles so far', rightName: 'Straight angle', productUnit: '°' },
      control: { label: 'Third angle', unit: '°', min: 0, max: 120, precision: 1 },
      tolerance: 3.4,
      start: 8,
    },
  },
  {
    slug: 'circle-circumference',
    chapterId: 'mathematics.measurement-mensuration',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 7,
    title: 'Circumference of a wheel',
    lab: 'circle',
    formula: 'C = 2\\pi r',
    scenario: 'a cycle shop calibrating a distance meter to a wheel',
    crisis: 'The meter counts revolutions and expects 2.198 m per turn. The wheel radius entered into the setup screen is wrong.',
    insight: 'Circumference grows in direct proportion to radius, with pi as the fixed constant of that proportion.',
    resolution: 'At the solved radius each revolution covers exactly the distance the meter assumes.',
    standardIds: ['cbse:7:11', 'igcse:4.1'],
    model: {
      kind: 'proportional',
      params: { k: 6.2832, targetY: 2.198, leftName: 'Distance per turn', rightName: 'Meter setting', productUnit: 'm' },
      control: { label: 'Wheel radius', unit: 'm', min: 0, max: 0.8, precision: 3 },
      tolerance: 0.2,
      start: 92,
    },
  },
  {
    slug: 'linear-equation-solve',
    chapterId: 'mathematics.algebra-equations',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Solving for x',
    lab: 'balance',
    formula: '7x + 19 = 96',
    scenario: 'a courier pricing a route with a fixed pickup charge',
    crisis: 'Every kilometre costs 7 rupees on top of a flat 19 rupee pickup, and the invoice reads 96 rupees. The distance logged is disputed.',
    insight: 'An equation is a balance. Whatever you do to one side you must do to the other, and the unknown is what survives.',
    resolution: 'At the solved distance the invoice works out to exactly 96 rupees.',
    standardIds: ['cbse:8:2', 'uk:KS3:algebra'],
    model: {
      kind: 'sumToConstant',
      params: { known: 19, total: 96, leftName: 'Invoice total', rightName: 'Invoice shown', productUnit: '₹' },
      control: { label: 'Distance charge', unit: '₹', min: 0, max: 140, precision: 1 },
      tolerance: 3.5,
      start: 8,
    },
  },
  {
    slug: 'pythagoras-ladder',
    chapterId: 'mathematics.geometry-shape',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 9,
    title: 'Ladder against a wall',
    lab: 'triangle',
    formula: 'a^2 + b^2 = c^2',
    scenario: 'a painter setting a ladder to a safe angle against a wall',
    crisis: 'The ladder is 13 m long and its foot must stand 5 m out from the wall. The reach up the wall has been guessed and the top is short of the gutter.',
    insight: 'In a right triangle the two shorter sides square to the longest. Nothing about the ladder is free once two lengths are fixed.',
    resolution: 'At the solved height the ladder reaches exactly the gutter with its foot correctly placed.',
    standardIds: ['cbse:9:6', 'icse:9:pythagoras', 'igcse:4.2'],
    model: {
      kind: 'pythagoras',
      params: { known: 5, hypotenuse: 13, leftName: 'Ladder span', rightName: 'Ladder length', productUnit: 'm' },
      control: { label: 'Reach up the wall', unit: 'm', min: 0, max: 18, precision: 2 },
      tolerance: 0.55,
      start: 8,
    },
  },
  {
    slug: 'probability-spinner',
    chapterId: 'mathematics.data-statistics',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Expected outcomes',
    lab: 'probability',
    formula: 'E = np',
    scenario: 'a school fete pricing a spinning-wheel stall',
    crisis: 'The wheel is spun 240 times across the afternoon and the stall has budgeted for 30 winning spins. The winning sector has been cut to the wrong size.',
    insight: 'Expectation is the count multiplied by the chance of each. It predicts the long run, never any single spin.',
    resolution: 'At the solved probability the expected wins land exactly on the budget.',
    standardIds: ['cbse:8:5', 'uk:KS3:probability'],
    model: {
      kind: 'proportional',
      params: { k: 240, targetY: 30, leftName: 'Expected wins', rightName: 'Budgeted wins', productUnit: 'wins' },
      control: { label: 'Winning chance', unit: '', min: 0, max: 0.4, precision: 3 },
      tolerance: 2.8,
      start: 92,
    },
  },
  {
    slug: 'volume-of-tank',
    chapterId: 'mathematics.measurement-mensuration',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 9,
    title: 'Volume of a cylinder',
    lab: 'volume',
    formula: 'V = \\pi r^2 h',
    scenario: 'a dairy sizing a cylindrical chilling vat',
    crisis: 'The vat floor is fixed at 3.14 m² and the plant needs 6.28 m³ of capacity. The wall height ordered from the fabricator is wrong.',
    insight: 'Volume is base area multiplied by height. Widening a tank buys capacity far faster than raising it, because area goes as radius squared.',
    resolution: 'At the solved height the vat holds exactly the capacity the plant requires.',
    standardIds: ['cbse:9:13', 'igcse:4.4'],
    model: {
      kind: 'proportional',
      params: { k: 3.14, targetY: 6.28, leftName: 'Vat capacity', rightName: 'Required capacity', productUnit: 'm³' },
      control: { label: 'Vat height', unit: 'm', min: 0, max: 5, precision: 2 },
      tolerance: 0.6,
      start: 92,
    },
  },
  {
    slug: 'coordinate-gradient',
    chapterId: 'mathematics.coordinate-graphs',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Gradient of a line',
    lab: 'coordinate',
    formula: 'm = \\frac{y_2 - y_1}{x_2 - x_1}',
    scenario: 'a surveyor setting the fall on a drainage run',
    crisis: 'The run covers 24 m horizontally and the code demands a gradient of 0.025. The fall pegged at the far end does not match.',
    insight: 'Gradient is rise over run. A shallow gradient over a long run still adds up to a real drop.',
    resolution: 'At the solved fall the drainage run sits exactly on the code gradient.',
    standardIds: ['cbse:10:7', 'igcse:3.2'],
    model: {
      kind: 'proportional',
      params: { k: 40, targetY: 24, leftName: 'Run implied', rightName: 'Actual run', productUnit: 'm' },
      control: { label: 'Fall over the run', unit: 'm', min: 0, max: 1.4, precision: 3 },
      tolerance: 2.2,
      start: 92,
    },
  },
  {
    slug: 'doubling-and-halving',
    chapterId: 'mathematics.number-sense',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 2,
    title: 'Doubling',
    lab: 'fraction',
    formula: '2n = 36',
    scenario: 'a kitchen doubling a recipe for a family gathering',
    crisis: 'The doubled batch has to come to thirty-six rotis and the original recipe card has been mislaid.',
    insight: 'Doubling means two equal groups. Working backwards from the double is the same as splitting it in half.',
    resolution: 'At the solved original count, doubling the recipe gives exactly thirty-six.',
    standardIds: ['cbse:2:3', 'uk:KS1:number'],
    model: {
      kind: 'proportional',
      params: { k: 2, targetY: 36, leftName: 'Doubled batch', rightName: 'Required batch', productUnit: 'rotis' },
      control: { label: 'Original recipe', unit: 'rotis', min: 0, max: 40, precision: 0 },
      tolerance: 2.2,
      start: 92,
    },
  },
  {
    slug: 'symmetry-fold',
    chapterId: 'mathematics.geometry-shape',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 3,
    title: 'Lines of symmetry',
    lab: 'mirror',
    formula: 'l = r',
    scenario: 'a rangoli being completed from one half of a drawn pattern',
    crisis: 'The left half is already chalked in and the finished pattern has to be symmetrical about the centre line. The right half is still bare and the count has not been read off.',
    insight: 'A line of symmetry means one half is the mirror of the other. Every mark on one side has exactly one partner.',
    resolution: 'At the solved count both halves match and the pattern reads as symmetrical.',
    standardIds: ['cbse:3:7', 'uk:KS2:geometry'],
    model: {
      kind: 'fluxBalance',
      params: { outside: 24, leftName: 'Right half marks', rightName: 'Left half marks', productUnit: 'marks' },
      control: { label: 'Right half marks', unit: 'marks', min: 0, max: 50, precision: 0 },
      tolerance: 1.4,
      start: 92,
    },
  },
  {
    slug: 'bar-chart-total',
    chapterId: 'mathematics.data-statistics',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 4,
    title: 'Reading a bar chart',
    lab: 'data',
    formula: '\\sum b = T',
    scenario: 'a class chart of favourite fruits with one bar unlabelled',
    crisis: 'Thirty-two children voted and the four labelled bars account for 25 of them. The fifth bar has no figure written on it.',
    insight: 'Every reading on a chart is part of one whole. The bars must always add back to the total surveyed.',
    resolution: 'At the solved height the five bars account for all thirty-two votes.',
    standardIds: ['cbse:4:13', 'uk:KS2:statistics'],
    model: {
      kind: 'sumToConstant',
      params: { known: 25, total: 32, leftName: 'Votes charted', rightName: 'Votes cast', productUnit: 'votes' },
      control: { label: 'Fifth bar', unit: 'votes', min: 0, max: 30, precision: 0 },
      tolerance: 0.9,
      start: 92,
    },
  },
  {
    slug: 'scale-model-bridge',
    chapterId: 'mathematics.ratio-proportion',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 7,
    title: 'Scale models',
    lab: 'area',
    formula: '\\frac{a}{b} = \\frac{c}{d}',
    scenario: 'an engineering fair building a scale model of a river bridge',
    crisis: 'The real bridge spans 96 m and the model is built at 1 cm to 8 m. The deck length cut for the model does not match the scale.',
    insight: 'A scale model keeps every ratio the same. One fixed factor links every real length to its model counterpart.',
    resolution: 'At the solved model length the deck sits exactly at the stated scale.',
    standardIds: ['cbse:7:12', 'igcse:4.1'],
    model: {
      kind: 'ratioMatch',
      params: { a: 8, b: 1, c: 96, leftName: 'Scaled model length', rightName: 'Real span scaled', productUnit: 'cm' },
      control: { label: 'Model deck length', unit: 'cm', min: 0, max: 26, precision: 1 },
      tolerance: 9,
      start: 92,
    },
  },
];

export default mathematics;
