/**
 * Physics missions.
 *
 * Every entry carries its own equation, its own real quantities, and its own
 * story. The balance point is solved from the equation — never picked to look
 * plausible — so tuning the control is genuinely doing the physics.
 */

const physics = [
  {
    slug: 'torque-balance',
    chapterId: 'physics.forces-motion',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Torque balance',
    lab: 'lever',
    formula: '\\tau_1 = \\tau_2 \\;\\Rightarrow\\; F_1 d_1 = F_2 d_2',
    scenario: 'a cargo crane leaning over a flooded rail yard',
    crisis: 'The jib is holding a 12 kN pallet 1.8 m out from the pivot, and the counterweight is parked in the wrong slot. The whole arm is creeping downward.',
    insight: 'A pivot does not care about force alone. It cares about force multiplied by distance. A small counterweight far out can hold a large load close in.',
    resolution: 'With the counterweight at the solved distance, both moments about the pivot are equal and the jib stops moving.',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 12, leftB: 1.8, rightA: 9, leftName: 'Load moment', rightName: 'Counter moment', productUnit: 'kN·m' },
      control: { label: 'Counterweight distance', unit: 'm', min: 0.5, max: 4, precision: 2 },
      tolerance: 0.9,
      start: 12,
    },
  },
  {
    slug: 'lever-arms',
    chapterId: 'physics.forces-motion',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Lever arms',
    lab: 'lever',
    formula: 'F_1 d_1 = F_2 d_2',
    scenario: 'a field workshop lifting a generator with a scaffold pole',
    crisis: 'Two students can push with 15 N. The generator resists with 45 N acting 0.4 m from the fulcrum. Right now the pole is too short to help.',
    insight: 'Moving the effort further from the fulcrum multiplies it. The lever does not create energy — it trades distance for force.',
    resolution: 'At the solved effort arm, 15 N does the work of 45 N and the generator lifts clear.',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 45, leftB: 0.4, rightA: 15, leftName: 'Load moment', rightName: 'Effort moment', productUnit: 'N·m' },
      control: { label: 'Effort arm length', unit: 'm', min: 0.2, max: 2.2, precision: 2 },
      tolerance: 0.8,
      start: 88,
    },
  },
  {
    slug: 'center-of-mass',
    chapterId: 'physics.forces-motion',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Center of mass',
    lab: 'lever',
    formula: 'm_1 x_1 = m_2 x_2',
    scenario: 'a rescue plank bridging a collapsed stairwell',
    crisis: 'A 3 kg toolbag sits 0.8 m left of the support. A 2 kg medical kit must go somewhere on the right, and the plank tips the moment the balance is wrong.',
    insight: 'The balance point is where mass-times-distance matches on both sides. Lighter objects simply have to sit further out.',
    resolution: 'Placed at the solved distance, the combined center of mass sits exactly over the support.',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 3, leftB: 0.8, rightA: 2, leftName: 'Left moment', rightName: 'Right moment', productUnit: 'kg·m' },
      control: { label: 'Medical kit distance', unit: 'm', min: 0.2, max: 2.4, precision: 2 },
      tolerance: 0.15,
      start: 8,
    },
  },
  {
    slug: 'static-friction',
    chapterId: 'physics.forces-motion',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Static friction',
    lab: 'friction',
    formula: 'F_f = \\mu_s N',
    scenario: 'a loading ramp where crates keep sliding on wet steel',
    crisis: 'The grip coefficient is 0.35 and the crate needs 28 N of friction to stay put. Not enough weight is pressing it down.',
    insight: 'Friction is not a fixed property of a surface. It scales with how hard the surfaces are pushed together.',
    resolution: 'At the solved normal force, available friction exactly meets the 28 N the crate needs.',
    model: {
      kind: 'proportional',
      params: { k: 0.35, targetY: 28, leftName: 'Available friction', rightName: 'Required friction', productUnit: 'N' },
      control: { label: 'Normal force', unit: 'N', min: 20, max: 140, precision: 0 },
      tolerance: 1.2,
      start: 15,
    },
  },
  {
    slug: 'newtons-first-law',
    chapterId: 'physics.forces-motion',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: "Newton's first law",
    lab: 'force',
    formula: '\\sum F = 0',
    scenario: 'a cable car stalled halfway across a gorge',
    crisis: 'Drag and cable friction pull backwards with 180 N. The drive motor is applying the wrong thrust, so the car keeps drifting instead of holding station.',
    insight: 'Constant velocity does not need zero force. It needs forces that cancel. Balanced does not mean nothing is happening.',
    resolution: 'With thrust matched to resistance, the net force is zero and the car holds its position exactly.',
    model: {
      kind: 'proportional',
      params: { k: 1, targetY: 180, leftName: 'Applied thrust', rightName: 'Total resistance', productUnit: 'N' },
      control: { label: 'Motor thrust', unit: 'N', min: 0, max: 400, precision: 0 },
      tolerance: 12,
      start: 90,
    },
  },
  {
    slug: 'newtons-second-law',
    chapterId: 'physics.forces-motion',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: "Newton's second law",
    lab: 'force',
    formula: 'F = ma',
    scenario: 'a magnetic launch sled on a test track',
    crisis: 'The 6.5 kg sled must leave the rail carrying exactly 91 N of drive force, but the acceleration setpoint is wrong.',
    insight: 'Force, mass, and acceleration are locked together. Fix any two and the third is decided for you.',
    resolution: 'At the solved acceleration the drive force lands on 91 N and the sled clears the rail cleanly.',
    model: {
      kind: 'proportional',
      params: { k: 6.5, targetY: 91, leftName: 'Drive force', rightName: 'Required force', productUnit: 'N' },
      control: { label: 'Acceleration setpoint', unit: 'm/s²', min: 0, max: 30, precision: 1 },
      tolerance: 4,
      start: 85,
    },
  },
  {
    slug: 'momentum-transfer',
    chapterId: 'physics.forces-motion',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Momentum transfer',
    lab: 'collision',
    formula: 'p = mv',
    scenario: 'a docking clamp catching a drifting supply pod',
    crisis: 'The clamp absorbs at most 8.4 kg·m/s. The 1.4 kg pod is closing too fast and will bounce off instead of latching.',
    insight: 'Momentum is mass carried by speed. A light object moving fast can hit as hard as a heavy one drifting slowly.',
    resolution: 'Slowed to the solved approach speed, the pod arrives with exactly the momentum the clamp can absorb.',
    model: {
      kind: 'proportional',
      params: { k: 1.4, targetY: 8.4, leftName: 'Pod momentum', rightName: 'Clamp limit', productUnit: 'kg·m/s' },
      control: { label: 'Approach speed', unit: 'm/s', min: 0, max: 14, precision: 2 },
      tolerance: 0.5,
      start: 92,
    },
  },
  {
    slug: 'energy-conservation',
    chapterId: 'physics.energy-work',
    difficulty: 'Foundation',
    gradeGroup: 'middle',
    gradeLevel: 6,
    title: 'Energy conservation',
    lab: 'energy',
    formula: 'E_T = E_k + E_p',
    scenario: 'a gravity-fed water tower feeding an emergency turbine',
    crisis: 'The system holds 500 J in total. Stored height energy accounts for 320 J. The kinetic reading is drifting and the turbine is stalling.',
    insight: 'Energy is not created at the turbine. It is traded — height energy converts into motion energy, and the total never changes.',
    resolution: 'At the solved kinetic value the two forms sum to the full 500 J and the turbine runs steady.',
    model: {
      kind: 'sumToConstant',
      params: { known: 320, total: 500, leftName: 'Total accounted', rightName: 'System energy', productUnit: 'J' },
      control: { label: 'Kinetic energy', unit: 'J', min: 0, max: 400, precision: 0 },
      tolerance: 12,
      start: 8,
    },
  },
  {
    slug: 'power-networks',
    chapterId: 'physics.electricity-magnetism',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Power networks',
    lab: 'circuit',
    formula: 'P = VI',
    scenario: 'a field hospital running on a single generator line',
    crisis: 'The ward needs 300 W delivered at 2.5 A. The supply voltage is set wrong and the lights keep browning out.',
    insight: 'Power is voltage and current together. Halving the voltage at fixed current halves the power delivered.',
    resolution: 'At the solved supply voltage the line delivers exactly 300 W and the ward stabilises.',
    model: {
      kind: 'proportional',
      params: { k: 2.5, targetY: 300, leftName: 'Delivered power', rightName: 'Ward demand', productUnit: 'W' },
      control: { label: 'Supply voltage', unit: 'V', min: 20, max: 220, precision: 0 },
      tolerance: 14,
      start: 10,
    },
  },
  {
    slug: 'series-circuits',
    chapterId: 'physics.electricity-magnetism',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Series circuits',
    lab: 'circuit',
    formula: 'R_T = R_1 + R_2',
    scenario: 'a signal repeater that keeps burning out its driver',
    crisis: 'The driver survives only if the loop presents 320 Ω. One fixed resistor gives 180 Ω. The second is set wrong.',
    insight: 'In a single loop there is one path, so resistances simply add. Every extra component makes the current smaller.',
    resolution: 'With the second resistor at the solved value the loop totals 320 Ω and the driver runs cool.',
    model: {
      kind: 'sumToConstant',
      params: { known: 180, total: 320, leftName: 'Loop resistance', rightName: 'Safe resistance', productUnit: 'Ω' },
      control: { label: 'Second resistor', unit: 'Ω', min: 0, max: 300, precision: 0 },
      tolerance: 9,
      start: 90,
    },
  },
  {
    slug: 'parallel-circuits',
    chapterId: 'physics.electricity-magnetism',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Parallel circuits',
    lab: 'circuit',
    formula: '\\frac{1}{R_T} = \\frac{1}{R_1} + \\frac{1}{R_2}',
    scenario: 'a rover heater bank drawing from one battery bus',
    crisis: 'The bus needs to see 48 Ω combined. One heater element is fixed at 120 Ω. The second element is misconfigured.',
    insight: 'Parallel paths give current more ways through, so the combined resistance is always smaller than either branch alone.',
    resolution: 'At the solved second-branch value the pair combine to 48 Ω and the heater bank draws its designed current.',
    model: {
      kind: 'reciprocalSum',
      params: { known: 120, combined: 48, leftName: 'Combined resistance', rightName: 'Bus requirement', productUnit: 'Ω' },
      control: { label: 'Second branch', unit: 'Ω', min: 20, max: 180, precision: 0 },
      tolerance: 1.5,
      start: 88,
    },
  },
  {
    slug: 'voltage-loops',
    chapterId: 'physics.electricity-magnetism',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Voltage loops',
    lab: 'circuit',
    formula: '\\sum V = 0',
    scenario: 'a battery bank feeding a comms mast',
    crisis: 'The 9.0 V source must be fully accounted for around the loop. Known drops total 5.4 V, leaving one unmeasured component.',
    insight: 'Walk any closed loop and the voltage you gain must equal the voltage you lose. Energy cannot vanish partway round.',
    resolution: 'At the solved drop the loop closes on zero and the mast holds a clean signal.',
    model: {
      kind: 'sumToConstant',
      params: { known: 5.4, total: 9, leftName: 'Accounted drops', rightName: 'Source EMF', productUnit: 'V' },
      control: { label: 'Unknown component drop', unit: 'V', min: 0, max: 9, precision: 2 },
      tolerance: 0.3,
      start: 92,
    },
  },
  {
    slug: 'magnetic-flux',
    chapterId: 'physics.electricity-magnetism',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Magnetic flux',
    lab: 'magnet',
    formula: '\\Phi_B = BA',
    scenario: 'an induction charging pad under a hospital trolley',
    crisis: 'The 0.04 m² receiver coil needs 0.012 Wb of flux to charge. The field strength is set too low to couple.',
    insight: 'Flux counts field lines through an area. A weak field over a wide loop can carry the same flux as a strong field over a narrow one.',
    resolution: 'At the solved field strength the coil sees exactly 0.012 Wb and charging begins.',
    model: {
      kind: 'proportional',
      params: { k: 0.04, targetY: 0.012, leftName: 'Coil flux', rightName: 'Required flux', productUnit: 'Wb' },
      control: { label: 'Field strength', unit: 'T', min: 0, max: 0.8, precision: 3 },
      tolerance: 0.0011,
      start: 8,
    },
  },
  {
    slug: 'electromagnet-strength',
    chapterId: 'physics.electricity-magnetism',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Electromagnet strength',
    lab: 'magnet',
    formula: 'B \\propto NI',
    scenario: 'a scrapyard lifting magnet that keeps dropping its load',
    crisis: 'Holding the load needs 0.32 T. Each turn of the coil contributes 0.0008 T at the working current, and the winding count is wrong.',
    insight: 'More turns means more field for the same current. The coil multiplies the current’s magnetic effect.',
    resolution: 'At the solved turn count the magnet reaches 0.32 T and holds the load without slipping.',
    model: {
      kind: 'proportional',
      params: { k: 0.0008, targetY: 0.32, leftName: 'Field produced', rightName: 'Field required', productUnit: 'T' },
      control: { label: 'Coil turns', unit: 'turns', min: 0, max: 900, precision: 0 },
      tolerance: 0.02,
      start: 90,
    },
  },
  {
    slug: 'wave-frequency',
    chapterId: 'physics.waves-sound',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Wave frequency',
    lab: 'wave',
    formula: 'v = f\\lambda',
    scenario: 'a sonar buoy searching a channel for a sunken hull',
    crisis: 'Sound travels this water at 340 m/s and the array is tuned to a 1.7 m wavelength. The transmit frequency does not match, so nothing returns.',
    insight: 'Speed, frequency and wavelength are one relationship. Fix the medium and choosing a frequency chooses the wavelength.',
    resolution: 'At the solved frequency the wave travels at exactly 340 m/s and the array locks on.',
    model: {
      kind: 'waveSpeed',
      params: { speed: 340, wavelength: 1.7, leftName: 'Wave speed', rightName: 'Medium speed', productUnit: 'm/s' },
      control: { label: 'Transmit frequency', unit: 'Hz', min: 20, max: 450, precision: 0 },
      tolerance: 20,
      start: 90,
    },
  },
  {
    slug: 'refraction-paths',
    chapterId: 'physics.light-optics',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Refraction paths',
    lab: 'lens',
    formula: 'n_1\\sin\\theta_1 = n_2\\sin\\theta_2',
    scenario: 'a laser survey line entering a flooded tunnel',
    crisis: 'The beam must leave the water at 32° to hit the far marker. Water is 1.33, air is 1.00, and the incoming angle is wrong.',
    insight: 'Light bends because it changes speed. The denser medium always holds the ray closer to the normal.',
    resolution: 'At the solved incident angle the beam refracts onto exactly 32° and strikes the marker.',
    model: {
      kind: 'snell',
      params: { n1: 1, n2: 1.33, theta2: 32, leftName: 'Incident side', rightName: 'Exit side', productUnit: '' },
      control: { label: 'Incident angle', unit: '°', min: 0, max: 85, precision: 1 },
      tolerance: 0.028,
      start: 12,
    },
  },
  {
    slug: 'convex-lenses',
    chapterId: 'physics.light-optics',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Convex lenses',
    lab: 'lens',
    formula: '\\frac{1}{f} = \\frac{1}{d_o} + \\frac{1}{d_i}',
    scenario: 'a projector rebuilt from salvage for a night briefing',
    crisis: 'The lens has a 12 cm focal length and the slide sits 30 cm away, but the screen distance is wrong and the image is a blur.',
    insight: 'Object distance and image distance trade against each other around a fixed focal length. Move one and the other must follow.',
    resolution: 'At the solved image distance the lens equation closes and the projection snaps into focus.',
    model: {
      kind: 'reciprocalSum',
      params: { known: 30, combined: 12, leftName: 'Lens equation', rightName: 'Focal length', productUnit: 'cm' },
      control: { label: 'Screen distance', unit: 'cm', min: 5, max: 60, precision: 1 },
      tolerance: 0.8,
      start: 82,
    },
  },
  {
    slug: 'mirror-angles',
    chapterId: 'physics.light-optics',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Mirror angles',
    lab: 'mirror',
    formula: '\\theta_i = \\theta_r',
    scenario: 'a periscope relay assembled to see over a debris wall',
    crisis: 'The reflected ray must leave at 38° to reach the second mirror. The incoming angle is set wrong and the image misses entirely.',
    insight: 'A flat mirror does one thing perfectly: it sends light out at the same angle it came in, measured from the normal.',
    resolution: 'At the solved incident angle the reflection lands on 38° and the relay completes.',
    model: {
      kind: 'proportional',
      params: { k: 1, targetY: 38, leftName: 'Incident angle', rightName: 'Required reflection', productUnit: '°' },
      control: { label: 'Incident angle', unit: '°', min: 0, max: 80, precision: 1 },
      tolerance: 2,
      start: 92,
    },
  },
  {
    slug: 'sound-resonance',
    chapterId: 'physics.waves-sound',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Sound resonance',
    lab: 'wave',
    formula: 'f_1 = \\frac{v}{2L}',
    scenario: 'a warning horn being tuned before a storm front arrives',
    crisis: 'The horn must sound its fundamental at 140 Hz. Sound moves at 343 m/s in this air, and the tube length is wrong.',
    insight: 'A pipe picks the note. Its length sets which wavelength fits, and the medium speed turns that into a frequency.',
    resolution: 'At the solved tube length the fundamental lands on 140 Hz and the horn carries across the valley.',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 343, leftB: 1, rightA: 280, leftName: 'Wave speed', rightName: 'Tube response', productUnit: 'm/s' },
      control: { label: 'Tube length', unit: 'm', min: 0.2, max: 2.4, precision: 2 },
      tolerance: 16,
      start: 88,
    },
  },
  {
    slug: 'pressure-systems',
    chapterId: 'physics.pressure-fluids',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Pressure systems',
    lab: 'hydraulic',
    formula: 'P = \\frac{F}{A}',
    scenario: 'an ice-shelf research hut resting on soft snow',
    crisis: 'The hut presses down with 4500 N. The snow collapses above 18 kPa, and the current footing area is far too small.',
    insight: 'The same weight can be safe or destructive depending on the area it acts over. Spreading load lowers pressure.',
    resolution: 'At the solved footing area the pressure drops to exactly 18 kPa and the snow holds.',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 4500, leftB: 1, rightA: 18000, leftName: 'Applied force', rightName: 'Pressure × area', productUnit: 'N' },
      control: { label: 'Footing area', unit: 'm²', min: 0.05, max: 0.5, precision: 3 },
      tolerance: 250,
      start: 6,
    },
  },
  {
    slug: 'hydraulic-lifts',
    chapterId: 'physics.pressure-fluids',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Hydraulic lifts',
    lab: 'hydraulic',
    formula: '\\frac{F_1}{A_1} = \\frac{F_2}{A_2}',
    scenario: 'a workshop jack lifting a collapsed roof beam',
    crisis: 'A hand pump gives 250 N on a 0.005 m² piston. The 0.08 m² output ram is not producing the force the beam needs.',
    insight: 'Pressure passes through the fluid unchanged. A larger output piston converts that same pressure into a larger force.',
    resolution: 'At the solved output force the pressures match on both sides and the beam lifts.',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 250, leftB: 0.08, rightA: 0.005, leftName: 'Input side', rightName: 'Output side', productUnit: 'N·m²' },
      control: { label: 'Output force', unit: 'N', min: 500, max: 7000, precision: 0 },
      tolerance: 0.5,
      start: 8,
    },
  },
  {
    slug: 'heat-transfer',
    chapterId: 'physics.heat-thermal',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Heat transfer',
    lab: 'thermal',
    formula: 'Q = mc\\Delta T',
    scenario: 'a shelter boiler warming water for a hundred people',
    crisis: 'The burner delivers 209 kJ into 2.5 kg of water. The temperature rise setpoint is wrong, so the controller keeps cutting out.',
    insight: 'How much a substance warms depends on its mass and on how stubbornly it resists heating. Water resists a lot.',
    resolution: 'At the solved temperature rise the energy books balance at 209 kJ and the boiler runs continuously.',
    model: {
      kind: 'heatTransfer',
      params: { mass: 2.5, specificHeat: 4180, heat: 209000, leftName: 'Energy absorbed', rightName: 'Energy supplied', productUnit: 'J' },
      control: { label: 'Temperature rise', unit: 'K', min: 0, max: 45, precision: 1 },
      tolerance: 10000,
      start: 88,
    },
  },
  {
    slug: 'phase-energy',
    chapterId: 'physics.heat-thermal',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Phase energy',
    lab: 'thermal',
    formula: 'Q = mL',
    scenario: 'an ice core lab melting a sample without overheating it',
    crisis: 'The chamber can deliver 100.2 kJ. Ice needs 334 kJ per kilogram to melt, and the sample mass is set wrong.',
    insight: 'While something changes state its temperature stays put. All the energy goes into breaking the structure, not warming it.',
    resolution: 'At the solved sample mass the delivered energy melts it exactly, with none left to overheat the core.',
    model: {
      kind: 'proportional',
      params: { k: 334000, targetY: 100200, leftName: 'Energy needed', rightName: 'Energy available', productUnit: 'J' },
      control: { label: 'Sample mass', unit: 'kg', min: 0, max: 0.7, precision: 3 },
      tolerance: 5000,
      start: 90,
    },
  },
  {
    slug: 'projectile-paths',
    chapterId: 'physics.forces-motion',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Projectile paths',
    lab: 'projectile',
    formula: 'R = \\frac{v_0^2\\sin 2\\theta}{g}',
    scenario: 'a line-throwing gun firing a rescue rope across a river',
    crisis: 'The far bank is 96 m away. The launcher is locked at 40°, and the muzzle speed is wrong — every shot falls short.',
    insight: 'Range grows with the square of launch speed. A small speed increase reaches dramatically further.',
    resolution: 'At the solved muzzle speed the rope lands exactly on the far bank.',
    model: {
      kind: 'projectileRange',
      params: { range: 96, angle: 40, leftName: 'Predicted range', rightName: 'Required range', productUnit: 'm' },
      control: { label: 'Muzzle speed', unit: 'm/s', min: 10, max: 50, precision: 1 },
      tolerance: 6,
      start: 10,
    },
  },
  {
    slug: 'gravity-fields',
    chapterId: 'physics.space-gravity',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Gravity fields',
    lab: 'orbit',
    formula: 'F_g = \\frac{Gm_1m_2}{r^2}',
    scenario: 'a survey satellite choosing a stable orbit altitude',
    crisis: 'Station-keeping works only while gravitational pull sits at 4.0 kN. The current orbital radius puts the craft far outside that window.',
    insight: 'Gravity falls off with the square of distance. Doubling the separation cuts the pull to a quarter, not a half.',
    resolution: 'At the solved orbital radius the pull settles on 4.0 kN and the orbit holds without correction burns.',
    model: {
      kind: 'inverseSquare',
      params: { constant: 398500, targetForce: 4000, leftName: 'Gravitational pull', rightName: 'Station-keeping target', productUnit: 'N' },
      control: { label: 'Orbital radius', unit: 'Mm', min: 6.4, max: 14, precision: 2 },
      tolerance: 180,
      start: 92,
    },
  },
  {
    slug: 'seesaw-balance',
    chapterId: 'physics.forces-motion',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 3,
    title: 'Balancing a seesaw',
    lab: 'balance',
    formula: 'm_1 d_1 = m_2 d_2',
    scenario: 'a playground seesaw with two children of very different size',
    crisis: 'A 30 kg child sits 1.2 m from the middle. A 45 kg child keeps slamming down on the other side however close in they shuffle.',
    insight: 'A seesaw balances on turning effect, not weight. A heavier child has to sit closer to the pivot to have the same effect.',
    resolution: 'At the solved distance the seesaw hangs level and both children can push off gently.',
    standardIds: ['cbse:3:9', 'ngss:3-5-PS2-1', 'uk:KS2:forces'],
    model: {
      kind: 'inverseProduct',
      params: { leftA: 30, leftB: 1.2, rightA: 45, leftName: 'Small child moment', rightName: 'Large child moment', productUnit: 'kg·m' },
      control: { label: 'Heavier child distance', unit: 'm', min: 0.2, max: 1.6, precision: 2 },
      tolerance: 1.1,
      start: 92,
    },
  },
  {
    slug: 'pulling-a-cart',
    chapterId: 'physics.forces-motion',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 4,
    title: 'Pushing a loaded cart',
    lab: 'force',
    formula: 'F = ma',
    scenario: 'a market porter shifting a loaded handcart off a kerb',
    crisis: 'The cart and its load come to 60 kg and the porter needs it moving at 0.9 m/s² to clear the ramp. He is pushing far too gently.',
    insight: 'The push needed grows with both the mass and the acceleration you want. Doubling the load doubles the push for the same result.',
    resolution: 'At the solved push the cart accelerates exactly as needed and rides the kerb cleanly.',
    standardIds: ['cbse:4:9', 'ngss:3-5-PS2-1'],
    model: {
      kind: 'proportional',
      params: { k: 0.016666666666666666, targetY: 0.9, leftName: 'Acceleration produced', rightName: 'Acceleration needed', productUnit: 'm/s²' },
      control: { label: 'Push force', unit: 'N', min: 0, max: 120, precision: 1 },
      tolerance: 0.09,
      start: 92,
    },
  },
  {
    slug: 'crowbar-lift',
    chapterId: 'physics.forces-motion',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 7,
    title: 'Crowbar leverage',
    lab: 'lever',
    formula: 'F_1 d_1 = F_2 d_2',
    scenario: 'a stagehand levering a crate lid with a flat bar',
    crisis: 'The lid resists with 480 N acting 0.05 m from the fulcrum. The stagehand can pull with only 60 N and the bar keeps slipping.',
    insight: 'A lever trades distance for force. The further from the pivot you apply your effort, the less of it you need.',
    resolution: 'With the hands at the solved distance, 60 N is enough and the lid lifts.',
    standardIds: ['cbse:7:13', 'icse:7:simple-machines'],
    model: {
      kind: 'inverseProduct',
      params: { leftA: 480, leftB: 0.05, rightA: 60, leftName: 'Load moment', rightName: 'Effort moment', productUnit: 'N·m' },
      control: { label: 'Effort distance', unit: 'm', min: 0, max: 0.9, precision: 2 },
      tolerance: 1.4,
      start: 92,
    },
  },
  {
    slug: 'friction-brake',
    chapterId: 'physics.forces-motion',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 7,
    title: 'Braking friction',
    lab: 'friction',
    formula: 'f = \\mu N',
    scenario: 'a loading-bay conveyor whose emergency brake pad is being set',
    crisis: 'The pad grips with a coefficient of 0.35 and the stop demands 245 N of friction. The clamp is set far too loose to reach it.',
    insight: 'Friction rises with how hard the surfaces are pressed together, not with how large they are. The normal force is the lever you actually have.',
    resolution: 'At the solved clamp load the pad delivers exactly the friction the stop requires.',
    standardIds: ['cbse:8:12', 'igcse:1.6'],
    model: {
      kind: 'proportional',
      params: { k: 0.35, targetY: 245, leftName: 'Friction available', rightName: 'Friction required', productUnit: 'N' },
      control: { label: 'Clamp normal force', unit: 'N', min: 0, max: 1400, precision: 0 },
      tolerance: 24,
      start: 92,
    },
  },
  {
    slug: 'wagon-coupling',
    chapterId: 'physics.forces-motion',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 9,
    title: 'Conserving momentum',
    lab: 'collision',
    formula: 'm_1 u_1 = (m_1 + m_2) v',
    scenario: 'a shunting yard coupling a moving wagon to a stationary one',
    crisis: 'A 12 000 kg wagon rolls in and couples to a stationary 8 000 kg wagon. The yard limit for the joined pair is a fixed 1.8 m/s and the approach speed is set wrong.',
    insight: 'Momentum before a collision equals momentum after it. Coupling spreads the same momentum over a larger mass, so the speed must drop.',
    resolution: 'At the solved approach speed the coupled pair rolls away at exactly the yard limit.',
    standardIds: ['cbse:9:9', 'icse:9:momentum', 'igcse:1.5'],
    model: {
      kind: 'proportional',
      params: { k: 12000, targetY: 36000, leftName: 'Incoming momentum', rightName: 'Coupled momentum', productUnit: 'kg·m/s' },
      control: { label: 'Approach speed', unit: 'm/s', min: 0, max: 6, precision: 2 },
      tolerance: 900,
      start: 92,
    },
  },
  {
    slug: 'lifting-work',
    chapterId: 'physics.energy-work',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 5,
    title: 'Work done lifting',
    lab: 'energy',
    formula: 'W = F \\times d',
    scenario: 'a well in a courtyard where a bucket is hauled by hand',
    crisis: 'The full bucket weighs 45 N and the rope job is rated at 405 J per haul. Nobody has measured how deep the well actually is.',
    insight: 'Work is force multiplied by the distance moved along it. Lifting twice as high does twice the work for the same bucket.',
    resolution: 'At the solved depth, one full haul does exactly the rated work.',
    standardIds: ['cbse:5:9', 'ngss:3-5-PS3-1'],
    model: {
      kind: 'proportional',
      params: { k: 45, targetY: 405, leftName: 'Work done', rightName: 'Rated work', productUnit: 'J' },
      control: { label: 'Well depth', unit: 'm', min: 0, max: 20, precision: 1 },
      tolerance: 40,
      start: 92,
    },
  },
  {
    slug: 'potential-energy-store',
    chapterId: 'physics.energy-work',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 7,
    title: 'Gravitational store',
    lab: 'energy',
    formula: 'E_p = mgh',
    scenario: 'a pumped-storage reservoir topping up overnight',
    crisis: 'The upper basin holds 250 000 kg of water and the operator needs 6.13 MJ banked before morning. The head of water is set wrong.',
    insight: 'Energy stored by lifting depends on mass, gravity and height together. Height is the only one of the three an operator can change.',
    resolution: 'At the solved head the basin stores exactly the energy the morning peak needs.',
    standardIds: ['cbse:9:11', 'igcse:1.7'],
    model: {
      kind: 'proportional',
      params: { k: 2452500, targetY: 6131250, leftName: 'Energy stored', rightName: 'Energy required', productUnit: 'J' },
      control: { label: 'Water head', unit: 'm', min: 0, max: 6, precision: 2 },
      tolerance: 150000,
      start: 92,
    },
  },
  {
    slug: 'power-rating',
    chapterId: 'physics.energy-work',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Power and time',
    lab: 'energy',
    formula: 'P = \\frac{W}{t}',
    scenario: 'a goods lift being specified for a warehouse mezzanine',
    crisis: 'Each trip does 33 600 J of work and the motor plate is fixed at 2 800 W. The trip time in the specification does not match either figure.',
    insight: 'Power is the rate of doing work. The same job done in half the time needs twice the power.',
    resolution: 'At the solved trip time the work and the motor rating agree exactly.',
    standardIds: ['cbse:9:11', 'icse:8:work-power'],
    model: {
      kind: 'proportional',
      params: { k: 2800, targetY: 33600, leftName: 'Work delivered', rightName: 'Work per trip', productUnit: 'J' },
      control: { label: 'Trip time', unit: 's', min: 0, max: 30, precision: 1 },
      tolerance: 2600,
      start: 92,
    },
  },
  {
    slug: 'kinetic-energy-stop',
    chapterId: 'physics.energy-work',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 9,
    title: 'Stopping distance energy',
    lab: 'friction',
    formula: 'E_k = f \\times d',
    scenario: 'a runaway trolley ramp at the end of a steep service road',
    crisis: 'The trolley arrives carrying 18 750 J and the gravel bed resists with 2 500 N. The bed as built is the wrong length.',
    insight: 'All the kinetic energy has to be absorbed as work against friction. A weaker resisting force simply needs a longer run.',
    resolution: 'At the solved bed length the trolley comes to rest exactly at the end of the gravel.',
    standardIds: ['cbse:9:11', 'igcse:1.7'],
    model: {
      kind: 'proportional',
      params: { k: 2500, targetY: 18750, leftName: 'Work absorbed', rightName: 'Kinetic energy', productUnit: 'J' },
      control: { label: 'Gravel bed length', unit: 'm', min: 0, max: 16, precision: 1 },
      tolerance: 1800,
      start: 92,
    },
  },
  {
    slug: 'coil-field-strength',
    chapterId: 'physics.electricity-magnetism',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 7,
    title: 'Electromagnet turns',
    lab: 'magnet',
    formula: 'B \\propto NI',
    scenario: 'a scrapyard lifting magnet being rewound after a burnout',
    crisis: 'The coil carries 4 A and the lift needs a field figure of 1 800 ampere-turns. The winder has no note of how many turns the old coil had.',
    insight: 'A coil\'s field grows with both the current through it and the number of turns. Turns are cheap; current costs heat.',
    resolution: 'At the solved turn count the rewound coil reaches the lifting field on 4 A.',
    standardIds: ['cbse:7:14', 'icse:7:magnetism'],
    model: {
      kind: 'proportional',
      params: { k: 4, targetY: 1800, leftName: 'Ampere-turns produced', rightName: 'Ampere-turns needed', productUnit: 'A·t' },
      control: { label: 'Coil turns', unit: 'turns', min: 0, max: 900, precision: 0 },
      tolerance: 170,
      start: 92,
    },
  },
  {
    slug: 'transformer-ratio',
    chapterId: 'physics.electricity-magnetism',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Transformer turns ratio',
    lab: 'magnet',
    formula: '\\frac{V_s}{V_p} = \\frac{N_s}{N_p}',
    scenario: 'a village transformer being rewound to feed a new pump house',
    crisis: 'The primary has 2 200 turns on 11 000 V and the pump house must receive 240 V. The secondary winding count on the order form is blank.',
    insight: 'A transformer trades voltage for current in the ratio of its windings. The turns ratio is the voltage ratio, exactly.',
    resolution: 'At the solved secondary count the output sits at the 240 V the pump house needs.',
    standardIds: ['cbse:10:12', 'icse:10:electromagnetism', 'igcse:4.5'],
    model: {
      kind: 'ratioMatch',
      params: { a: 11000, b: 240, c: 2200, leftName: 'Primary side', rightName: 'Secondary side', productUnit: 'turns' },
      control: { label: 'Secondary turns', unit: 'turns', min: 0, max: 110, precision: 0 },
      tolerance: 44000,
      start: 92,
    },
  },
  {
    slug: 'echo-timing',
    chapterId: 'physics.waves-sound',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 5,
    title: 'Timing an echo',
    lab: 'mirror',
    formula: 'd = \\frac{vt}{2}',
    scenario: 'a canyon wall being ranged by shouting and counting',
    crisis: 'Sound travels 340 m/s and the echo comes back after a round trip of 1.5 s. The map distance to the wall is disputed.',
    insight: 'An echo travels to the wall and back, so it covers twice the distance you want. Halving the round trip gives the true range.',
    resolution: 'At the solved distance the echo returns in exactly the measured time.',
    standardIds: ['cbse:8:13', 'ngss:3-5-PS4-1'],
    model: {
      kind: 'proportional',
      params: { k: 2, targetY: 510, leftName: 'Round trip distance', rightName: 'Sound path', productUnit: 'm' },
      control: { label: 'Distance to wall', unit: 'm', min: 0, max: 600, precision: 0 },
      tolerance: 50,
      start: 92,
    },
  },
  {
    slug: 'string-frequency',
    chapterId: 'physics.waves-sound',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Tuning a string',
    lab: 'wave',
    formula: 'v = f\\lambda',
    scenario: 'a sitar being tuned before a recording session',
    crisis: 'The wave travels the string at 246 m/s and the fundamental wavelength is fixed at 1.2 m by the bridge spacing. The tuner reads far off pitch.',
    insight: 'Wave speed, frequency and wavelength are locked together. Fixing two of them fixes the third with no freedom left.',
    resolution: 'At the solved frequency the string sounds exactly the note the bridge geometry demands.',
    standardIds: ['cbse:8:13', 'igcse:3.3'],
    model: {
      kind: 'waveSpeed',
      params: { speed: 246, wavelength: 1.2, leftName: 'Wave speed produced', rightName: 'String wave speed', productUnit: 'm/s' },
      control: { label: 'Frequency', unit: 'Hz', min: 0, max: 420, precision: 1 },
      tolerance: 24,
      start: 92,
    },
  },
  {
    slug: 'ultrasound-depth',
    chapterId: 'physics.waves-sound',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Sonar depth sounding',
    lab: 'wave',
    formula: 'd = \\frac{vt}{2}',
    scenario: 'a fishing boat sounding a channel before entering at low tide',
    crisis: 'Sound moves at 1 500 m/s in seawater and the transducer logs a 0.048 s round trip. The chart depth disagrees with the sounder.',
    insight: 'Sonar is an echo in water. The speed is far higher than in air, so a short delay still means a real depth.',
    resolution: 'At the solved depth the round-trip time matches the transducer log exactly.',
    standardIds: ['cbse:9:12', 'igcse:3.4'],
    model: {
      kind: 'proportional',
      params: { k: 2, targetY: 72, leftName: 'Round trip path', rightName: 'Sound path', productUnit: 'm' },
      control: { label: 'Channel depth', unit: 'm', min: 0, max: 80, precision: 1 },
      tolerance: 7,
      start: 92,
    },
  },
  {
    slug: 'shadow-length',
    chapterId: 'physics.light-optics',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 4,
    title: 'Shadows and similar triangles',
    lab: 'mirror',
    formula: '\\frac{h_1}{s_1} = \\frac{h_2}{s_2}',
    scenario: 'a school measuring a flagpole without climbing it',
    crisis: 'A 1.5 m pupil casts a 2.5 m shadow. The flagpole casts a 15 m shadow at the same moment and its height is unknown.',
    insight: 'At one moment the sun strikes everything at the same angle, so every object and its shadow form the same shape of triangle.',
    resolution: 'At the solved height the flagpole\'s shadow ratio matches the pupil\'s exactly.',
    standardIds: ['cbse:4:12', 'ngss:3-5-PS4-2'],
    model: {
      kind: 'ratioMatch',
      params: { a: 2.5, b: 1.5, c: 15, leftName: 'Pupil ratio scaled', rightName: 'Flagpole shadow', productUnit: 'm' },
      control: { label: 'Flagpole height', unit: 'm', min: 0, max: 18, precision: 1 },
      tolerance: 2.2,
      start: 92,
    },
  },
  {
    slug: 'mirror-reflection-angle',
    chapterId: 'physics.light-optics',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 7,
    title: 'Law of reflection',
    lab: 'mirror',
    formula: '\\theta_i = \\theta_r',
    scenario: 'a heliostat aiming daylight down a hospital light well',
    crisis: 'The beam has to be turned through 68° in total, measured from the incoming ray round to the outgoing one, and the mirror is set well off that figure.',
    insight: 'Light leaves a mirror at the same angle it arrives, measured from the normal. The two angles always add to the total deviation.',
    resolution: 'At the solved reflected angle the beam leaves along the light well as designed.',
    standardIds: ['cbse:7:15', 'icse:7:light'],
    model: {
      kind: 'sumToConstant',
      params: { known: 34, total: 68, leftName: 'Total turn', rightName: 'Required turn', productUnit: '°' },
      control: { label: 'Reflected angle', unit: '°', min: 0, max: 80, precision: 1 },
      tolerance: 2.4,
      start: 92,
    },
  },
  {
    slug: 'lens-power',
    chapterId: 'physics.light-optics',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Lens power',
    lab: 'lens',
    formula: 'P = \\frac{1}{f}',
    scenario: 'an optician grinding a reading lens to a written prescription',
    crisis: 'The prescription calls for 2.5 dioptres and the blank has been cut to the wrong focal length. A trial frame shows the text still blurred.',
    insight: 'Lens power is the reciprocal of focal length in metres. A stronger lens bends light more sharply over a shorter distance.',
    resolution: 'At the solved focal length the lens delivers exactly the prescribed power.',
    standardIds: ['cbse:10:10', 'icse:10:refraction', 'igcse:3.2'],
    model: {
      kind: 'proportional',
      params: { k: 2.5, targetY: 1, leftName: 'Power × focal length', rightName: 'Unity', productUnit: '' },
      control: { label: 'Focal length', unit: 'm', min: 0, max: 0.9, precision: 3 },
      tolerance: 0.1,
      start: 92,
    },
  },
  {
    slug: 'pressure-under-foot',
    chapterId: 'physics.pressure-fluids',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 5,
    title: 'Pressure and area',
    lab: 'area',
    formula: 'P = \\frac{F}{A}',
    scenario: 'a rescue team crossing thin ice on boards',
    crisis: 'A rescuer weighs 700 N and the ice will not take more than 3 500 Pa. Standing in boots the pressure is far over the limit.',
    insight: 'The same weight spread over a larger area presses less hard at every point. Boards do not make you lighter, only wider.',
    resolution: 'At the solved board area the pressure sits exactly on the ice limit.',
    standardIds: ['cbse:8:11', 'ngss:3-5-PS2-1'],
    model: {
      kind: 'proportional',
      params: { k: 3500, targetY: 700, leftName: 'Load supported', rightName: 'Rescuer weight', productUnit: 'N' },
      control: { label: 'Board area', unit: 'm²', min: 0, max: 0.5, precision: 3 },
      tolerance: 70,
      start: 92,
    },
  },
  {
    slug: 'hydraulic-jack',
    chapterId: 'physics.pressure-fluids',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Hydraulic advantage',
    lab: 'hydraulic',
    formula: '\\frac{F_1}{A_1} = \\frac{F_2}{A_2}',
    scenario: 'a workshop jack being sized to lift a tractor axle',
    crisis: 'The small piston takes 150 N over 0.0015 m² and the axle needs 9 000 N. The large piston fitted is the wrong bore.',
    insight: 'Pressure passes undiminished through a liquid, so a larger piston turns the same pressure into a larger force.',
    resolution: 'At the solved piston area the jack lifts the axle on 150 N of hand effort.',
    standardIds: ['cbse:8:11', 'igcse:1.8'],
    model: {
      kind: 'proportional',
      params: { k: 100000, targetY: 9000, leftName: 'Force delivered', rightName: 'Force required', productUnit: 'N' },
      control: { label: 'Large piston area', unit: 'm²', min: 0, max: 0.2, precision: 4 },
      tolerance: 900,
      start: 92,
    },
  },
  {
    slug: 'water-column-pressure',
    chapterId: 'physics.pressure-fluids',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 9,
    title: 'Pressure with depth',
    lab: 'hydraulic',
    formula: 'P = \\rho g h',
    scenario: 'a rooftop tank feeding a sprinkler system four floors down',
    crisis: 'Water is 1 000 kg/m³ and the sprinkler heads need 117 720 Pa to open. The tank sits at the wrong height above the risers.',
    insight: 'Pressure at the bottom of a column depends only on the height of liquid above it, not on the width of the tank.',
    resolution: 'At the solved head the sprinklers see exactly their opening pressure.',
    standardIds: ['cbse:9:10', 'igcse:1.8'],
    model: {
      kind: 'proportional',
      params: { k: 9810, targetY: 117720, leftName: 'Pressure at the head', rightName: 'Opening pressure', productUnit: 'Pa' },
      control: { label: 'Tank height', unit: 'm', min: 0, max: 26, precision: 1 },
      tolerance: 11000,
      start: 92,
    },
  },
  {
    slug: 'heating-water',
    chapterId: 'physics.heat-thermal',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 7,
    title: 'Heating a tank',
    lab: 'thermal',
    formula: 'Q = mc\\Delta T',
    scenario: 'a hostel water heater sized for the morning rush',
    crisis: 'Eighty kilograms of water take 4 200 J per kilogram per degree, and the boiler can deliver 10 080 000 J. The temperature rise on the datasheet is wrong.',
    insight: 'The heat needed scales with mass, with the material\'s specific heat, and with the rise you want. Water is stubborn on all three counts.',
    resolution: 'At the solved rise the boiler energy exactly matches the tank\'s demand.',
    standardIds: ['cbse:7:4', 'igcse:2.2'],
    model: {
      kind: 'heatTransfer',
      params: { heat: 10080000, mass: 80, specificHeat: 4200, leftName: 'Heat absorbed', rightName: 'Heat supplied', productUnit: 'J' },
      control: { label: 'Temperature rise', unit: '°C', min: 0, max: 60, precision: 1 },
      tolerance: 900000,
      start: 92,
    },
  },
  {
    slug: 'thermal-expansion-gap',
    chapterId: 'physics.heat-thermal',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 9,
    title: 'Expansion gap',
    lab: 'thermal',
    formula: '\\Delta L = \\alpha L \\Delta T',
    scenario: 'a steel footbridge being set on its bearings in winter',
    crisis: 'The 50 m span expands by 0.000012 per degree per metre, and the bearings were set with a 0.0192 m gap. Nobody recorded the summer rise that gap was sized for.',
    insight: 'Every material stretches as it warms. A bridge that is not given room to grow will buckle or shear its own bearings.',
    resolution: 'At the solved temperature rise the expansion exactly fills the gap that was left.',
    standardIds: ['cbse:9:1', 'igcse:2.1'],
    model: {
      kind: 'proportional',
      params: { k: 0.0006, targetY: 0.0192, leftName: 'Expansion produced', rightName: 'Gap allowed', productUnit: 'm' },
      control: { label: 'Temperature rise', unit: '°C', min: 0, max: 90, precision: 1 },
      tolerance: 0.0018,
      start: 92,
    },
  },
  {
    slug: 'weight-on-planets',
    chapterId: 'physics.space-gravity',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 5,
    title: 'Weight and gravity',
    lab: 'orbit',
    formula: 'W = mg',
    scenario: 'a science museum exhibit that weighs visitors on other worlds',
    crisis: 'The display is set for a 50 kg visitor and must read 185 N on the Martian pad. The gravity constant loaded into the exhibit is wrong.',
    insight: 'Mass never changes but weight does, because weight is mass pulled on by a particular world\'s gravity.',
    resolution: 'At the solved gravity the pad reads exactly the Martian weight for a 50 kg visitor.',
    standardIds: ['cbse:5:9', 'ngss:3-5-PS2-1'],
    model: {
      kind: 'proportional',
      params: { k: 50, targetY: 185, leftName: 'Weight displayed', rightName: 'Martian weight', productUnit: 'N' },
      control: { label: 'Surface gravity', unit: 'm/s²', min: 0, max: 11, precision: 2 },
      tolerance: 18,
      start: 92,
    },
  },
  {
    slug: 'orbital-radius',
    chapterId: 'physics.space-gravity',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Gravitational pull with distance',
    lab: 'orbit',
    formula: 'F = \\frac{GMm}{r^2}',
    scenario: 'a survey satellite being placed where its instrument reads correctly',
    crisis: 'The gravitational constant term comes to 3.99e14 for this pairing and the instrument is calibrated for 2.5 N/kg. The commanded orbit radius is wrong.',
    insight: 'Gravity falls with the square of distance, so doubling the radius quarters the pull. Small radius errors matter enormously.',
    resolution: 'At the solved radius the satellite feels exactly the field the instrument expects.',
    standardIds: ['cbse:9:10', 'icse:10:gravitation'],
    model: {
      kind: 'inverseSquare',
      params: { constant: 399000000000000, targetForce: 2.5, leftName: 'Field at radius', rightName: 'Calibrated field', productUnit: 'N/kg' },
      control: { label: 'Orbit radius', unit: 'm', min: 0, max: 26000000, precision: 0 },
      tolerance: 0.24,
      start: 92,
    },
  },
  {
    slug: 'floating-and-sinking',
    chapterId: 'physics.pressure-fluids',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 3,
    title: 'Floating and sinking',
    lab: 'gas',
    formula: 'F_b = \\rho g V',
    scenario: 'a class testing which objects float in a water tray',
    crisis: 'A block must be held up by 4.9 N of upthrust and water provides 9 810 N for every cubic metre pushed aside. The displaced volume is unknown.',
    insight: 'An object floats when the water it pushes aside weighs as much as the object does. Shape matters because it changes how much is pushed aside.',
    resolution: 'At the solved displaced volume the block floats exactly level with the surface.',
    standardIds: ['cbse:3:5', 'ngss:3-5-PS1-1'],
    model: {
      kind: 'proportional',
      params: { k: 9810, targetY: 4.9, leftName: 'Upthrust produced', rightName: 'Upthrust needed', productUnit: 'N' },
      control: { label: 'Displaced volume', unit: 'm³', min: 0, max: 0.001, precision: 6 },
      tolerance: 0.45,
      start: 92,
    },
  },
  {
    slug: 'speed-distance-time',
    chapterId: 'physics.forces-motion',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 4,
    title: 'Speed, distance and time',
    lab: 'collision',
    formula: 'v = \\frac{d}{t}',
    scenario: 'a school bus route being timetabled to arrive before the bell',
    crisis: 'The route runs 18 km and the bus must be parked within a fixed window. The average speed written into the timetable gives the wrong arrival.',
    insight: 'Speed ties distance and time together. Fix any two and the third is decided for you.',
    resolution: 'At the solved speed the bus covers the route in exactly the timetabled window.',
    standardIds: ['cbse:4:9', 'uk:KS2:forces'],
    model: {
      kind: 'proportional',
      params: { k: 0.5, targetY: 18, leftName: 'Distance covered', rightName: 'Route length', productUnit: 'km' },
      control: { label: 'Average speed', unit: 'km/h', min: 0, max: 80, precision: 1 },
      tolerance: 1.7,
      start: 92,
    },
  },
  {
    slug: 'series-resistance-sum',
    chapterId: 'physics.electricity-magnetism',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 7,
    title: 'Resistors in series',
    lab: 'balance',
    formula: 'R_T = R_1 + R_2',
    scenario: 'a lab bench dropping a supply down to a safe test voltage',
    crisis: 'A 68 Ω resistor is already in the loop and the meter must read a total of 150 Ω. The second resistor pulled from the drawer is the wrong value.',
    insight: 'Resistors in a line each take their share of the push, so their resistances simply add.',
    resolution: 'At the solved resistance the loop totals exactly 150 Ω.',
    standardIds: ['cbse:7:14', 'igcse:4.3'],
    model: {
      kind: 'sumToConstant',
      params: { known: 68, total: 150, leftName: 'Loop resistance', rightName: 'Target resistance', productUnit: 'Ω' },
      control: { label: 'Second resistor', unit: 'Ω', min: 0, max: 160, precision: 1 },
      tolerance: 4.5,
      start: 8,
    },
  },
  {
    slug: 'refraction-angle',
    chapterId: 'physics.light-optics',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Refraction at a boundary',
    lab: 'lens',
    formula: 'n_1\\sin\\theta_1 = n_2\\sin\\theta_2',
    scenario: 'a fibre-optic splice being aligned against its acceptance cone',
    crisis: 'Light passes from air at n = 1.00 into glass at n = 1.50, and the internal ray must sit at 25° to the normal. The incoming alignment is off.',
    insight: 'Light bends toward the normal on entering a denser medium. The two angles are locked by the ratio of refractive indices.',
    resolution: 'At the solved incidence angle the internal ray lands exactly on the acceptance line.',
    standardIds: ['cbse:10:10', 'icse:10:refraction', 'igcse:3.2'],
    model: {
      kind: 'snell',
      params: { n1: 1, n2: 1.5, theta2: 25, leftName: 'Incident side', rightName: 'Refracted side', productUnit: '' },
      control: { label: 'Incidence angle', unit: '°', min: 0, max: 80, precision: 1 },
      tolerance: 0.06,
      start: 92,
    },
  },
  {
    slug: 'specific-heat-metal',
    chapterId: 'physics.heat-thermal',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Specific heat capacity',
    lab: 'particle',
    formula: 'c = \\frac{Q}{m\\Delta T}',
    scenario: 'a foundry identifying an unlabelled metal ingot by its heat capacity',
    crisis: 'A 2 kg ingot takes 46 000 J to raise it by 25 °C. The specific heat entered into the identification table is wrong.',
    insight: 'Every material resists heating by its own fixed amount per kilogram per degree. That number is a fingerprint.',
    resolution: 'At the solved specific heat the measured energy and the temperature rise agree exactly.',
    standardIds: ['cbse:10:1', 'igcse:2.2'],
    model: {
      kind: 'proportional',
      params: { k: 50, targetY: 46000, leftName: 'Energy accounted for', rightName: 'Energy supplied', productUnit: 'J' },
      control: { label: 'Specific heat', unit: 'J/kg·°C', min: 0, max: 2000, precision: 0 },
      tolerance: 4300,
      start: 92,
    },
  },
  {
    slug: 'simple-pulley',
    chapterId: 'physics.forces-motion',
    difficulty: 'Foundation',
    gradeGroup: 'early',
    gradeLevel: 5,
    title: 'Pulleys and effort',
    lab: 'balance',
    formula: 'F = \\frac{W}{n}',
    scenario: 'a builder hoisting mortar to a first-floor scaffold',
    crisis: 'The bucket weighs 360 N and the builder can pull with 90 N without straining. The block fitted has the wrong number of supporting ropes.',
    insight: 'Each rope supporting the load carries a share of it. More ropes means less pull, but more rope to haul through.',
    resolution: 'At the solved rope count the builder lifts the bucket on 90 N.',
    standardIds: ['cbse:5:9', 'icse:7:simple-machines'],
    model: {
      kind: 'proportional',
      params: { k: 90, targetY: 360, leftName: 'Load supported', rightName: 'Bucket weight', productUnit: 'N' },
      control: { label: 'Supporting ropes', unit: 'ropes', min: 0, max: 9, precision: 0 },
      tolerance: 33,
      start: 92,
    },
  },
  {
    slug: 'terminal-velocity',
    chapterId: 'physics.forces-motion',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 8,
    title: 'Balanced forces in fall',
    lab: 'friction',
    formula: 'W = D',
    scenario: 'an aid drop being rigged so crates land intact',
    crisis: 'A loaded crate weighs 2 940 N and the canopy must generate exactly that in drag before it reaches the ground. The chute area rigged is wrong.',
    insight: 'A falling object stops accelerating when drag has grown to match weight. It keeps falling, but at a steady speed.',
    resolution: 'At the solved canopy area drag balances weight and the crate descends steadily.',
    standardIds: ['cbse:8:12', 'igcse:1.5'],
    model: {
      kind: 'proportional',
      params: { k: 140, targetY: 2940, leftName: 'Drag generated', rightName: 'Crate weight', productUnit: 'N' },
      control: { label: 'Canopy area', unit: 'm²', min: 0, max: 45, precision: 1 },
      tolerance: 270,
      start: 92,
    },
  },
  {
    slug: 'sound-insulation',
    chapterId: 'physics.waves-sound',
    difficulty: 'Explorer',
    gradeGroup: 'middle',
    gradeLevel: 7,
    title: 'Absorbing sound',
    lab: 'mirror',
    formula: 'A = \\alpha S',
    scenario: 'a school hall being treated so speech is intelligible',
    crisis: 'The acoustic panels absorb 0.65 of the sound striking them and the hall needs 130 absorption units to settle. The panel area ordered is short.',
    insight: 'A hard room returns sound and blurs speech. Absorption depends on how much treated surface the sound can find.',
    resolution: 'At the solved panel area the hall reaches exactly its absorption target.',
    standardIds: ['cbse:8:13', 'icse:8:sound'],
    model: {
      kind: 'proportional',
      params: { k: 0.65, targetY: 130, leftName: 'Absorption achieved', rightName: 'Absorption needed', productUnit: 'units' },
      control: { label: 'Panel area', unit: 'm²', min: 0, max: 420, precision: 0 },
      tolerance: 12,
      start: 92,
    },
  },
  {
    slug: 'satellite-period',
    chapterId: 'physics.space-gravity',
    difficulty: 'Challenge',
    gradeGroup: 'high',
    gradeLevel: 10,
    title: 'Orbital speed',
    lab: 'orbit',
    formula: 'v = \\frac{2\\pi r}{T}',
    scenario: 'a ground station predicting when a survey satellite reappears',
    crisis: 'The orbit circumference works out at 42 000 km and the satellite travels at 7 km/s. The pass time loaded into the tracker is wrong.',
    insight: 'Orbital period is the path length divided by the speed along it. A higher orbit is both longer and slower.',
    resolution: 'At the solved period the tracker predicts the pass correctly.',
    standardIds: ['cbse:9:10', 'icse:10:gravitation'],
    model: {
      kind: 'proportional',
      params: { k: 7, targetY: 42000, leftName: 'Distance travelled', rightName: 'Orbit circumference', productUnit: 'km' },
      control: { label: 'Orbital period', unit: 's', min: 0, max: 12000, precision: 0 },
      tolerance: 3800,
      start: 92,
    },
  },
];

export default physics;
