/**
 * Physics missions.
 *
 * Every entry carries its own equation, its own real quantities, and its own
 * story. The balance point is solved from the equation — never picked to look
 * plausible — so tuning the control is genuinely doing the physics.
 */

const physics = [
  {
    slug: 'torque-balance',
    title: 'Torque balance',
    lab: 'lever',
    formula: '\\tau_1 = \\tau_2 \\;\\Rightarrow\\; F_1 d_1 = F_2 d_2',
    scenario: 'a cargo crane leaning over a flooded rail yard',
    crisis: 'The jib is holding a 12 kN pallet 1.8 m out from the pivot, and the counterweight is parked in the wrong slot. The whole arm is creeping downward.',
    insight: 'A pivot does not care about force alone. It cares about force multiplied by distance. A small counterweight far out can hold a large load close in.',
    resolution: 'With the counterweight at the solved distance, both moments about the pivot are equal and the jib stops moving.',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 12, leftB: 1.8, rightA: 9, leftName: 'Load moment', rightName: 'Counter moment', productUnit: 'kN·m' },
      control: { label: 'Counterweight distance', unit: 'm', min: 0.5, max: 4, precision: 2 },
      tolerance: 0.9,
      start: 12,
    },
  },
  {
    slug: 'lever-arms',
    title: 'Lever arms',
    lab: 'lever',
    formula: 'F_1 d_1 = F_2 d_2',
    scenario: 'a field workshop lifting a generator with a scaffold pole',
    crisis: 'Two students can push with 15 N. The generator resists with 45 N acting 0.4 m from the fulcrum. Right now the pole is too short to help.',
    insight: 'Moving the effort further from the fulcrum multiplies it. The lever does not create energy — it trades distance for force.',
    resolution: 'At the solved effort arm, 15 N does the work of 45 N and the generator lifts clear.',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 45, leftB: 0.4, rightA: 15, leftName: 'Load moment', rightName: 'Effort moment', productUnit: 'N·m' },
      control: { label: 'Effort arm length', unit: 'm', min: 0.2, max: 2.2, precision: 2 },
      tolerance: 0.8,
      start: 88,
    },
  },
  {
    slug: 'center-of-mass',
    title: 'Center of mass',
    lab: 'lever',
    formula: 'm_1 x_1 = m_2 x_2',
    scenario: 'a rescue plank bridging a collapsed stairwell',
    crisis: 'A 3 kg toolbag sits 0.8 m left of the support. A 2 kg medical kit must go somewhere on the right, and the plank tips the moment the balance is wrong.',
    insight: 'The balance point is where mass-times-distance matches on both sides. Lighter objects simply have to sit further out.',
    resolution: 'Placed at the solved distance, the combined center of mass sits exactly over the support.',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 3, leftB: 0.8, rightA: 2, leftName: 'Left moment', rightName: 'Right moment', productUnit: 'kg·m' },
      control: { label: 'Medical kit distance', unit: 'm', min: 0.2, max: 2.4, precision: 2 },
      tolerance: 0.15,
      start: 8,
    },
  },
  {
    slug: 'static-friction',
    title: 'Static friction',
    lab: 'friction',
    formula: 'F_f = \\mu_s N',
    scenario: 'a loading ramp where crates keep sliding on wet steel',
    crisis: 'The grip coefficient is 0.35 and the crate needs 28 N of friction to stay put. Not enough weight is pressing it down.',
    insight: 'Friction is not a fixed property of a surface. It scales with how hard the surfaces are pushed together.',
    resolution: 'At the solved normal force, available friction exactly meets the 28 N the crate needs.',
    model: {
      kind: 'proportional',
      params: { k: 0.35, targetY: 28, leftName: 'Available friction', rightName: 'Required friction', productUnit: 'N' },
      control: { label: 'Normal force', unit: 'N', min: 20, max: 140, precision: 0 },
      tolerance: 1.2,
      start: 15,
    },
  },
  {
    slug: 'newtons-first-law',
    title: "Newton's first law",
    lab: 'force',
    formula: '\\sum F = 0',
    scenario: 'a cable car stalled halfway across a gorge',
    crisis: 'Drag and cable friction pull backwards with 180 N. The drive motor is applying the wrong thrust, so the car keeps drifting instead of holding station.',
    insight: 'Constant velocity does not need zero force. It needs forces that cancel. Balanced does not mean nothing is happening.',
    resolution: 'With thrust matched to resistance, the net force is zero and the car holds its position exactly.',
    model: {
      kind: 'proportional',
      params: { k: 1, targetY: 180, leftName: 'Applied thrust', rightName: 'Total resistance', productUnit: 'N' },
      control: { label: 'Motor thrust', unit: 'N', min: 0, max: 400, precision: 0 },
      tolerance: 12,
      start: 90,
    },
  },
  {
    slug: 'newtons-second-law',
    title: "Newton's second law",
    lab: 'force',
    formula: 'F = ma',
    scenario: 'a magnetic launch sled on a test track',
    crisis: 'The 6.5 kg sled must leave the rail carrying exactly 91 N of drive force, but the acceleration setpoint is wrong.',
    insight: 'Force, mass, and acceleration are locked together. Fix any two and the third is decided for you.',
    resolution: 'At the solved acceleration the drive force lands on 91 N and the sled clears the rail cleanly.',
    model: {
      kind: 'proportional',
      params: { k: 6.5, targetY: 91, leftName: 'Drive force', rightName: 'Required force', productUnit: 'N' },
      control: { label: 'Acceleration setpoint', unit: 'm/s²', min: 0, max: 30, precision: 1 },
      tolerance: 4,
      start: 85,
    },
  },
  {
    slug: 'momentum-transfer',
    title: 'Momentum transfer',
    lab: 'collision',
    formula: 'p = mv',
    scenario: 'a docking clamp catching a drifting supply pod',
    crisis: 'The clamp absorbs at most 8.4 kg·m/s. The 1.4 kg pod is closing too fast and will bounce off instead of latching.',
    insight: 'Momentum is mass carried by speed. A light object moving fast can hit as hard as a heavy one drifting slowly.',
    resolution: 'Slowed to the solved approach speed, the pod arrives with exactly the momentum the clamp can absorb.',
    model: {
      kind: 'proportional',
      params: { k: 1.4, targetY: 8.4, leftName: 'Pod momentum', rightName: 'Clamp limit', productUnit: 'kg·m/s' },
      control: { label: 'Approach speed', unit: 'm/s', min: 0, max: 14, precision: 2 },
      tolerance: 0.5,
      start: 92,
    },
  },
  {
    slug: 'energy-conservation',
    title: 'Energy conservation',
    lab: 'energy',
    formula: 'E_T = E_k + E_p',
    scenario: 'a gravity-fed water tower feeding an emergency turbine',
    crisis: 'The system holds 500 J in total. Stored height energy accounts for 320 J. The kinetic reading is drifting and the turbine is stalling.',
    insight: 'Energy is not created at the turbine. It is traded — height energy converts into motion energy, and the total never changes.',
    resolution: 'At the solved kinetic value the two forms sum to the full 500 J and the turbine runs steady.',
    model: {
      kind: 'sumToConstant',
      params: { known: 320, total: 500, leftName: 'Total accounted', rightName: 'System energy', productUnit: 'J' },
      control: { label: 'Kinetic energy', unit: 'J', min: 0, max: 400, precision: 0 },
      tolerance: 12,
      start: 8,
    },
  },
  {
    slug: 'power-networks',
    title: 'Power networks',
    lab: 'circuit',
    formula: 'P = VI',
    scenario: 'a field hospital running on a single generator line',
    crisis: 'The ward needs 300 W delivered at 2.5 A. The supply voltage is set wrong and the lights keep browning out.',
    insight: 'Power is voltage and current together. Halving the voltage at fixed current halves the power delivered.',
    resolution: 'At the solved supply voltage the line delivers exactly 300 W and the ward stabilises.',
    model: {
      kind: 'proportional',
      params: { k: 2.5, targetY: 300, leftName: 'Delivered power', rightName: 'Ward demand', productUnit: 'W' },
      control: { label: 'Supply voltage', unit: 'V', min: 20, max: 220, precision: 0 },
      tolerance: 14,
      start: 10,
    },
  },
  {
    slug: 'series-circuits',
    title: 'Series circuits',
    lab: 'circuit',
    formula: 'R_T = R_1 + R_2',
    scenario: 'a signal repeater that keeps burning out its driver',
    crisis: 'The driver survives only if the loop presents 320 Ω. One fixed resistor gives 180 Ω. The second is set wrong.',
    insight: 'In a single loop there is one path, so resistances simply add. Every extra component makes the current smaller.',
    resolution: 'With the second resistor at the solved value the loop totals 320 Ω and the driver runs cool.',
    model: {
      kind: 'sumToConstant',
      params: { known: 180, total: 320, leftName: 'Loop resistance', rightName: 'Safe resistance', productUnit: 'Ω' },
      control: { label: 'Second resistor', unit: 'Ω', min: 0, max: 300, precision: 0 },
      tolerance: 9,
      start: 90,
    },
  },
  {
    slug: 'parallel-circuits',
    title: 'Parallel circuits',
    lab: 'circuit',
    formula: '\\frac{1}{R_T} = \\frac{1}{R_1} + \\frac{1}{R_2}',
    scenario: 'a rover heater bank drawing from one battery bus',
    crisis: 'The bus needs to see 48 Ω combined. One heater element is fixed at 120 Ω. The second element is misconfigured.',
    insight: 'Parallel paths give current more ways through, so the combined resistance is always smaller than either branch alone.',
    resolution: 'At the solved second-branch value the pair combine to 48 Ω and the heater bank draws its designed current.',
    model: {
      kind: 'reciprocalSum',
      params: { known: 120, combined: 48, leftName: 'Combined resistance', rightName: 'Bus requirement', productUnit: 'Ω' },
      control: { label: 'Second branch', unit: 'Ω', min: 20, max: 180, precision: 0 },
      tolerance: 1.5,
      start: 88,
    },
  },
  {
    slug: 'voltage-loops',
    title: 'Voltage loops',
    lab: 'circuit',
    formula: '\\sum V = 0',
    scenario: 'a battery bank feeding a comms mast',
    crisis: 'The 9.0 V source must be fully accounted for around the loop. Known drops total 5.4 V, leaving one unmeasured component.',
    insight: 'Walk any closed loop and the voltage you gain must equal the voltage you lose. Energy cannot vanish partway round.',
    resolution: 'At the solved drop the loop closes on zero and the mast holds a clean signal.',
    model: {
      kind: 'sumToConstant',
      params: { known: 5.4, total: 9, leftName: 'Accounted drops', rightName: 'Source EMF', productUnit: 'V' },
      control: { label: 'Unknown component drop', unit: 'V', min: 0, max: 9, precision: 2 },
      tolerance: 0.3,
      start: 92,
    },
  },
  {
    slug: 'magnetic-flux',
    title: 'Magnetic flux',
    lab: 'magnet',
    formula: '\\Phi_B = BA',
    scenario: 'an induction charging pad under a hospital trolley',
    crisis: 'The 0.04 m² receiver coil needs 0.012 Wb of flux to charge. The field strength is set too low to couple.',
    insight: 'Flux counts field lines through an area. A weak field over a wide loop can carry the same flux as a strong field over a narrow one.',
    resolution: 'At the solved field strength the coil sees exactly 0.012 Wb and charging begins.',
    model: {
      kind: 'proportional',
      params: { k: 0.04, targetY: 0.012, leftName: 'Coil flux', rightName: 'Required flux', productUnit: 'Wb' },
      control: { label: 'Field strength', unit: 'T', min: 0, max: 0.8, precision: 3 },
      tolerance: 0.0011,
      start: 8,
    },
  },
  {
    slug: 'electromagnet-strength',
    title: 'Electromagnet strength',
    lab: 'magnet',
    formula: 'B \\propto NI',
    scenario: 'a scrapyard lifting magnet that keeps dropping its load',
    crisis: 'Holding the load needs 0.32 T. Each turn of the coil contributes 0.0008 T at the working current, and the winding count is wrong.',
    insight: 'More turns means more field for the same current. The coil multiplies the current’s magnetic effect.',
    resolution: 'At the solved turn count the magnet reaches 0.32 T and holds the load without slipping.',
    model: {
      kind: 'proportional',
      params: { k: 0.0008, targetY: 0.32, leftName: 'Field produced', rightName: 'Field required', productUnit: 'T' },
      control: { label: 'Coil turns', unit: 'turns', min: 0, max: 900, precision: 0 },
      tolerance: 0.02,
      start: 90,
    },
  },
  {
    slug: 'wave-frequency',
    title: 'Wave frequency',
    lab: 'wave',
    formula: 'v = f\\lambda',
    scenario: 'a sonar buoy searching a channel for a sunken hull',
    crisis: 'Sound travels this water at 340 m/s and the array is tuned to a 1.7 m wavelength. The transmit frequency does not match, so nothing returns.',
    insight: 'Speed, frequency and wavelength are one relationship. Fix the medium and choosing a frequency chooses the wavelength.',
    resolution: 'At the solved frequency the wave travels at exactly 340 m/s and the array locks on.',
    model: {
      kind: 'waveSpeed',
      params: { speed: 340, wavelength: 1.7, leftName: 'Wave speed', rightName: 'Medium speed', productUnit: 'm/s' },
      control: { label: 'Transmit frequency', unit: 'Hz', min: 20, max: 450, precision: 0 },
      tolerance: 20,
      start: 90,
    },
  },
  {
    slug: 'refraction-paths',
    title: 'Refraction paths',
    lab: 'lens',
    formula: 'n_1\\sin\\theta_1 = n_2\\sin\\theta_2',
    scenario: 'a laser survey line entering a flooded tunnel',
    crisis: 'The beam must leave the water at 32° to hit the far marker. Water is 1.33, air is 1.00, and the incoming angle is wrong.',
    insight: 'Light bends because it changes speed. The denser medium always holds the ray closer to the normal.',
    resolution: 'At the solved incident angle the beam refracts onto exactly 32° and strikes the marker.',
    model: {
      kind: 'snell',
      params: { n1: 1, n2: 1.33, theta2: 32, leftName: 'Incident side', rightName: 'Exit side', productUnit: '' },
      control: { label: 'Incident angle', unit: '°', min: 0, max: 85, precision: 1 },
      tolerance: 0.028,
      start: 12,
    },
  },
  {
    slug: 'convex-lenses',
    title: 'Convex lenses',
    lab: 'lens',
    formula: '\\frac{1}{f} = \\frac{1}{d_o} + \\frac{1}{d_i}',
    scenario: 'a projector rebuilt from salvage for a night briefing',
    crisis: 'The lens has a 12 cm focal length and the slide sits 30 cm away, but the screen distance is wrong and the image is a blur.',
    insight: 'Object distance and image distance trade against each other around a fixed focal length. Move one and the other must follow.',
    resolution: 'At the solved image distance the lens equation closes and the projection snaps into focus.',
    model: {
      kind: 'reciprocalSum',
      params: { known: 30, combined: 12, leftName: 'Lens equation', rightName: 'Focal length', productUnit: 'cm' },
      control: { label: 'Screen distance', unit: 'cm', min: 5, max: 60, precision: 1 },
      tolerance: 0.8,
      start: 82,
    },
  },
  {
    slug: 'mirror-angles',
    title: 'Mirror angles',
    lab: 'mirror',
    formula: '\\theta_i = \\theta_r',
    scenario: 'a periscope relay assembled to see over a debris wall',
    crisis: 'The reflected ray must leave at 38° to reach the second mirror. The incoming angle is set wrong and the image misses entirely.',
    insight: 'A flat mirror does one thing perfectly: it sends light out at the same angle it came in, measured from the normal.',
    resolution: 'At the solved incident angle the reflection lands on 38° and the relay completes.',
    model: {
      kind: 'proportional',
      params: { k: 1, targetY: 38, leftName: 'Incident angle', rightName: 'Required reflection', productUnit: '°' },
      control: { label: 'Incident angle', unit: '°', min: 0, max: 80, precision: 1 },
      tolerance: 2,
      start: 92,
    },
  },
  {
    slug: 'sound-resonance',
    title: 'Sound resonance',
    lab: 'wave',
    formula: 'f_1 = \\frac{v}{2L}',
    scenario: 'a warning horn being tuned before a storm front arrives',
    crisis: 'The horn must sound its fundamental at 140 Hz. Sound moves at 343 m/s in this air, and the tube length is wrong.',
    insight: 'A pipe picks the note. Its length sets which wavelength fits, and the medium speed turns that into a frequency.',
    resolution: 'At the solved tube length the fundamental lands on 140 Hz and the horn carries across the valley.',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 343, leftB: 1, rightA: 280, leftName: 'Wave speed', rightName: 'Tube response', productUnit: 'm/s' },
      control: { label: 'Tube length', unit: 'm', min: 0.2, max: 2.4, precision: 2 },
      tolerance: 16,
      start: 88,
    },
  },
  {
    slug: 'pressure-systems',
    title: 'Pressure systems',
    lab: 'hydraulic',
    formula: 'P = \\frac{F}{A}',
    scenario: 'an ice-shelf research hut resting on soft snow',
    crisis: 'The hut presses down with 4500 N. The snow collapses above 18 kPa, and the current footing area is far too small.',
    insight: 'The same weight can be safe or destructive depending on the area it acts over. Spreading load lowers pressure.',
    resolution: 'At the solved footing area the pressure drops to exactly 18 kPa and the snow holds.',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 4500, leftB: 1, rightA: 18000, leftName: 'Applied force', rightName: 'Pressure × area', productUnit: 'N' },
      control: { label: 'Footing area', unit: 'm²', min: 0.05, max: 0.5, precision: 3 },
      tolerance: 250,
      start: 6,
    },
  },
  {
    slug: 'hydraulic-lifts',
    title: 'Hydraulic lifts',
    lab: 'hydraulic',
    formula: '\\frac{F_1}{A_1} = \\frac{F_2}{A_2}',
    scenario: 'a workshop jack lifting a collapsed roof beam',
    crisis: 'A hand pump gives 250 N on a 0.005 m² piston. The 0.08 m² output ram is not producing the force the beam needs.',
    insight: 'Pressure passes through the fluid unchanged. A larger output piston converts that same pressure into a larger force.',
    resolution: 'At the solved output force the pressures match on both sides and the beam lifts.',
    model: {
      kind: 'inverseProduct',
      params: { leftA: 250, leftB: 0.08, rightA: 0.005, leftName: 'Input side', rightName: 'Output side', productUnit: 'N·m²' },
      control: { label: 'Output force', unit: 'N', min: 500, max: 7000, precision: 0 },
      tolerance: 0.5,
      start: 8,
    },
  },
  {
    slug: 'heat-transfer',
    title: 'Heat transfer',
    lab: 'thermal',
    formula: 'Q = mc\\Delta T',
    scenario: 'a shelter boiler warming water for a hundred people',
    crisis: 'The burner delivers 209 kJ into 2.5 kg of water. The temperature rise setpoint is wrong, so the controller keeps cutting out.',
    insight: 'How much a substance warms depends on its mass and on how stubbornly it resists heating. Water resists a lot.',
    resolution: 'At the solved temperature rise the energy books balance at 209 kJ and the boiler runs continuously.',
    model: {
      kind: 'heatTransfer',
      params: { mass: 2.5, specificHeat: 4180, heat: 209000, leftName: 'Energy absorbed', rightName: 'Energy supplied', productUnit: 'J' },
      control: { label: 'Temperature rise', unit: 'K', min: 0, max: 45, precision: 1 },
      tolerance: 10000,
      start: 88,
    },
  },
  {
    slug: 'phase-energy',
    title: 'Phase energy',
    lab: 'thermal',
    formula: 'Q = mL',
    scenario: 'an ice core lab melting a sample without overheating it',
    crisis: 'The chamber can deliver 100.2 kJ. Ice needs 334 kJ per kilogram to melt, and the sample mass is set wrong.',
    insight: 'While something changes state its temperature stays put. All the energy goes into breaking the structure, not warming it.',
    resolution: 'At the solved sample mass the delivered energy melts it exactly, with none left to overheat the core.',
    model: {
      kind: 'proportional',
      params: { k: 334000, targetY: 100200, leftName: 'Energy needed', rightName: 'Energy available', productUnit: 'J' },
      control: { label: 'Sample mass', unit: 'kg', min: 0, max: 0.7, precision: 3 },
      tolerance: 5000,
      start: 90,
    },
  },
  {
    slug: 'projectile-paths',
    title: 'Projectile paths',
    lab: 'projectile',
    formula: 'R = \\frac{v_0^2\\sin 2\\theta}{g}',
    scenario: 'a line-throwing gun firing a rescue rope across a river',
    crisis: 'The far bank is 96 m away. The launcher is locked at 40°, and the muzzle speed is wrong — every shot falls short.',
    insight: 'Range grows with the square of launch speed. A small speed increase reaches dramatically further.',
    resolution: 'At the solved muzzle speed the rope lands exactly on the far bank.',
    model: {
      kind: 'projectileRange',
      params: { range: 96, angle: 40, leftName: 'Predicted range', rightName: 'Required range', productUnit: 'm' },
      control: { label: 'Muzzle speed', unit: 'm/s', min: 10, max: 50, precision: 1 },
      tolerance: 6,
      start: 10,
    },
  },
  {
    slug: 'gravity-fields',
    title: 'Gravity fields',
    lab: 'orbit',
    formula: 'F_g = \\frac{Gm_1m_2}{r^2}',
    scenario: 'a survey satellite choosing a stable orbit altitude',
    crisis: 'Station-keeping works only while gravitational pull sits at 4.0 kN. The current orbital radius puts the craft far outside that window.',
    insight: 'Gravity falls off with the square of distance. Doubling the separation cuts the pull to a quarter, not a half.',
    resolution: 'At the solved orbital radius the pull settles on 4.0 kN and the orbit holds without correction burns.',
    model: {
      kind: 'inverseSquare',
      params: { constant: 398500, targetForce: 4000, leftName: 'Gravitational pull', rightName: 'Station-keeping target', productUnit: 'N' },
      control: { label: 'Orbital radius', unit: 'Mm', min: 6.4, max: 14, precision: 2 },
      tolerance: 180,
      start: 92,
    },
  },
];

export default physics;
